-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["Paua Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, },
	implicit = "(20-30)% increased Mana Regeneration Rate",
	implicitModTypes = { { "mana" }, },
	req = { },
}
itemBases["Coral Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, },
	implicit = "Regenerate (2-4) Life per second",
	implicitModTypes = { { "flat_life_regen", "life" }, },
	req = { },
}
itemBases["Amber Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, },
	implicit = "+(20-30) to Strength",
	implicitModTypes = { { "jewellery_attribute" }, },
	req = { level = 5, },
}
itemBases["Jade Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, },
	implicit = "+(20-30) to Dexterity",
	implicitModTypes = { { "jewellery_attribute" }, },
	req = { level = 5, },
}
itemBases["Lapis Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, },
	implicit = "+(20-30) to Intelligence",
	implicitModTypes = { { "jewellery_attribute" }, },
	req = { level = 5, },
}
itemBases["Gold Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, },
	implicit = "(12-20)% increased Rarity of Items found",
	implicitModTypes = { {  }, },
	req = { level = 8, },
}
itemBases["Onyx Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, },
	implicit = "+(10-16) to all Attributes",
	implicitModTypes = { { "jewellery_attribute" }, },
	req = { level = 20, },
}
itemBases["Turquoise Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, },
	implicit = "+(16-24) to Dexterity and Intelligence",
	implicitModTypes = { { "jewellery_attribute" }, },
	req = { level = 16, },
}
itemBases["Agate Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, },
	implicit = "+(16-24) to Strength and Intelligence",
	implicitModTypes = { { "jewellery_attribute" }, },
	req = { level = 16, },
}
itemBases["Citrine Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, },
	implicit = "+(16-24) to Strength and Dexterity",
	implicitModTypes = { { "jewellery_attribute" }, },
	req = { level = 16, },
}
itemBases["Ruby Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, not_for_sale = true, },
	implicit = "+(20-30)% to Fire Resistance",
	implicitModTypes = { { "fire", "jewellery_resistance" }, },
	req = { },
}
itemBases["Blue Pearl Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, not_for_sale = true, atlas_base_type = true, amuletatlas1 = true, },
	implicit = "(48-56)% increased Mana Regeneration Rate",
	implicitModTypes = { { "mana" }, },
	req = { level = 77, },
}
itemBases["Marble Amulet"] = {
	type = "Amulet",
	tags = { default = true, amulet = true, not_for_sale = true, atlas_base_type = true, amuletatlas2 = true, },
	implicit = "Regenerate (1.2-1.6)% of Life per second",
	implicitModTypes = { { "life" }, },
	req = { level = 74, },
}

itemBases["Jet Amulet"] = {
	type = "Amulet",
	hidden = true,
	tags = { default = true, amulet = true, not_for_sale = true, },
	implicit = "+(8-12)% to all Elemental Resistances",
	implicitModTypes = { { "elemental", "jewellery_resistance" }, },
	req = { level = 12, },
}

itemBases["Black Maw Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "Has 1 Socket",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Bonespire Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(20-30)% increased maximum Mana",
	implicitModTypes = { { "mana" }, },
	req = { },
}
itemBases["Ashscale Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(20-30)% increased Fire Damage",
	implicitModTypes = { { "fire", "jewellery_elemental" }, },
	req = { },
}
itemBases["Lone Antler Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(20-30)% increased Lightning Damage",
	implicitModTypes = { { "lightning", "jewellery_elemental" }, },
	req = { },
}
itemBases["Deep One Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(20-30)% increased Cold Damage",
	implicitModTypes = { { "cold", "jewellery_elemental" }, },
	req = { },
}
itemBases["Breakrib Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(20-30)% increased Global Physical Damage",
	implicitModTypes = { { "physical" }, },
	req = { },
}
itemBases["Deadhand Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(19-31)% increased Chaos Damage",
	implicitModTypes = { { "chaos" }, },
	req = { },
}
itemBases["Undying Flesh Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "+1 to maximum number of Raised Zombies",
	implicitModTypes = { { "minion" }, },
	req = { },
}
itemBases["Rot Head Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(30-40)% increased Fish Bite Sensitivity",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Mandible Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(6-10)% increased Attack and Cast Speed",
	implicitModTypes = { { "speed", "jewellery_attack", "jewellery_caster", "attack", "caster" }, },
	req = { },
}
itemBases["Chrysalis Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(20-30)% increased Spell Damage",
	implicitModTypes = { { "caster" }, },
	req = { },
}
itemBases["Writhing Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(20-30)% increased Attack Damage",
	implicitModTypes = { { "jewellery_attack", "attack" }, },
	req = { },
}
itemBases["Hexclaw Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(40-50)% increased Global Critical Strike Chance",
	implicitModTypes = { { "critical" }, },
	req = { },
}
itemBases["Primal Skull Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "Regenerate 2% of Life per second",
	implicitModTypes = { { "life" }, },
	req = { },
}
itemBases["Wereclaw Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "+(24-36)% to Global Critical Strike Multiplier",
	implicitModTypes = { { "critical" }, },
	req = { },
}
itemBases["Splitnewt Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(4-6)% chance to Freeze, Shock and Ignite",
	implicitModTypes = { { "jewellery_elemental" }, },
	req = { },
}
itemBases["Clutching Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(15-25)% increased Global Defences",
	implicitModTypes = { { "defences", "jewellery_defense" }, },
	req = { },
}
itemBases["Avian Twins Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "50% of Fire Damage from Hits taken as Cold Damage",
	implicitModTypes = { { "fire", "cold" }, },
	req = { },
}
itemBases["Avian Twins Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "50% of Fire Damage from Hits taken as Lightning Damage",
	implicitModTypes = { { "fire", "lightning" }, },
	req = { },
}
itemBases["Avian Twins Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "50% of Cold Damage from Hits taken as Fire Damage",
	implicitModTypes = { { "fire", "cold" }, },
	req = { },
}
itemBases["Avian Twins Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "50% of Cold Damage from Hits taken as Lightning Damage",
	implicitModTypes = { { "cold", "lightning" }, },
	req = { },
}
itemBases["Avian Twins Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "50% of Lightning Damage from Hits taken as Cold Damage",
	implicitModTypes = { { "cold", "lightning" }, },
	req = { },
}
itemBases["Avian Twins Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "50% of Lightning Damage from Hits taken as Fire Damage",
	implicitModTypes = { { "fire", "lightning" }, },
	req = { },
}
itemBases["Fangjaw Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(8-12)% increased maximum Life",
	implicitModTypes = { { "life" }, },
	req = { },
}
itemBases["Horned Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "Projectiles Pierce 2 additional Targets",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Spinefuse Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(6-10)% increased Quantity of Items found",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Three Rat Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(12-16)% increased Attributes",
	implicitModTypes = { { "jewellery_attribute" }, },
	req = { },
}
itemBases["Monkey Twins Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(5-8)% increased Area of Effect",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Longtooth Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(4-6)% additional Physical Damage Reduction",
	implicitModTypes = { { "physical" }, },
	req = { },
}
itemBases["Rotfeather Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "(25-35)% increased Damage",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Monkey Paw Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "10% chance to gain a Power Charge on Kill",
	implicitModTypes = { { "critical" }, },
	req = { },
}
itemBases["Monkey Paw Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "10% chance to gain a Frenzy Charge on Kill",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Monkey Paw Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "10% chance to gain an Endurance Charge on Kill",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Three Hands Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, talisman = true, },
	implicit = "Gain (6-12)% of Physical Damage as Extra Damage of a random Element",
	implicitModTypes = { { "physical", "elemental", "jewellery_elemental" }, },
	req = { },
}
itemBases["Greatwolf Talisman"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, amulet = true, },
	implicitModTypes = { },
	req = { },
}
