-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["Rusted Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 4, PhysicalMax = 10, CritChanceBase = 5, AttackRateBase = 1.45, },
	req = { str = 8, dex = 8, },
}
itemBases["Copper Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "+45 to Accuracy Rating",
	weapon = { PhysicalMin = 7, PhysicalMax = 15, CritChanceBase = 5, AttackRateBase = 1.4, },
	req = { level = 5, str = 14, dex = 14, },
}
itemBases["Sabre"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 5, PhysicalMax = 22, CritChanceBase = 5, AttackRateBase = 1.55, },
	req = { level = 10, str = 18, dex = 26, },
}
itemBases["Broad Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 17, PhysicalMax = 25, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 15, str = 30, dex = 30, },
}
itemBases["War Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 20, PhysicalMax = 37, CritChanceBase = 5, AttackRateBase = 1.2, },
	req = { level = 20, str = 41, dex = 35, },
}
itemBases["Ancient Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "+165 to Accuracy Rating",
	weapon = { PhysicalMin = 20, PhysicalMax = 38, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 24, str = 44, dex = 44, },
}
itemBases["Elegant Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "+190 to Accuracy Rating",
	weapon = { PhysicalMin = 20, PhysicalMax = 33, CritChanceBase = 5, AttackRateBase = 1.5, },
	req = { level = 28, str = 46, dex = 55, },
}
itemBases["Dusk Blade"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 19, PhysicalMax = 54, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 32, str = 57, dex = 57, },
}
itemBases["Hook Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "4% chance to Dodge Attacks",
	weapon = { PhysicalMin = 28, PhysicalMax = 60, CritChanceBase = 5, AttackRateBase = 1.15, },
	req = { level = 34, str = 64, dex = 64, },
}
itemBases["Variscite Blade"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "+240 to Accuracy Rating",
	weapon = { PhysicalMin = 25, PhysicalMax = 53, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 35, str = 62, dex = 62, },
}
itemBases["Cutlass"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 13, PhysicalMax = 53, CritChanceBase = 5, AttackRateBase = 1.55, },
	req = { level = 38, str = 55, dex = 79, },
}
itemBases["Baselard"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 37, PhysicalMax = 53, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 41, str = 72, dex = 72, },
}
itemBases["Battle Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 38, PhysicalMax = 70, CritChanceBase = 5, AttackRateBase = 1.2, },
	req = { level = 44, str = 83, dex = 70, },
}
itemBases["Elder Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "+330 to Accuracy Rating",
	weapon = { PhysicalMin = 36, PhysicalMax = 66, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 47, str = 81, dex = 81, },
}
itemBases["Graceful Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "+350 to Accuracy Rating",
	weapon = { PhysicalMin = 34, PhysicalMax = 55, CritChanceBase = 5, AttackRateBase = 1.5, },
	req = { level = 50, str = 78, dex = 94, },
}
itemBases["Twilight Blade"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 30, PhysicalMax = 86, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 53, str = 91, dex = 91, },
}
itemBases["Grappler"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "4% chance to Dodge Attacks",
	weapon = { PhysicalMin = 44, PhysicalMax = 94, CritChanceBase = 5, AttackRateBase = 1.15, },
	req = { level = 55, str = 99, dex = 99, },
}
itemBases["Gemstone Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "+400 to Accuracy Rating",
	weapon = { PhysicalMin = 39, PhysicalMax = 83, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 56, str = 96, dex = 96, },
}
itemBases["Corsair Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 20, PhysicalMax = 80, CritChanceBase = 5, AttackRateBase = 1.55, },
	req = { level = 58, str = 81, dex = 117, },
}
itemBases["Gladius"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 54, PhysicalMax = 78, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 60, str = 113, dex = 113, },
}
itemBases["Legion Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 53, PhysicalMax = 98, CritChanceBase = 5, AttackRateBase = 1.2, },
	req = { level = 62, str = 122, dex = 104, },
}
itemBases["Vaal Blade"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "+460 to Accuracy Rating",
	weapon = { PhysicalMin = 46, PhysicalMax = 86, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 64, str = 113, dex = 113, },
}
itemBases["Eternal Sword"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "+475 to Accuracy Rating",
	weapon = { PhysicalMin = 41, PhysicalMax = 68, CritChanceBase = 5, AttackRateBase = 1.5, },
	req = { level = 66, str = 104, dex = 122, },
}
itemBases["Midnight Blade"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 35, PhysicalMax = 99, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 68, str = 113, dex = 113, },
}
itemBases["Tiger Hook"] = {
	type = "One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "6% chance to Dodge Attacks",
	weapon = { PhysicalMin = 49, PhysicalMax = 105, CritChanceBase = 5, AttackRateBase = 1.15, },
	req = { level = 70, str = 119, dex = 119, },
}

itemBases["Rusted Spike"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 5, PhysicalMax = 13, CritChanceBase = 5.5, AttackRateBase = 1.4, },
	req = { dex = 20, },
}
itemBases["Whalebone Rapier"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 4, PhysicalMax = 18, CritChanceBase = 5.5, AttackRateBase = 1.55, },
	req = { level = 7, dex = 32, },
}
itemBases["Battered Foil"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 12, PhysicalMax = 22, CritChanceBase = 6, AttackRateBase = 1.4, },
	req = { level = 12, dex = 47, },
}
itemBases["Basket Rapier"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 11, PhysicalMax = 26, CritChanceBase = 5.5, AttackRateBase = 1.5, },
	req = { level = 17, dex = 62, },
}
itemBases["Jagged Foil"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 12, PhysicalMax = 29, CritChanceBase = 5.5, AttackRateBase = 1.6, },
	req = { level = 22, dex = 77, },
}
itemBases["Antique Rapier"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 12, PhysicalMax = 46, CritChanceBase = 6.5, AttackRateBase = 1.3, },
	req = { level = 26, dex = 89, },
}
itemBases["Elegant Foil"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 18, PhysicalMax = 33, CritChanceBase = 5.5, AttackRateBase = 1.6, },
	req = { level = 30, dex = 101, },
}
itemBases["Thorn Rapier"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+35% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 19, PhysicalMax = 44, CritChanceBase = 5.7, AttackRateBase = 1.4, },
	req = { level = 34, dex = 113, },
}
itemBases["Smallsword"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, not_for_sale = true, maraketh = true, },
	implicit = "15% chance to cause Bleeding on Hit",
	weapon = { PhysicalMin = 19, PhysicalMax = 40, CritChanceBase = 6, AttackRateBase = 1.55, },
	req = { level = 36, dex = 124, },
}
itemBases["Wyrmbone Rapier"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 13, PhysicalMax = 51, CritChanceBase = 5.5, AttackRateBase = 1.5, },
	req = { level = 37, dex = 122, },
}
itemBases["Burnished Foil"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 25, PhysicalMax = 46, CritChanceBase = 6, AttackRateBase = 1.4, },
	req = { level = 40, dex = 131, },
}
itemBases["Estoc"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 21, PhysicalMax = 50, CritChanceBase = 5.5, AttackRateBase = 1.5, },
	req = { level = 43, dex = 140, },
}
itemBases["Serrated Foil"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 21, PhysicalMax = 49, CritChanceBase = 5.5, AttackRateBase = 1.6, },
	req = { level = 46, dex = 149, },
}
itemBases["Primeval Rapier"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 18, PhysicalMax = 73, CritChanceBase = 6.5, AttackRateBase = 1.3, },
	req = { level = 49, dex = 158, },
}
itemBases["Fancy Foil"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 28, PhysicalMax = 51, CritChanceBase = 5.5, AttackRateBase = 1.6, },
	req = { level = 52, dex = 167, },
}
itemBases["Apex Rapier"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+35% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 29, PhysicalMax = 67, CritChanceBase = 5.7, AttackRateBase = 1.4, },
	req = { level = 55, dex = 176, },
}
itemBases["Courtesan Sword"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, not_for_sale = true, maraketh = true, },
	implicit = "15% chance to cause Bleeding on Hit",
	weapon = { PhysicalMin = 29, PhysicalMax = 60, CritChanceBase = 6, AttackRateBase = 1.55, },
	req = { level = 57, dex = 190, },
}
itemBases["Dragonbone Rapier"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 19, PhysicalMax = 75, CritChanceBase = 5.5, AttackRateBase = 1.5, },
	req = { level = 58, dex = 185, },
}
itemBases["Tempered Foil"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 35, PhysicalMax = 65, CritChanceBase = 6, AttackRateBase = 1.4, },
	req = { level = 60, dex = 212, },
}
itemBases["Pecoraro"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 29, PhysicalMax = 69, CritChanceBase = 5.5, AttackRateBase = 1.5, },
	req = { level = 62, dex = 212, },
}
itemBases["Spiraled Foil"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 27, PhysicalMax = 64, CritChanceBase = 5.5, AttackRateBase = 1.6, },
	req = { level = 64, dex = 212, },
}
itemBases["Vaal Rapier"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 22, PhysicalMax = 87, CritChanceBase = 6.5, AttackRateBase = 1.3, },
	req = { level = 66, dex = 212, },
}
itemBases["Jewelled Foil"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+25% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 32, PhysicalMax = 60, CritChanceBase = 5.5, AttackRateBase = 1.6, },
	req = { level = 68, dex = 212, },
}
itemBases["Harpy Rapier"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, },
	implicit = "+35% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 31, PhysicalMax = 72, CritChanceBase = 5.7, AttackRateBase = 1.4, },
	req = { level = 70, dex = 212, },
}
itemBases["Dragoon Sword"] = {
	type = "Thrusting One Handed Sword",
	tags = { default = true, weapon = true, onehand = true, sword = true, one_hand_weapon = true, rapier = true, not_for_sale = true, maraketh = true, },
	implicit = "20% chance to cause Bleeding on Hit",
	weapon = { PhysicalMin = 32, PhysicalMax = 66, CritChanceBase = 6, AttackRateBase = 1.5, },
	req = { level = 72, dex = 220, },
}

itemBases["Keyblade"] = {
	type = "Two Handed Sword",
	hidden = true,
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, not_for_sale = true, },
	weapon = { PhysicalMin = 1, PhysicalMax = 1, CritChanceBase = 5, AttackRateBase = 1.2, },
	req = { str = 8, dex = 8, },
}
itemBases["Corroded Blade"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 7, PhysicalMax = 13, CritChanceBase = 5, AttackRateBase = 1.45, },
	req = { str = 11, dex = 11, },
}
itemBases["Longsword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "+60 to Accuracy Rating",
	weapon = { PhysicalMin = 10, PhysicalMax = 24, CritChanceBase = 5, AttackRateBase = 1.35, },
	req = { level = 8, str = 20, dex = 17, },
}
itemBases["Bastard Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 15, PhysicalMax = 25, CritChanceBase = 5, AttackRateBase = 1.45, },
	req = { level = 12, str = 21, dex = 30, },
}
itemBases["Two-Handed Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "+120 to Accuracy Rating",
	weapon = { PhysicalMin = 19, PhysicalMax = 34, CritChanceBase = 5, AttackRateBase = 1.35, },
	req = { level = 17, str = 33, dex = 33, },
}
itemBases["Etched Greatsword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 22, PhysicalMax = 46, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 22, str = 45, dex = 38, },
}
itemBases["Ornate Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "+185 to Accuracy Rating",
	weapon = { PhysicalMin = 26, PhysicalMax = 43, CritChanceBase = 5, AttackRateBase = 1.4, },
	req = { level = 27, str = 45, dex = 54, },
}
itemBases["Spectral Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "30% increased Accuracy Rating",
	weapon = { PhysicalMin = 27, PhysicalMax = 56, CritChanceBase = 5, AttackRateBase = 1.35, },
	req = { level = 32, str = 57, dex = 57, },
}
itemBases["Curved Blade"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "+40% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 35, PhysicalMax = 58, CritChanceBase = 6, AttackRateBase = 1.35, },
	req = { level = 35, str = 62, dex = 73, },
}
itemBases["Butcher Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "+250 to Accuracy Rating",
	weapon = { PhysicalMin = 29, PhysicalMax = 68, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 36, str = 69, dex = 58, },
}
itemBases["Footman Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 34, PhysicalMax = 56, CritChanceBase = 5, AttackRateBase = 1.45, },
	req = { level = 40, str = 57, dex = 83, },
}
itemBases["Highland Blade"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "+305 to Accuracy Rating",
	weapon = { PhysicalMin = 39, PhysicalMax = 72, CritChanceBase = 5, AttackRateBase = 1.35, },
	req = { level = 44, str = 77, dex = 77, },
}
itemBases["Engraved Greatsword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 42, PhysicalMax = 87, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 48, str = 91, dex = 76, },
}
itemBases["Tiger Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "+360 to Accuracy Rating",
	weapon = { PhysicalMin = 46, PhysicalMax = 76, CritChanceBase = 5, AttackRateBase = 1.4, },
	req = { level = 51, str = 80, dex = 96, },
}
itemBases["Wraith Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "30% increased Accuracy Rating",
	weapon = { PhysicalMin = 45, PhysicalMax = 93, CritChanceBase = 5, AttackRateBase = 1.35, },
	req = { level = 54, str = 93, dex = 93, },
}
itemBases["Lithe Blade"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "+40% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 54, PhysicalMax = 89, CritChanceBase = 6, AttackRateBase = 1.35, },
	req = { level = 56, str = 96, dex = 113, },
}
itemBases["Headman's Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "+400 to Accuracy Rating",
	weapon = { PhysicalMin = 47, PhysicalMax = 109, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 57, str = 106, dex = 89, },
}
itemBases["Reaver Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 52, PhysicalMax = 86, CritChanceBase = 5, AttackRateBase = 1.45, },
	req = { level = 59, str = 82, dex = 119, },
}
itemBases["Ezomyte Blade"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "+435 to Accuracy Rating",
	weapon = { PhysicalMin = 55, PhysicalMax = 102, CritChanceBase = 5, AttackRateBase = 1.35, },
	req = { level = 61, str = 113, dex = 113, },
}
itemBases["Vaal Greatsword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "40% increased Accuracy Rating",
	weapon = { PhysicalMin = 55, PhysicalMax = 113, CritChanceBase = 5, AttackRateBase = 1.3, },
	req = { level = 63, str = 122, dex = 104, },
}
itemBases["Lion Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "+470 to Accuracy Rating",
	weapon = { PhysicalMin = 57, PhysicalMax = 94, CritChanceBase = 5, AttackRateBase = 1.4, },
	req = { level = 65, str = 104, dex = 122, },
}
itemBases["Infernal Sword"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, },
	implicit = "30% increased Accuracy Rating",
	weapon = { PhysicalMin = 52, PhysicalMax = 108, CritChanceBase = 5, AttackRateBase = 1.35, },
	req = { level = 67, str = 113, dex = 113, },
}
itemBases["Exquisite Blade"] = {
	type = "Two Handed Sword",
	tags = { default = true, weapon = true, twohand = true, sword = true, two_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "+60% to Global Critical Strike Multiplier",
	weapon = { PhysicalMin = 56, PhysicalMax = 94, CritChanceBase = 6, AttackRateBase = 1.35, },
	req = { level = 70, str = 119, dex = 131, },
}
