# .github/release.yml

changelog:
  exclude:
    labels:
      - technical
      - invalid
      - duplicate
    authors:
      - github-actions
  categories:
    - title: Implemented Enhancements
      labels:
        - enhancement
    - title: User Interface
      labels:
        - user-interface
    - title: New Calculations
      labels:
        - new-calculations
    - title: Accuracy Improvements
      labels:
        - accuracy
    - title: Fixed Bugs
      labels:
        - bug
    - title: Other changes
      labels:
        - "*"