# .github/release.yml

changelog:
  exclude:
    labels:
      - technical
      - invalid
      - duplicate
    authors:
      - github-actions
  categories:
    - title: Implemented Enhancements
      labels:
        - enhancement
    - title: Fixed Bugs
      labels:
        - bug
    - title: Other changes
      labels:
        - "*"