-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["Plate Vest"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 14, MovementPenalty = 3, },
	req = { str = 12, },
}
itemBases["Chestplate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 49, MovementPenalty = 5, },
	req = { level = 6, str = 25, },
}
itemBases["Copper Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 126, MovementPenalty = 5, },
	req = { level = 17, str = 53, },
}
itemBases["War Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 154, MovementPenalty = 5, },
	req = { level = 21, str = 63, },
}
itemBases["Full Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 203, MovementPenalty = 5, },
	req = { level = 28, str = 81, },
}
itemBases["Arena Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 231, MovementPenalty = 5, },
	req = { level = 32, str = 91, },
}
itemBases["Lordly Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 252, MovementPenalty = 5, },
	req = { level = 35, str = 99, },
}
itemBases["Bronze Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 266, MovementPenalty = 5, },
	req = { level = 37, str = 104, },
}
itemBases["Battle Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 294, MovementPenalty = 5, },
	req = { level = 41, str = 114, },
}
itemBases["Sun Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 322, MovementPenalty = 5, },
	req = { level = 45, str = 124, },
}
itemBases["Colosseum Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 350, MovementPenalty = 5, },
	req = { level = 49, str = 134, },
}
itemBases["Majestic Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 378, MovementPenalty = 5, },
	req = { level = 53, str = 144, },
}
itemBases["Golden Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 399, MovementPenalty = 5, },
	req = { level = 56, str = 152, },
}
itemBases["Crusader Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 428, MovementPenalty = 5, },
	req = { level = 59, str = 160, },
}
itemBases["Astral Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	implicit = "+(8-12)% to all Elemental Resistances",
	armour = { ArmourBase = 507, MovementPenalty = 5, },
	req = { level = 62, str = 180, },
}
itemBases["Gladiator Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 526, MovementPenalty = 5, },
	req = { level = 65, str = 177, },
}
itemBases["Glorious Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	tags = { default = true, armour = true, body_armour = true, str_armour = true, },
	armour = { ArmourBase = 553, },
	req = { level = 68, str = 191, },
}

itemBases["Shabby Jerkin"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 21, MovementPenalty = 3, },
	req = { dex = 14, },
}
itemBases["Strapped Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 70, MovementPenalty = 3, },
	req = { level = 9, dex = 32, },
}
itemBases["Buckskin Tunic"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 126, MovementPenalty = 3, },
	req = { level = 17, dex = 53, },
}
itemBases["Wild Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 182, MovementPenalty = 3, },
	req = { level = 25, dex = 73, },
}
itemBases["Full Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 203, MovementPenalty = 3, },
	req = { level = 28, dex = 81, },
}
itemBases["Sun Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 231, MovementPenalty = 3, },
	req = { level = 32, dex = 91, },
}
itemBases["Thief's Garb"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 252, MovementPenalty = 3, },
	req = { level = 35, dex = 99, },
}
itemBases["Eelskin Tunic"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 266, MovementPenalty = 3, },
	req = { level = 37, dex = 104, },
}
itemBases["Frontier Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 294, MovementPenalty = 3, },
	req = { level = 41, dex = 114, },
}
itemBases["Glorious Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 322, MovementPenalty = 3, },
	req = { level = 45, dex = 124, },
}
itemBases["Coronal Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 350, MovementPenalty = 3, },
	req = { level = 49, dex = 134, },
}
itemBases["Cutthroat's Garb"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 378, MovementPenalty = 3, },
	req = { level = 53, dex = 144, },
}
itemBases["Sharkskin Tunic"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 399, MovementPenalty = 3, },
	req = { level = 56, dex = 152, },
}
itemBases["Destiny Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 428, MovementPenalty = 3, },
	req = { level = 59, dex = 160, },
}
itemBases["Exquisite Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 502, MovementPenalty = 3, },
	req = { level = 62, dex = 170, },
}
itemBases["Zodiac Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	armour = { EvasionBase = 609, MovementPenalty = 3, },
	req = { level = 65, dex = 197, },
}
itemBases["Assassin's Garb"] = {
	type = "Body Armour",
	subType = "Evasion",
	tags = { default = true, armour = true, body_armour = true, dex_armour = true, },
	implicit = "3% increased Movement Speed",
	armour = { EvasionBase = 525, },
	req = { level = 68, dex = 183, },
}

itemBases["Simple Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 11, MovementPenalty = 3, },
	req = { int = 17, },
}
itemBases["Silken Vest"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 27, MovementPenalty = 3, },
	req = { level = 11, int = 37, },
}
itemBases["Scholar's Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 41, MovementPenalty = 3, },
	req = { level = 18, int = 55, },
}
itemBases["Silken Garb"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 55, MovementPenalty = 3, },
	req = { level = 25, int = 73, },
}
itemBases["Mage's Vestment"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 61, MovementPenalty = 3, },
	req = { level = 28, int = 81, },
}
itemBases["Silk Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 69, MovementPenalty = 3, },
	req = { level = 32, int = 91, },
}
itemBases["Cabalist Regalia"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 75, MovementPenalty = 3, },
	req = { level = 35, int = 99, },
}
itemBases["Sage's Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 79, MovementPenalty = 3, },
	req = { level = 37, int = 104, },
}
itemBases["Silken Wrap"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 87, MovementPenalty = 3, },
	req = { level = 41, int = 114, },
}
itemBases["Conjurer's Vestment"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 95, MovementPenalty = 3, },
	req = { level = 45, int = 124, },
}
itemBases["Spidersilk Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 103, MovementPenalty = 3, },
	req = { level = 49, int = 134, },
}
itemBases["Destroyer Regalia"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 111, MovementPenalty = 3, },
	req = { level = 53, int = 144, },
}
itemBases["Savant's Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 117, MovementPenalty = 3, },
	req = { level = 56, int = 152, },
}
itemBases["Necromancer Silks"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 125, MovementPenalty = 3, },
	req = { level = 59, int = 160, },
}
itemBases["Occultist's Vestment"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	implicit = "(3-10)% increased Spell Damage",
	armour = { EnergyShieldBase = 140, MovementPenalty = 3, },
	req = { level = 62, int = 180, },
}
itemBases["Widowsilk Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 161, MovementPenalty = 3, },
	req = { level = 65, int = 187, },
}
itemBases["Vaal Regalia"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	tags = { default = true, armour = true, body_armour = true, int_armour = true, },
	armour = { EnergyShieldBase = 175, MovementPenalty = 3, },
	req = { level = 68, int = 194, },
}

itemBases["Scale Vest"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 19, EvasionBase = 19, MovementPenalty = 3, },
	req = { str = 10, dex = 10, },
}
itemBases["Light Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 35, EvasionBase = 35, MovementPenalty = 3, },
	req = { level = 8, str = 16, dex = 16, },
}
itemBases["Scale Doublet"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 69, EvasionBase = 69, MovementPenalty = 3, },
	req = { level = 17, str = 28, dex = 28, },
}
itemBases["Infantry Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 85, EvasionBase = 85, MovementPenalty = 3, },
	req = { level = 21, str = 34, dex = 34, },
}
itemBases["Full Scale Armour"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 112, EvasionBase = 112, MovementPenalty = 3, },
	req = { level = 28, str = 43, dex = 43, },
}
itemBases["Soldier's Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 127, EvasionBase = 127, MovementPenalty = 3, },
	req = { level = 32, str = 48, dex = 48, },
}
itemBases["Field Lamellar"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 138, EvasionBase = 138, MovementPenalty = 3, },
	req = { level = 35, str = 53, dex = 53, },
}
itemBases["Wyrmscale Doublet"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 150, EvasionBase = 150, MovementPenalty = 3, },
	req = { level = 38, str = 57, dex = 57, },
}
itemBases["Hussar Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 165, EvasionBase = 165, MovementPenalty = 3, },
	req = { level = 42, str = 62, dex = 62, },
}
itemBases["Full Wyrmscale"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 181, EvasionBase = 181, MovementPenalty = 3, },
	req = { level = 46, str = 68, dex = 68, },
}
itemBases["Commander's Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 196, EvasionBase = 196, MovementPenalty = 3, },
	req = { level = 50, str = 73, dex = 73, },
}
itemBases["Battle Lamellar"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 212, EvasionBase = 212, MovementPenalty = 3, },
	req = { level = 54, str = 79, dex = 79, },
}
itemBases["Dragonscale Doublet"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 223, EvasionBase = 223, MovementPenalty = 3, },
	req = { level = 57, str = 83, dex = 83, },
}
itemBases["Desert Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 268, EvasionBase = 268, MovementPenalty = 3, },
	req = { level = 60, str = 96, dex = 96, },
}
itemBases["Full Dragonscale"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 335, EvasionBase = 266, MovementPenalty = 3, },
	req = { level = 63, str = 115, dex = 94, },
}
itemBases["General's Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 296, EvasionBase = 296, MovementPenalty = 3, },
	req = { level = 66, str = 103, dex = 103, },
}
itemBases["Triumphant Lamellar"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	tags = { default = true, armour = true, body_armour = true, str_dex_armour = true, },
	armour = { ArmourBase = 271, EvasionBase = 340, MovementPenalty = 3, },
	req = { level = 69, str = 95, dex = 116, },
}

itemBases["Chainmail Vest"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 19, EnergyShieldBase = 7, MovementPenalty = 5, },
	req = { str = 10, int = 10, },
}
itemBases["Chainmail Tunic"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 35, EnergyShieldBase = 11, MovementPenalty = 5, },
	req = { level = 8, str = 16, int = 16, },
}
itemBases["Ringmail Coat"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 69, EnergyShieldBase = 21, MovementPenalty = 5, },
	req = { level = 17, str = 28, int = 28, },
}
itemBases["Chainmail Doublet"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 85, EnergyShieldBase = 26, MovementPenalty = 5, },
	req = { level = 21, str = 34, int = 34, },
}
itemBases["Full Ringmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 112, EnergyShieldBase = 33, MovementPenalty = 5, },
	req = { level = 28, str = 43, int = 43, },
}
itemBases["Full Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 127, EnergyShieldBase = 38, MovementPenalty = 5, },
	req = { level = 32, str = 48, int = 48, },
}
itemBases["Holy Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 138, EnergyShieldBase = 41, MovementPenalty = 5, },
	req = { level = 35, str = 53, int = 53, },
}
itemBases["Latticed Ringmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 154, EnergyShieldBase = 46, MovementPenalty = 5, },
	req = { level = 39, str = 59, int = 59, },
}
itemBases["Crusader Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 169, EnergyShieldBase = 50, MovementPenalty = 5, },
	req = { level = 43, str = 64, int = 64, },
}
itemBases["Ornate Ringmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 185, EnergyShieldBase = 54, MovementPenalty = 5, },
	req = { level = 47, str = 69, int = 69, },
}
itemBases["Chain Hauberk"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 200, EnergyShieldBase = 59, MovementPenalty = 5, },
	req = { level = 51, str = 75, int = 75, },
}
itemBases["Devout Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 215, EnergyShieldBase = 63, MovementPenalty = 5, },
	req = { level = 55, str = 80, int = 80, },
}
itemBases["Loricated Ringmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 232, EnergyShieldBase = 68, MovementPenalty = 5, },
	req = { level = 58, str = 84, int = 84, },
}
itemBases["Conquest Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 276, EnergyShieldBase = 81, MovementPenalty = 5, },
	req = { level = 61, str = 96, int = 96, },
}
itemBases["Elegant Ringmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 269, EnergyShieldBase = 94, MovementPenalty = 5, },
	req = { level = 64, str = 90, int = 105, },
}
itemBases["Saint's Hauberk"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 315, EnergyShieldBase = 78, MovementPenalty = 5, },
	req = { level = 67, str = 109, int = 94, },
}
itemBases["Saintly Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_int_armour = true, },
	armour = { ArmourBase = 286, EnergyShieldBase = 98, MovementPenalty = 5, },
	req = { level = 70, str = 99, int = 115, },
}

itemBases["Padded Vest"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 19, EnergyShieldBase = 7, MovementPenalty = 3, },
	req = { dex = 10, int = 10, },
}
itemBases["Oiled Vest"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 38, EnergyShieldBase = 13, MovementPenalty = 3, },
	req = { level = 9, dex = 17, int = 17, },
}
itemBases["Padded Jacket"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 73, EnergyShieldBase = 22, MovementPenalty = 3, },
	req = { level = 18, dex = 30, int = 30, },
}
itemBases["Oiled Coat"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 88, EnergyShieldBase = 27, MovementPenalty = 3, },
	req = { level = 22, dex = 35, int = 35, },
}
itemBases["Scarlet Raiment"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 112, EnergyShieldBase = 33, MovementPenalty = 3, },
	req = { level = 28, dex = 43, int = 43, },
}
itemBases["Waxed Garb"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 127, EnergyShieldBase = 38, MovementPenalty = 3, },
	req = { level = 32, dex = 48, int = 48, },
}
itemBases["Bone Armour"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 138, EnergyShieldBase = 41, MovementPenalty = 3, },
	req = { level = 35, dex = 53, int = 53, },
}
itemBases["Quilted Jacket"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 158, EnergyShieldBase = 47, MovementPenalty = 3, },
	req = { level = 40, dex = 60, int = 60, },
}
itemBases["Sleek Coat"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 173, EnergyShieldBase = 51, MovementPenalty = 3, },
	req = { level = 44, dex = 65, int = 65, },
}
itemBases["Crimson Raiment"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 189, EnergyShieldBase = 55, MovementPenalty = 3, },
	req = { level = 48, dex = 71, int = 71, },
}
itemBases["Lacquered Garb"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 204, EnergyShieldBase = 60, MovementPenalty = 3, },
	req = { level = 52, dex = 76, int = 76, },
}
itemBases["Crypt Armour"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 219, EnergyShieldBase = 64, MovementPenalty = 3, },
	req = { level = 56, dex = 82, int = 82, },
}
itemBases["Sentinel Jacket"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 235, EnergyShieldBase = 69, MovementPenalty = 3, },
	req = { level = 59, dex = 86, int = 86, },
}
itemBases["Varnished Coat"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 276, EnergyShieldBase = 81, MovementPenalty = 3, },
	req = { level = 62, dex = 96, int = 96, },
}
itemBases["Blood Raiment"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 311, EnergyShieldBase = 75, MovementPenalty = 3, },
	req = { level = 65, dex = 107, int = 90, },
}
itemBases["Sadist Garb"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	armour = { EvasionBase = 304, EnergyShieldBase = 95, MovementPenalty = 3, },
	req = { level = 68, dex = 103, int = 109, },
}
itemBases["Carnal Armour"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, dex_int_armour = true, },
	implicit = "+(20-25) to maximum Mana",
	armour = { EvasionBase = 251, EnergyShieldBase = 105, MovementPenalty = 3, },
	req = { level = 71, dex = 88, int = 122, },
}

itemBases["Sacrificial Garb"] = {
	type = "Body Armour",
	subType = "Armour/Evasion/Energy Shield",
	tags = { default = true, armour = true, body_armour = true, str_dex_int_armour = true, not_for_sale = true, },
	armour = { ArmourBase = 234, EvasionBase = 234, EnergyShieldBase = 69, MovementPenalty = 3, },
	req = { level = 72, str = 66, dex = 66, int = 66, },
}
itemBases["Golden Mantle"] = {
	type = "Body Armour",
	subType = "Armour/Evasion/Energy Shield",
	hidden = true,
	tags = { default = true, armour = true, body_armour = true, str_dex_int_armour = true, not_for_sale = true, },
	implicit = "+(15-25)% to all Elemental Resistances",
	armour = { ArmourBase = 53, EvasionBase = 53, EnergyShieldBase = 16, },
	req = { level = 20, str = 8, dex = 8, int = 8, },
}
