local t_insert = table.insert

local M = {}

local indentCache = {}
local function indentFor(k)
	if k < 1 then
		return ""
	end
	if not indentCache[k] then
		indentCache[k] = string.rep("\t", k)
	end
	return indentCache[k]
end
local function strSort(a, b)
	return tostring(a) < tostring(b)
end
---@alias StringifyTypes string | number | boolean | nil | table<StringifyTypes, StringifyTypes>
local function writeStringify(buf, value, allowNewlines, tabs, singleLine)
	local valType = type(value)
	if not tabs then
		tabs = 1
	end
	if valType == "string" then
		local str = allowNewlines and value or value:gsub("\r\n", " "):gsub("[\r\n]", " ")
		buf[#buf + 1] = string.format("%q", str)
	elseif valType == "boolean" or valType == "nil" or valType == "number" then
		buf[#buf + 1] = tostring(value)
	elseif valType == "table" then
		local newLine = (singleLine and " " or "\n")
		buf[#buf + 1] = "{" .. newLine
		-- ipairs compatible keys are done first so we can use the array syntax for them
		local arrayKeys = {}
		local indent = singleLine and "" or indentFor(tabs)
		for k, v in ipairs(value) do
			arrayKeys[k] = true
			buf[#buf + 1] = indent
			writeStringify(buf, v, allowNewlines, tabs + 1, singleLine)
			buf[#buf + 1] = "," .. newLine
		end

		local mapKeys = {}
		for key in pairs(value) do
			-- avoid printing array-style items twice
			if not arrayKeys[key] then
				t_insert(mapKeys, key)
			end
		end
		table.sort(mapKeys, strSort)

		for _, k in ipairs(mapKeys) do
			buf[#buf + 1] = indent .. "["
			writeStringify(buf, k, allowNewlines, nil, singleLine)
			buf[#buf + 1] = "] = "
			writeStringify(buf, value[k], allowNewlines, tabs + 1, singleLine)
			buf[#buf + 1] = "," .. newLine
		end
		buf[#buf + 1] = (singleLine and "" or indentFor(tabs - 1)) .. "}"
	else
		error("Disallowed stringify type " .. valType)
	end
end
-- Converts a table to a string which will be valid Lua. The result will ipairs to utilise the array
-- syntax when applicable, and will sort other keys.
--- @param value StringifyTypes
--- @param allowNewlines boolean? Determines if multi-line strings should be allowed. By default newlines are converted to spaces.
--- @param tabs number? Amount of tabs to prepend on table lines. Defaults to 1.
--- @return string
function M.stringify(value, allowNewlines, tabs)
	local buf = {}
	writeStringify(buf, value, allowNewlines, tabs)
	return table.concat(buf)
end

-- Converts a table to a string which will be valid Lua. The result will ipairs to utilise the array
-- syntax when applicable, and will sort other keys. This is similar to stringify(), but does not produce a multi line string.
--- @param value StringifyTypes
--- @return string
function M.stringifyInline(value)
	local buf = {}
	writeStringify(buf, value, false, nil, true)
	return table.concat(buf)
end

---@param fileName string
---@param table StringifyTypes
---@param description? string A string which will be passed to string.format and which should describe what this file contains. Multi-line strings are supported.
---@param allowMultiLine? boolean Whether multi-line strings should be allowed. If not, they are converted to spaces.
---@return boolean success
function M.saveTableToFile(fileName, table, description, allowMultiLine)
	local f, openErr = io.open(fileName, "w")
	if not f then
		error(string.format("Could not open %s for writing table: %s", fileName, openErr))
	end
	local descFormatted = ""
	if description then
		-- add newline at the end
		if description:sub(-1) ~= "\n" then
			description = description .. "\n"
		end
		-- prepend lines with comments
		for line in description:gmatch("(.-)\n") do
			descFormatted = descFormatted .. "-- " .. line .. "\n"
		end
	end
	local template = [[-- This file is automatically generated, do not edit!
-- Game data (c) Grinding Gear Games

%s
-- spell-checker: disable
return %s
]]

	local contents = string.format(template, descFormatted, M.stringify(table, allowMultiLine, 1))

	local _, writeErr = f:write(contents)

	if writeErr then
		error(string.format("Failed to write to %s: %s", fileName, writeErr))
	end

	return f:close() or false
end

return M
