-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Rustic Sash"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(12-24)% increased Global Physical Damage",
	implicitModTypes = { { "physical_damage", "damage", "physical" }, },
	implicitIds = { "IncreasedPhysicalDamagePercentImplicitBelt1", },
	req = { },
}
itemBases["Chain Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "+(9-20) to maximum Energy Shield",
	implicitModTypes = { { "defences", "energy_shield" }, },
	implicitIds = { "IncreasedEnergyShieldImplicitBelt1", },
	req = { },
}
itemBases["Leather Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "+(25-40) to maximum Life",
	implicitModTypes = { { "resource", "life" }, },
	implicitIds = { "IncreasedLifeImplicitBelt1", },
	req = { level = 8, },
}
itemBases["Heavy Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "+(25-35) to Strength",
	implicitModTypes = { { "attribute" }, },
	implicitIds = { "StrengthImplicitBelt1", },
	req = { level = 8, },
}
itemBases["Cloth Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(15-25)% increased Stun and Block Recovery",
	implicitModTypes = { {  }, },
	implicitIds = { "StunRecoveryImplicitBelt1", },
	req = { level = 16, },
}
itemBases["Studded Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(20-30)% increased Stun Duration on Enemies",
	implicitModTypes = { {  }, },
	implicitIds = { "StunDurationImplicitBelt1", },
	req = { level = 16, },
}
itemBases["Micro-Distillery Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, experimental_base = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "Flasks applied to you have 30% increased Effect\nCan't use Flask in Fifth Slot",
	implicitModTypes = { {  }, {  }, },
	implicitIds = { "CannotUseFlaskInFifthSlotImplicitE1_", },
	req = { level = 24, },
}
itemBases["Mechalarm Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, experimental_base = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "Trigger Level 20 Summon Taunting Contraption when you use a Flask",
	implicitModTypes = { {  }, },
	implicitIds = { "SummonTauntingContraptionOnFlaskUseImplicitE1", },
	req = { level = 56, },
}
itemBases["Mechanical Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, experimental_base = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "Has 1 Socket",
	implicitModTypes = { {  }, },
	implicitIds = { "BeltHasOneSocket", },
	req = { level = 56, },
}
itemBases["Vanguard Belt"] = {
	type = "Belt",
	tags = { atlas_base_type = true, belt = true, beltatlas1 = true, default = true, not_for_sale = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "+(260-320) to Armour and Evasion Rating",
	implicitModTypes = { { "defences", "armour", "evasion" }, },
	implicitIds = { "ArmourAndEvasionImplicitBelt1", },
	req = { level = 78, },
}
itemBases["Crystal Belt"] = {
	type = "Belt",
	tags = { atlas_base_type = true, belt = true, beltatlas2 = true, default = true, not_for_sale = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "+(60-80) to maximum Energy Shield",
	implicitModTypes = { { "defences", "energy_shield" }, },
	implicitIds = { "IncreasedEnergyShieldImplicitBelt2", },
	req = { level = 79, },
}
itemBases["Stygian Vise"] = {
	type = "Belt",
	tags = { belt = true, default = true, not_for_sale = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "Has 1 Abyssal Socket",
	implicitModTypes = { {  }, },
	implicitIds = { "AbyssJewelSocketImplicit", },
	req = { },
}
itemBases["Cord Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, not_for_sale = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "Can be Anointed",
	implicitModTypes = { {  }, },
	implicitIds = { "BeltEnchantImplicit", },
	req = { },
}

itemBases["Golden Obi"] = {
	type = "Belt",
	tags = { belt = true, default = true, demigods = true, not_for_sale = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(20-30)% increased Rarity of Items found",
	implicitModTypes = { { "drop" }, },
	implicitIds = { "ItemFoundRarityIncreaseImplicitDemigodsBelt1", },
	req = { },
}
