-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["Plate Vest"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 19, EvasionBase = 27, },
	req = { str = 12, },
}
itemBases["Chestplate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 68, EvasionBase = 89, },
	req = { level = 6, str = 25, },
}
itemBases["Copper Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 176, EvasionBase = 221, },
	req = { level = 17, str = 53, },
}
itemBases["War Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 216, EvasionBase = 248, },
	req = { level = 21, str = 63, },
}
itemBases["Full Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 284, EvasionBase = 319, },
	req = { level = 28, str = 81, },
}
itemBases["Arena Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 324, EvasionBase = 389, },
	req = { level = 32, str = 91, },
}
itemBases["Lordly Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 353, EvasionBase = 417, },
	req = { level = 35, str = 99, },
}
itemBases["Bronze Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 373, EvasionBase = 429, },
	req = { level = 37, str = 104, },
}
itemBases["Battle Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 412, EvasionBase = 474, },
	req = { level = 41, str = 114, },
}
itemBases["Sun Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 451, EvasionBase = 506, },
	req = { level = 45, str = 124, },
}
itemBases["Colosseum Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 491, EvasionBase = 589, },
	req = { level = 49, str = 134, },
}
itemBases["Majestic Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 530, EvasionBase = 625, },
	req = { level = 53, str = 145, },
}
itemBases["Golden Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 559, EvasionBase = 643, },
	req = { level = 56, str = 152, },
}
itemBases["Crusader Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 601, EvasionBase = 691, },
	req = { level = 59, str = 160, },
}
itemBases["Astral Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicit = "+(8-12)% to all Elemental Resistances",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { ArmourBase = 711, EvasionBase = 782, },
	req = { level = 62, str = 180, },
}
itemBases["Gladiator Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 738, EvasionBase = 848, },
	req = { level = 65, str = 177, },
}
itemBases["Glorious Plate"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 776, EvasionBase = 892, },
	req = { level = 68, str = 191, },
}

itemBases["Shabby Jerkin"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 29, MovementPenalty = -41, },
	req = { dex = 14, },
}
itemBases["Strapped Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 98, MovementPenalty = -127, },
	req = { level = 9, dex = 32, },
}
itemBases["Buckskin Tunic"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 176, MovementPenalty = -221, },
	req = { level = 17, dex = 53, },
}
itemBases["Wild Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 255, MovementPenalty = -306, },
	req = { level = 25, dex = 73, },
}
itemBases["Full Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 284, MovementPenalty = -327, },
	req = { level = 28, dex = 81, },
}
itemBases["Sun Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 324, MovementPenalty = -382, },
	req = { level = 32, dex = 91, },
}
itemBases["Thief's Garb"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 353, MovementPenalty = -396, },
	req = { level = 35, dex = 99, },
}
itemBases["Eelskin Tunic"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 373, MovementPenalty = -429, },
	req = { level = 37, dex = 104, },
}
itemBases["Frontier Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 412, MovementPenalty = -495, },
	req = { level = 41, dex = 114, },
}
itemBases["Glorious Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 451, MovementPenalty = -519, },
	req = { level = 45, dex = 124, },
}
itemBases["Coronal Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 491, MovementPenalty = -579, },
	req = { level = 49, dex = 134, },
}
itemBases["Cutthroat's Garb"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 530, MovementPenalty = -594, },
	req = { level = 53, dex = 145, },
}
itemBases["Sharkskin Tunic"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 559, MovementPenalty = -643, },
	req = { level = 56, dex = 152, },
}
itemBases["Destiny Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 601, MovementPenalty = -721, },
	req = { level = 59, dex = 160, },
}
itemBases["Exquisite Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 704, MovementPenalty = -810, },
	req = { level = 62, dex = 170, },
}
itemBases["Zodiac Leather"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 854, MovementPenalty = -982, },
	req = { level = 65, dex = 197, },
}
itemBases["Assassin's Garb"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicit = "3% increased Movement Speed",
	implicitModTypes = { { "speed" }, },
	armour = { EnergyShieldBase = 737, MovementPenalty = -811, },
	req = { level = 68, dex = 183, },
}

itemBases["Simple Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 14, },
	req = { int = 17, },
}
itemBases["Silken Vest"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 30, },
	req = { level = 11, int = 37, },
}
itemBases["Scholar's Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 43, },
	req = { level = 18, int = 55, },
}
itemBases["Silken Garb"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 56, },
	req = { level = 25, int = 73, },
}
itemBases["Mage's Vestment"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 62, },
	req = { level = 28, int = 81, },
}
itemBases["Silk Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 69, },
	req = { level = 32, int = 91, },
}
itemBases["Cabalist Regalia"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 75, },
	req = { level = 35, int = 99, },
}
itemBases["Sage's Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 79, },
	req = { level = 37, int = 104, },
}
itemBases["Silken Wrap"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 86, },
	req = { level = 41, int = 114, },
}
itemBases["Conjurer's Vestment"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 94, },
	req = { level = 45, int = 124, },
}
itemBases["Spidersilk Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 101, },
	req = { level = 49, int = 134, },
}
itemBases["Destroyer Regalia"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 109, },
	req = { level = 53, int = 145, },
}
itemBases["Savant's Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 115, },
	req = { level = 56, int = 152, },
}
itemBases["Necromancer Silks"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 123, },
	req = { level = 59, int = 160, },
}
itemBases["Occultist's Vestment"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicit = "(3-10)% increased Spell Damage",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { WardBase = 137, },
	req = { level = 62, int = 180, },
}
itemBases["Widowsilk Robe"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 157, },
	req = { level = 65, int = 187, },
}
itemBases["Vaal Regalia"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 171, },
	req = { level = 68, int = 194, },
}

itemBases["Scale Vest"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 27, EvasionBase = 38, EnergyShieldBase = 27, MovementPenalty = -38, },
	req = { str = 10, dex = 10, },
}
itemBases["Light Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 48, EvasionBase = 63, EnergyShieldBase = 48, MovementPenalty = -63, },
	req = { level = 8, str = 16, dex = 16, },
}
itemBases["Scale Doublet"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 97, EvasionBase = 121, EnergyShieldBase = 97, MovementPenalty = -121, },
	req = { level = 17, str = 28, dex = 28, },
}
itemBases["Infantry Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 119, EvasionBase = 142, EnergyShieldBase = 119, MovementPenalty = -142, },
	req = { level = 21, str = 34, dex = 34, },
}
itemBases["Full Scale Armour"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 156, EvasionBase = 180, EnergyShieldBase = 156, MovementPenalty = -180, },
	req = { level = 28, str = 43, dex = 43, },
}
itemBases["Soldier's Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 178, EvasionBase = 210, EnergyShieldBase = 178, MovementPenalty = -210, },
	req = { level = 32, str = 48, dex = 48, },
}
itemBases["Field Lamellar"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 194, EvasionBase = 223, EnergyShieldBase = 194, MovementPenalty = -223, },
	req = { level = 35, str = 53, dex = 53, },
}
itemBases["Wyrmscale Doublet"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 210, EvasionBase = 236, EnergyShieldBase = 210, MovementPenalty = -236, },
	req = { level = 38, str = 57, dex = 57, },
}
itemBases["Hussar Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 232, EvasionBase = 278, EnergyShieldBase = 232, MovementPenalty = -278, },
	req = { level = 42, str = 62, dex = 62, },
}
itemBases["Full Wyrmscale"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 254, EvasionBase = 292, EnergyShieldBase = 254, MovementPenalty = -292, },
	req = { level = 46, str = 68, dex = 68, },
}
itemBases["Commander's Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 275, EvasionBase = 325, EnergyShieldBase = 275, MovementPenalty = -325, },
	req = { level = 50, str = 73, dex = 73, },
}
itemBases["Battle Lamellar"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 297, EvasionBase = 341, EnergyShieldBase = 297, MovementPenalty = -341, },
	req = { level = 54, str = 79, dex = 79, },
}
itemBases["Dragonscale Doublet"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 313, EvasionBase = 351, EnergyShieldBase = 313, MovementPenalty = -351, },
	req = { level = 57, str = 83, dex = 83, },
}
itemBases["Desert Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 376, EvasionBase = 451, EnergyShieldBase = 376, MovementPenalty = -451, },
	req = { level = 60, str = 96, dex = 96, },
}
itemBases["Full Dragonscale"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 470, EvasionBase = 541, EnergyShieldBase = 373, MovementPenalty = -429, },
	req = { level = 63, str = 115, dex = 94, },
}
itemBases["General's Brigandine"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 415, EvasionBase = 465, EnergyShieldBase = 415, MovementPenalty = -465, },
	req = { level = 66, str = 103, dex = 103, },
}
itemBases["Triumphant Lamellar"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 380, EvasionBase = 437, EnergyShieldBase = 477, MovementPenalty = -549, },
	req = { level = 69, str = 95, dex = 116, },
}

itemBases["Chainmail Vest"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 27, EvasionBase = 38, WardBase = 9, },
	req = { str = 10, int = 10, },
}
itemBases["Chainmail Tunic"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 48, EvasionBase = 63, WardBase = 13, },
	req = { level = 8, str = 16, int = 16, },
}
itemBases["Ringmail Coat"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 97, EvasionBase = 121, WardBase = 22, },
	req = { level = 17, str = 28, int = 28, },
}
itemBases["Chainmail Doublet"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 119, EvasionBase = 140, WardBase = 27, },
	req = { level = 21, str = 34, int = 34, },
}
itemBases["Full Ringmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 156, EvasionBase = 180, WardBase = 34, },
	req = { level = 28, str = 43, int = 43, },
}
itemBases["Full Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 178, EvasionBase = 199, WardBase = 38, },
	req = { level = 32, str = 48, int = 48, },
}
itemBases["Holy Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 194, EvasionBase = 233, WardBase = 41, },
	req = { level = 35, str = 53, int = 53, },
}
itemBases["Latticed Ringmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 216, EvasionBase = 248, WardBase = 45, },
	req = { level = 39, str = 59, int = 59, },
}
itemBases["Crusader Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 237, EvasionBase = 266, WardBase = 50, },
	req = { level = 43, str = 64, int = 64, },
}
itemBases["Ornate Ringmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 259, EvasionBase = 298, WardBase = 54, },
	req = { level = 47, str = 69, int = 69, },
}
itemBases["Chain Hauberk"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 281, EvasionBase = 314, WardBase = 58, },
	req = { level = 51, str = 75, int = 75, },
}
itemBases["Devout Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 302, EvasionBase = 363, WardBase = 62, },
	req = { level = 55, str = 80, int = 80, },
}
itemBases["Loricated Ringmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 325, EvasionBase = 374, WardBase = 66, },
	req = { level = 58, str = 84, int = 84, },
}
itemBases["Conquest Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 387, EvasionBase = 445, WardBase = 79, },
	req = { level = 61, str = 96, int = 96, },
}
itemBases["Elegant Ringmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 377, EvasionBase = 433, WardBase = 92, },
	req = { level = 64, str = 90, int = 105, },
}
itemBases["Saint's Hauberk"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 443, EvasionBase = 496, WardBase = 76, },
	req = { level = 67, str = 109, int = 94, },
}
itemBases["Saintly Chainmail"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 401, EvasionBase = 461, WardBase = 96, },
	req = { level = 70, str = 99, int = 115, },
}

itemBases["Padded Vest"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 27, MovementPenalty = -38, WardBase = 9, },
	req = { dex = 10, int = 10, },
}
itemBases["Oiled Vest"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 54, MovementPenalty = -70, WardBase = 14, },
	req = { level = 9, dex = 17, int = 17, },
}
itemBases["Padded Jacket"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 102, MovementPenalty = -128, WardBase = 24, },
	req = { level = 18, dex = 30, int = 30, },
}
itemBases["Oiled Coat"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 124, MovementPenalty = -146, WardBase = 28, },
	req = { level = 22, dex = 35, int = 35, },
}
itemBases["Scarlet Raiment"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 156, MovementPenalty = -180, WardBase = 34, },
	req = { level = 28, dex = 43, int = 43, },
}
itemBases["Waxed Garb"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 178, MovementPenalty = -205, WardBase = 38, },
	req = { level = 32, dex = 48, int = 48, },
}
itemBases["Bone Armour"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 194, MovementPenalty = -233, WardBase = 41, },
	req = { level = 35, dex = 53, int = 53, },
}
itemBases["Quilted Jacket"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 221, MovementPenalty = -248, WardBase = 46, },
	req = { level = 40, dex = 60, int = 60, },
}
itemBases["Sleek Coat"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 243, MovementPenalty = -287, WardBase = 51, },
	req = { level = 44, dex = 65, int = 65, },
}
itemBases["Crimson Raiment"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 264, MovementPenalty = -304, WardBase = 55, },
	req = { level = 48, dex = 71, int = 71, },
}
itemBases["Lacquered Garb"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 286, MovementPenalty = -329, WardBase = 59, },
	req = { level = 52, dex = 76, int = 76, },
}
itemBases["Crypt Armour"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 308, MovementPenalty = -369, WardBase = 63, },
	req = { level = 56, dex = 82, int = 82, },
}
itemBases["Sentinel Jacket"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 330, MovementPenalty = -370, WardBase = 67, },
	req = { level = 59, dex = 86, int = 86, },
}
itemBases["Varnished Coat"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 387, MovementPenalty = -434, WardBase = 79, },
	req = { level = 62, dex = 96, int = 96, },
}
itemBases["Blood Raiment"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 436, MovementPenalty = -501, WardBase = 73, },
	req = { level = 65, dex = 107, int = 90, },
}
itemBases["Sadist Garb"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 427, MovementPenalty = -491, WardBase = 93, },
	req = { level = 68, dex = 103, int = 109, },
}
itemBases["Carnal Armour"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicit = "+(20-25) to maximum Mana",
	implicitModTypes = { { "resource", "mana" }, },
	armour = { EnergyShieldBase = 353, MovementPenalty = -388, WardBase = 103, },
	req = { level = 71, dex = 88, int = 122, },
}

itemBases["Sacrificial Garb"] = {
	type = "Body Armour",
	subType = "Armour/Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicit = "+1 to Level of all Vaal Skill Gems",
	implicitModTypes = { { "gem" }, },
	armour = { ArmourBase = 329, EvasionBase = 378, EnergyShieldBase = 329, MovementPenalty = -378, WardBase = 67, },
	req = { level = 72, str = 66, dex = 66, int = 66, },
}
itemBases["Grasping Mail"] = {
	type = "Body Armour",
	subType = "Armour/Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 217, EvasionBase = 250, EnergyShieldBase = 217, MovementPenalty = -250, WardBase = 44, },
	req = { level = 70, str = 60, dex = 60, int = 60, },
}
itemBases["Golden Mantle"] = {
	type = "Body Armour",
	subType = "Armour/Evasion/Energy Shield",
	hidden = true,
	socketLimit = 6,
	tags = { body_armour = true, armour = true, default = true, },
	implicit = "+(15-25)% to all Elemental Resistances",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { ArmourBase = 75, EvasionBase = 86, EnergyShieldBase = 75, MovementPenalty = -86, WardBase = 17, },
	req = { level = 20, str = 8, dex = 8, int = 8, },
}
