name: Accuracy bug report
description: Create a bug report to help us fix incorrect wording in Path of Building for PoE1.
labels: ["bug:accuracy"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue with PoB-**PoE1**.  
        [Issues with PoB-PoE2 go here.](https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/issues)
        Please try to fill in as much of the form below as you're able to. Fields marked with an asterisk (*) are required.
  - type: checkboxes
    id: version
    attributes:
      label: Check version
      options:
        - label: I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)
          required: true
  - type: checkboxes
    id: duplicates
    attributes:
      label: Check for duplicates
      options:
        - label: I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)
          required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you running Path of Building on?
      options: 
        - Windows
        - Linux - Wine
        - Linux - PoB Frontend
        - MacOS
      default: 0
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is the wording in-game?
      description: Please write a clear and concise description of what should happen.
      placeholder: |
        E.g. when I look at the unique [...] in-game it says [...].
        [screenshot].
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What is the wording in Path of Building?
      description: Please write a clear and concise description of what actually happens.
      placeholder: |
        E.g. When I look at the unique [...] in Path of Building it says [...].
        [screenshot].
    validations:
      required: true
  - type: textarea
    id: build_code
    attributes:
      label: PoB for PoE1 build code
      description: Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster.
      placeholder: This can be either a code copied from the "Import/Export Build" tab or a link to a PoB build.
      render: shell
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Screenshots
      description: Always provide screenshots of the problematic wording if possible. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
      placeholder: In this text area, you can attach files/images (copy paste) directly, or link to them if they're hosted elsewhere instead.
    validations:
      required: false
