name: Bug report
description: Create a bug report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.
        Please try to fill in as much of the form below as you're able to. Some of the fields marked with an asterisk (*) are required.
  - type: checkboxes
    id: version
    attributes:
      label: Check version
      options:
        - label: I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)
          required: true
  - type: checkboxes
    id: duplicates
    attributes:
      label: Check for duplicates
      options:
        - label: I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)
          required: true
  - type: textarea
    id: expected
    attributes:
      label: What is the expected behaviour/value?
      description: Please write a clear and concise description of what should happen.
      placeholder: E.g. When I'm clicking on [...], I expect [...].
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What is the actual behaviour/value?
      description: Please write a clear and concise description of what actually happens.
      placeholder: E.g. When I'm hovering over [...], PoB displays [...].
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: How to reproduce the issue
      description: Please provide step-by-step instructions.
      placeholder: |
        E.g.
        1. Select [...] as main skill.
        2. Switch to the items tab.
        3. Remove the main skill group.
        4. [...].
    validations:
      required: false
  - type: textarea
    id: build_code
    attributes:
      label: Character build code
      description: Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster.
      placeholder: This can be either a code copied from the "Import/Export Build" tab or a link to a shared build.
      render: shell
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Screenshots
      description: If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
      placeholder: In this text area, you can attach files directly or link to them if they're hosted elsewhere instead.
    validations:
      required: false
