name: Crash report
description: Create a crash report to help us fix critical issues
labels: [bug, crash]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a crash or severe graphical issue.
        Please try to fill in as much of the form below as you're able to. Some of the fields marked with an asterisk (*) are required.
  - type: checkboxes
    id: version
    attributes:
      label: Check version
      options:
        - label: I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)
          required: true
  - type: checkboxes
    id: duplicates
    attributes:
      label: Check for duplicates
      options:
        - label: I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)
          required: true
  - type: textarea
    id: context
    attributes:
      label: Screenshots of crash/graphical issue, version and options menu
      description: If you received a crash or graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the issue cannot be displayed in a still image.
      placeholder: In this text area, you can attach files/images (copy paste) directly, or link to them if they're hosted elsewhere instead.
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: What are your system specifications and configuration?
      description: Please write a clear and concise description of your system details.
      placeholder: |
        E.g.
        Operating System: Windows 10
        Graphics: Nvidia gtx 1060; Driver xxxx
        File Path / File Permissions: e.g. non-ascii characters.
        Other notable system configuration information: e.g. a certain app might be conflicting with Path of Building.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: How to reproduce the issue
      description: Please provide step-by-step instructions.
      placeholder: |
        E.g.
        1. Select [...] as a main skill.
        2. Switch to the items tab.
        3. Remove the main skill group.
        4. [...].
    validations:
      required: true
  - type: textarea
    id: build_code
    attributes:
      label: Character build code
      description: Provide a build code if the crash/graphical issue is caused by a certain build.
      placeholder: |
        This can be either a code copied from the "Import/Export Build" tab or a link to a shared build. 
        In the case where Path of Building crashes/doesn't work on startup or when you open a build.
        Go to your builds folder (default %userprofile%/Documents/Path of Building/Builds) and copy the problematic build's .xml contents into a pastebin and supply the link.
      render: shell
    validations:
      required: false
