-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Other active skills
-- Skill data (c) Grinding Gear Games
--
local skills, mod, flag, skill = ...

skills["Melee"] = {
	name = "Default Attack",
	hidden = true,
	color = 4,
	description = "Strike your foes down with a powerful blow.",
	skillTypes = { [1] = true, [48] = true, [6] = true, [3] = true, [25] = true, [28] = true, [24] = true, },
	baseFlags = {
		attack = true,
		melee = true,
		projectile = true,
	},
	qualityStats = {
	},
	stats = {
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { 1, 1, },
	},
	baseMods = {
		skill("castTime", 1),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[1] = { 1, },
	},
}
skills["GemDetonateMines"] = {
	name = "Detonate Mines",
	color = 4,
	description = "Detonates all the Remote Mines you have placed.",
	skillTypes = { [2] = true, [17] = true, [18] = true, [36] = true, },
	baseFlags = {
		spell = true,
	},
	qualityStats = {
		{ "base_cast_speed_+%", 5 },
	},
	stats = {
		"base_deal_no_damage",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { nil, },
		[2] = { nil, },
		[3] = { nil, },
		[4] = { nil, },
		[5] = { nil, },
		[6] = { nil, },
		[7] = { nil, },
		[8] = { nil, },
		[9] = { nil, },
		[10] = { nil, },
	},
	baseMods = {
		skill("castTime", 0.2),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[1] = { 8, },
		[2] = { 8, },
		[3] = { 8, },
		[4] = { 8, },
		[5] = { 8, },
		[6] = { 8, },
		[7] = { 8, },
		[8] = { 8, },
		[9] = { 8, },
		[10] = { 8, },
	},
}
skills["Portal"] = {
	name = "Portal",
	color = 4,
	description = "Creates a portal to the current area's town.",
	skillTypes = { [2] = true, [17] = true, [18] = true, [19] = true, [36] = true, [27] = true, },
	baseFlags = {
		spell = true,
	},
	qualityStats = {
		{ "base_cast_speed_+%", 3 },
	},
	stats = {
		"base_deal_no_damage",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { nil, },
		[2] = { nil, },
		[3] = { nil, },
		[4] = { nil, },
		[5] = { nil, },
		[6] = { nil, },
		[7] = { nil, },
		[8] = { nil, },
		[9] = { nil, },
		[10] = { nil, },
	},
	baseMods = {
		skill("castTime", 2.5),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[1] = { 10, },
		[2] = { 10, },
		[3] = { 10, },
		[4] = { 10, },
		[5] = { 10, },
		[6] = { 10, },
		[7] = { 10, },
		[8] = { 10, },
		[9] = { 10, },
		[10] = { 10, },
	},
}
skills["VaalBreach"] = {
	name = "Vaal Breach",
	color = 4,
	description = "Creates a breach, making you vulnerable to its powerful inhabitants.",
	skillTypes = { [2] = true, [17] = true, [18] = true, [19] = true, [27] = true, [43] = true, },
	baseFlags = {
		spell = true,
	},
	qualityStats = {
		{ "base_cast_speed_+%", 3 },
	},
	stats = {
		"base_deal_no_damage",
		"display_vaal_breach_no_drops_xp",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { nil, nil, },
		[2] = { nil, nil, },
		[3] = { nil, nil, },
		[4] = { nil, nil, },
		[5] = { nil, nil, },
		[6] = { nil, nil, },
		[7] = { nil, nil, },
		[8] = { nil, nil, },
		[9] = { nil, nil, },
		[10] = { nil, nil, },
	},
	baseMods = {
		skill("castTime", 2.5),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[1] = { 10, },
		[2] = { 10, },
		[3] = { 10, },
		[4] = { 10, },
		[5] = { 10, },
		[6] = { 10, },
		[7] = { 10, },
		[8] = { 10, },
		[9] = { 10, },
		[10] = { 10, },
	},
}
skills["SupportUniqueMjolnerLightningSpellsCastOnHit"] = {
	name = "Mjolner",
	hidden = true,
	color = 4,
	support = true,
	requireSkillTypes = { 45, },
	addSkillTypes = { 42, },
	excludeSkillTypes = { 37, 41, 30, 44, 61, },
	fromItem = true,
	statMap = {
		["triggered_spell_spell_damage_+%"] = {
			mod("Damage", "INC", nil, ModFlag.Spell, 0, { type = "Condition", var = "SkillIsTriggered" }),
		},
	},
	qualityStats = {
	},
	stats = {
		"triggered_spell_spell_damage_+%",
		"unique_mjolner_lightning_spells_triggered",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { 100, nil, },
	},
	baseMods = {
		skill("cooldown", 0.25),
	},
	levelMods = {
		[1] = nil,
	},
	levels = {
		[1] = { 0, },
	},
}
skills["SupportUniqueCosprisMaliceColdSpellsCastOnMeleeCriticalStrike"] = {
	name = "Cospri's Malice",
	hidden = true,
	color = 4,
	support = true,
	requireSkillTypes = { 60, },
	addSkillTypes = { },
	excludeSkillTypes = { 37, 41, 30, 44, 61, },
	fromItem = true,
	qualityStats = {
	},
	stats = {
		"unique_cospris_malice_cold_spells_triggered",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { nil, },
	},
	baseMods = {
		skill("cooldown", 0.25),
	},
	levelMods = {
		[1] = nil,
	},
	levels = {
		[1] = { 1, },
	},
}
skills["RepeatingShockwave"] = {
	name = "Abberath's Fury",
	hidden = true,
	color = 4,
	description = "While you run, this skill creates a small explosion with each step, dealing fire damage in an area around you.",
	skillTypes = { [11] = true, [36] = true, [42] = true, [2] = true, [10] = true, [61] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"base_chance_to_ignite_%",
		"cast_on_gain_skill",
		"cannot_knockback",
		"spell_uncastable_if_triggerable",
		"is_area_damage",
		"skill_can_add_multiple_charges_per_action",
	},
	statInterpolation = { },
	statLevels = {
		[7] = { 50, 75, 10, nil, nil, nil, nil, nil, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("CritChance", 5),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[7] = { 1, },
	},
}
skills["TriggeredBoneNova"] = {
	name = "Bone Nova",
	hidden = true,
	color = 4,
	description = "A spiral of bones erupts around you, dealing physical damage.",
	skillTypes = { [1] = true, [48] = true, [3] = true, [10] = true, [57] = true, [47] = true, [61] = true, },
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	qualityStats = {
	},
	stats = {
		"number_of_additional_projectiles",
		"attack_trigger_on_killing_bleeding_enemy_%",
		"monster_projectile_variation",
		"projectiles_nova",
		"spell_uncastable_if_triggerable",
		"base_is_projectile",
		"cannot_cause_bleeding",
	},
	statInterpolation = { },
	statLevels = {
		[20] = { 8, 100, 15, nil, nil, nil, nil, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("cooldown", 0.5),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[20] = { 1, },
	},
}
skills["TriggeredConsecrate"] = {
	name = "Consecrate",
	hidden = true,
	color = 4,
	description = "Creates an area of Consecrated Ground, providing life regeneration for you and allies who stand in it.",
	skillTypes = { [2] = true, [12] = true, [36] = true, [11] = true, [42] = true, [61] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		duration = true,
		area = true,
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"life_regeneration_rate_per_minute_%",
		"cast_on_crit_%",
		"spell_uncastable_if_triggerable",
	},
	statInterpolation = { },
	statLevels = {
		[10] = { 5000, 240, 100, nil, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("cooldown", 5),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[10] = { 1, },
	},
}
skills["TriggeredSummonLesserShrine"] = {
	name = "Create Lesser Shrine",
	hidden = true,
	color = 4,
	description = "Creates a Lesser Shrine, which will grant a bonus when touched. The Lesser Shrine will disappear after a short duration, or when used. This skill starts on cooldown.",
	skillTypes = { [2] = true, [36] = true, [42] = true, [61] = true, [12] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		duration = true,
	},
	qualityStats = {
	},
	stats = {
		"chance_to_cast_on_kill_%",
		"base_skill_effect_duration",
		"spell_uncastable_if_triggerable",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { 100, 10000, nil, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("cooldown", 20),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[1] = { 1, },
	},
}
skills["Envy"] = {
	name = "Envy",
	hidden = true,
	color = 3,
	description = "Casts an aura that adds chaos damage to the attacks and spells of you and your allies.",
	skillTypes = { [2] = true, [11] = true, [5] = true, [15] = true, [27] = true, [16] = true, [18] = true, [44] = true, [50] = true, },
	fromItem = true,
	statMap = {
		["attack_minimum_added_chaos_damage"] = {
			mod("ChaosMin", "BASE", nil, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["attack_maximum_added_chaos_damage"] = {
			mod("ChaosMax", "BASE", nil, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["spell_minimum_added_chaos_damage"] = {
			mod("ChaosMin", "BASE", nil, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["spell_maximum_added_chaos_damage"] = {
			mod("ChaosMax", "BASE", nil, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }),
		},
	},
	baseFlags = {
		spell = true,
		aura = true,
		area = true,
		chaos = true,
	},
	qualityStats = {
	},
	stats = {
		"attack_minimum_added_chaos_damage",
		"attack_maximum_added_chaos_damage",
		"base_skill_area_of_effect_+%",
		"spell_minimum_added_chaos_damage",
		"spell_maximum_added_chaos_damage",
		"base_deal_no_damage",
	},
	statInterpolation = { },
	statLevels = {
		[15] = { 58, 81, 0, 52, 69, nil, },
	},
	baseMods = {
		skill("castTime", 1.2),
		skill("manaCost", 50),
		skill("cooldown", 1.2),
		skill("radius", 36),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[15] = { 60, },
	},
}
skills["FireBurstOnHit"] = {
	name = "Fire Burst",
	hidden = true,
	color = 4,
	description = "A burst of flame errupts from the location of a hit, dealing fire damage.",
	skillTypes = { [2] = true, [11] = true, [10] = true, [33] = true, [36] = true, [42] = true, [61] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"cast_on_hit_%",
		"is_area_damage",
		"spell_uncastable_if_triggerable",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { 7, 11, 10, nil, nil, },
		[2] = { 8, 12, 10, nil, nil, },
		[3] = { 10, 16, 10, nil, nil, },
		[4] = { 14, 21, 10, nil, nil, },
		[5] = { 20, 30, 10, nil, nil, },
		[6] = { 30, 46, 10, nil, nil, },
		[7] = { 41, 61, 10, nil, nil, },
		[8] = { 54, 80, 10, nil, nil, },
		[9] = { 70, 104, 10, nil, nil, },
		[10] = { 89, 134, 10, nil, nil, },
		[11] = { 114, 170, 10, nil, nil, },
		[12] = { 143, 215, 10, nil, nil, },
		[13] = { 180, 270, 10, nil, nil, },
		[14] = { 224, 336, 10, nil, nil, },
		[15] = { 278, 418, 10, nil, nil, },
		[16] = { 344, 516, 10, nil, nil, },
		[17] = { 424, 636, 10, nil, nil, },
		[18] = { 520, 780, 10, nil, nil, },
		[19] = { 605, 908, 10, nil, nil, },
		[20] = { 703, 1055, 10, nil, nil, },
		[21] = { 777, 1165, 10, nil, nil, },
		[22] = { 858, 1286, 10, nil, nil, },
		[23] = { 946, 1419, 10, nil, nil, },
		[24] = { 1043, 1564, 10, nil, nil, },
		[25] = { 1149, 1724, 10, nil, nil, },
		[26] = { 1266, 1899, 10, nil, nil, },
		[27] = { 1394, 2091, 10, nil, nil, },
		[28] = { 1534, 2301, 10, nil, nil, },
		[29] = { 1687, 2530, 10, nil, nil, },
		[30] = { 1855, 2782, 10, nil, nil, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("damageEffectiveness", 0.5),
		skill("CritChance", 5),
		skill("cooldown", 0.5),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[1] = { 1, },
		[2] = { 2, },
		[3] = { 4, },
		[4] = { 7, },
		[5] = { 11, },
		[6] = { 16, },
		[7] = { 20, },
		[8] = { 24, },
		[9] = { 28, },
		[10] = { 32, },
		[11] = { 36, },
		[12] = { 40, },
		[13] = { 44, },
		[14] = { 48, },
		[15] = { 52, },
		[16] = { 56, },
		[17] = { 60, },
		[18] = { 64, },
		[19] = { 67, },
		[20] = { 70, },
		[21] = { 72, },
		[22] = { 74, },
		[23] = { 76, },
		[24] = { 78, },
		[25] = { 80, },
		[26] = { 82, },
		[27] = { 84, },
		[28] = { 86, },
		[29] = { 88, },
		[30] = { 90, },
	},
}
skills["VaalAuraElementalDamageHealing"] = {
	name = "Gluttony of Elements",
	hidden = true,
	color = 4,
	description = "Casts an aura that causes taking elemental damage to heal you and nearby allies instead.",
	skillTypes = { [2] = true, [5] = true, [11] = true, [12] = true, [18] = true, [43] = true, [44] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		aura = true,
		area = true,
		duration = true,
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"base_elemental_damage_heals",
	},
	statInterpolation = { },
	statLevels = {
		[20] = { 6000, nil, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("radius", 36),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[20] = { 1, },
	},
}
skills["IcestormUniqueStaff12"] = {
	name = "Icestorm",
	hidden = true,
	color = 3,
	description = "Icy bolts rain down over the targeted area. They explode when landing, dealing damage to nearby enemies and chilling them, as well as causing patches of chilled ground. Skill damage is based on Intelligence.",
	skillTypes = { [2] = true, [10] = true, [11] = true, [12] = true, [17] = true, [18] = true, [19] = true, [26] = true, [36] = true, [34] = true, [60] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage_+_per_10_intelligence",
		"spell_maximum_base_cold_damage_+_per_10_intelligence",
		"base_skill_effect_duration",
		"fire_storm_fireball_delay_ms",
		"skill_override_pvp_scaling_time_ms",
		"firestorm_drop_ground_ice_duration_ms",
		"skill_art_variation",
		"skill_effect_duration_per_100_int",
		"base_skill_show_average_damage_instead_of_dps",
		"is_area_damage",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { 1, 3, 1500, 100, 450, 500, 4, 150, nil, nil, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("manaCost", 22),
		skill("damageEffectiveness", 0.3),
		skill("CritChance", 5),
		skill("duration", 0.15, { type = "PerStat", stat = "Int", div = 100, base = 1.5 }),
		skill("radius", 25),
		skill("radiusSecondary", 10),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[1] = { 1, },
	},
}
skills["MerveilWarp"] = {
	name = "Illusory Warp",
	hidden = true,
	color = 4,
	description = "Teleport to a target destination. Chilled ground is spread in an area around both where the caster was and where they teleported to.",
	skillTypes = { [2] = true, [38] = true, [12] = true, [34] = true, [11] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
	},
	statInterpolation = { },
	statLevels = {
		[20] = { 1500, },
	},
	baseMods = {
		skill("castTime", 0.6),
		skill("manaCost", 20),
		skill("cooldown", 3),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[20] = { 1, },
	},
}
skills["LightningSpell"] = {
	name = "Lightning Bolt",
	hidden = true,
	color = 3,
	description = "A bolt of lightning strikes an area, dealing lightning damage.",
	skillTypes = { [2] = true, [42] = true, [35] = true, [11] = true, [10] = true, [45] = true, [61] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"cast_on_crit_%",
		"is_area_damage",
		"spell_uncastable_if_triggerable",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { 10, 29, 100, nil, nil, },
		[2] = { 11, 33, 100, nil, nil, },
		[3] = { 14, 41, 100, nil, nil, },
		[4] = { 18, 54, 100, nil, nil, },
		[5] = { 25, 75, 100, nil, nil, },
		[6] = { 36, 109, 100, nil, nil, },
		[7] = { 47, 141, 100, nil, nil, },
		[8] = { 60, 180, 100, nil, nil, },
		[9] = { 76, 227, 100, nil, nil, },
		[10] = { 94, 282, 100, nil, nil, },
		[11] = { 116, 348, 100, nil, nil, },
		[12] = { 142, 426, 100, nil, nil, },
		[13] = { 173, 518, 100, nil, nil, },
		[14] = { 209, 626, 100, nil, nil, },
		[15] = { 251, 754, 100, nil, nil, },
		[16] = { 301, 903, 100, nil, nil, },
		[17] = { 359, 1078, 100, nil, nil, },
		[18] = { 428, 1283, 100, nil, nil, },
		[19] = { 486, 1459, 100, nil, nil, },
		[20] = { 552, 1657, 100, nil, nil, },
		[21] = { 601, 1802, 100, nil, nil, },
		[22] = { 653, 1959, 100, nil, nil, },
		[23] = { 709, 2127, 100, nil, nil, },
		[24] = { 770, 2310, 100, nil, nil, },
		[25] = { 835, 2506, 100, nil, nil, },
		[26] = { 906, 2718, 100, nil, nil, },
		[27] = { 982, 2946, 100, nil, nil, },
		[28] = { 1064, 3192, 100, nil, nil, },
		[29] = { 1153, 3458, 100, nil, nil, },
		[30] = { 1248, 3743, 100, nil, nil, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("CritChance", 6),
		skill("cooldown", 0.5),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[1] = { 1, },
		[2] = { 2, },
		[3] = { 4, },
		[4] = { 7, },
		[5] = { 11, },
		[6] = { 16, },
		[7] = { 20, },
		[8] = { 24, },
		[9] = { 28, },
		[10] = { 32, },
		[11] = { 36, },
		[12] = { 40, },
		[13] = { 44, },
		[14] = { 48, },
		[15] = { 52, },
		[16] = { 56, },
		[17] = { 60, },
		[18] = { 64, },
		[19] = { 67, },
		[20] = { 70, },
		[21] = { 72, },
		[22] = { 74, },
		[23] = { 76, },
		[24] = { 78, },
		[25] = { 80, },
		[26] = { 82, },
		[27] = { 84, },
		[28] = { 86, },
		[29] = { 88, },
		[30] = { 90, },
	},
}
skills["UniqueAnimateWeapon"] = {
	name = "Manifest Dancing Dervish",
	hidden = true,
	color = 4,
	description = "Releases Dancing Dervish to fight by your side. While Dancing Dervish is manifested, you have Onslaught and cannot use Weapons.",
	skillTypes = { [2] = true, [9] = true, [21] = true, [36] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [11] = true, [38] = true, [28] = true, },
	fromItem = true,
	minionList = {
		"UniqueAnimatedWeapon",
	},
	minionUses = {
		["Weapon 1"] = true,
	},
	statMap = {
		["attack_damage_+%"] = {
			mod("MinionModifier", "LIST", { mod = mod("Damage", "INC", nil, ModFlag.Attack) }),
		},
		["attack_speed_+%"] = {
			mod("MinionModifier", "LIST", { mod = mod("Speed", "INC", nil, ModFlag.Attack) }),
		},
	},
	baseFlags = {
		spell = true,
		minion = true,
	},
	qualityStats = {
	},
	stats = {
		"disable_weapons",
		"attack_speed_+%",
		"attack_damage_+%",
		"chance_to_cast_on_rampage_tier_%",
		"minion_movement_speed_+%",
	},
	statInterpolation = { },
	statLevels = {
		[15] = { 1, 25, 110, 100, 30, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("cooldown", 0.5),
		mod("DisableWeapons", "FLAG", true, 0, 0, { type = "GlobalEffect", effectType = "Buff" }),
		mod("Condition:Onslaught", "FLAG", true, 0, 0, { type = "GlobalEffect", effectType = "Buff" }),
		skill("minionLevel", 59),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[15] = { 1, },
	},
}
skills["TriggeredMoltenStrike"] = {
	name = "Molten Burst",
	hidden = true,
	color = 1,
	description = "Launch molten projectiles from the point of impact, causing AoE attack damage to enemies where they land.",
	skillTypes = { [3] = true, [1] = true, [11] = true, [33] = true, [57] = true, [47] = true, [48] = true, },
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
		area = true,
	},
	qualityStats = {
	},
	stats = {
		"number_of_additional_projectiles",
		"attack_trigger_on_melee_hit_%",
		"show_number_of_projectiles",
		"base_is_projectile",
		"is_area_damage",
		"base_skill_show_average_damage_instead_of_dps",
	},
	statInterpolation = { },
	statLevels = {
		[16] = { 2, 20, nil, nil, nil, nil, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("cooldown", 0.15),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[16] = { 1, },
	},
}
skills["TriggeredSummonSpider"] = {
	name = "Raise Spiders",
	hidden = true,
	color = 3,
	description = "Raise two spectral spiders from each nearby corpse that will leap towards and attack your enemies. Enemies will not engage the spiders directly.",
	skillTypes = { [2] = true, [9] = true, [36] = true, [49] = true, [42] = true, [61] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [28] = true, },
	fromItem = true,
	minionList = {
		"SpiderMinion",
	},
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	qualityStats = {
	},
	stats = {
		"chance_to_cast_on_kill_%_target_self",
		"base_skill_effect_duration",
		"number_of_spider_minions_allowed",
		"spell_uncastable_if_triggerable",
		"take_no_actions_while_parent_dead",
		"minion_dies_when_parent_dies",
		"display_skill_minions_level_is_corpse_level",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { 20, 8000, 20, nil, nil, nil, nil, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("cooldown", 2),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[1] = { 1, },
	},
}
skills["TriggeredShockedGround"] = {
	name = "Shock Ground",
	hidden = true,
	color = 4,
	description = "Creates a patch of Shocked Ground in a radius around you.",
	skillTypes = { [2] = true, [11] = true, [36] = true, [12] = true, [42] = true, [45] = true, [61] = true, [35] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	qualityStats = {
	},
	stats = {
		"cast_when_hit_%",
		"skill_art_variation",
		"base_skill_effect_duration",
		"spell_uncastable_if_triggerable",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { 100, 7, 5000, nil, },
	},
	baseMods = {
		skill("castTime", 1),
		skill("cooldown", 5),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[1] = { 1, },
	},
}
skills["SummonEssenceSpirits"] = {
	name = "Spectral Spirits",
	hidden = true,
	color = 3,
	description = "Summons three invulnerable spectral skulls that rush at nearby enemies and attack them rapidly. Enemies will not engage these spirits, and can pass through them.",
	skillTypes = { [2] = true, [9] = true, [36] = true, [49] = true, [42] = true, [61] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [28] = true, },
	fromItem = true,
	minionList = {
		"SummonedEssenceSpirit",
	},
	baseFlags = {
		spell = true,
		minion = true,
	},
	qualityStats = {
	},
	stats = {
		"active_skill_minion_added_damage_+%_final",
		"number_of_monsters_to_summon",
		"cast_on_gain_skill",
		"spell_uncastable_if_triggerable",
		"take_no_actions_while_parent_dead",
		"minion_dies_when_parent_dies",
	},
	statInterpolation = { },
	statLevels = {
		[1] = { -15, 3, nil, nil, nil, nil, },
		[2] = { -15, 3, nil, nil, nil, nil, },
		[3] = { -15, 3, nil, nil, nil, nil, },
		[4] = { -15, 3, nil, nil, nil, nil, },
		[5] = { -15, 3, nil, nil, nil, nil, },
		[6] = { -15, 3, nil, nil, nil, nil, },
		[7] = { -15, 3, nil, nil, nil, nil, },
		[8] = { -15, 3, nil, nil, nil, nil, },
		[9] = { -15, 3, nil, nil, nil, nil, },
		[10] = { -15, 3, nil, nil, nil, nil, },
		[11] = { -15, 3, nil, nil, nil, nil, },
		[12] = { -15, 3, nil, nil, nil, nil, },
		[13] = { -15, 3, nil, nil, nil, nil, },
		[14] = { -15, 3, nil, nil, nil, nil, },
		[15] = { -15, 3, nil, nil, nil, nil, },
		[16] = { -15, 3, nil, nil, nil, nil, },
		[17] = { -15, 3, nil, nil, nil, nil, },
		[18] = { -15, 3, nil, nil, nil, nil, },
		[19] = { -15, 3, nil, nil, nil, nil, },
		[20] = { -15, 3, nil, nil, nil, nil, },
		[21] = { -15, 3, nil, nil, nil, nil, },
		[22] = { -15, 3, nil, nil, nil, nil, },
		[23] = { -15, 3, nil, nil, nil, nil, },
		[24] = { -15, 3, nil, nil, nil, nil, },
		[25] = { -15, 3, nil, nil, nil, nil, },
		[26] = { -15, 3, nil, nil, nil, nil, },
		[27] = { -15, 3, nil, nil, nil, nil, },
		[28] = { -15, 3, nil, nil, nil, nil, },
		[29] = { -15, 3, nil, nil, nil, nil, },
		[30] = { -15, 3, nil, nil, nil, nil, },
	},
	baseMods = {
		skill("castTime", 1),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[1] = { 1, },
		[2] = { 2, },
		[3] = { 4, },
		[4] = { 7, },
		[5] = { 11, },
		[6] = { 16, },
		[7] = { 20, },
		[8] = { 24, },
		[9] = { 28, },
		[10] = { 32, },
		[11] = { 36, },
		[12] = { 40, },
		[13] = { 44, },
		[14] = { 48, },
		[15] = { 52, },
		[16] = { 56, },
		[17] = { 60, },
		[18] = { 64, },
		[19] = { 67, },
		[20] = { 70, },
		[21] = { 72, },
		[22] = { 74, },
		[23] = { 76, },
		[24] = { 78, },
		[25] = { 80, },
		[26] = { 82, },
		[27] = { 84, },
		[28] = { 86, },
		[29] = { 88, },
		[30] = { 90, },
	},
}
skills["SummonRigwaldsPack"] = {
	name = "Summon Spectral Wolf",
	hidden = true,
	color = 4,
	description = "Summons a spectral wolf companion that attacks near by enemies and dies after a duration.",
	skillTypes = { [2] = true, [9] = true, [12] = true, [21] = true, [17] = true, [18] = true, [19] = true, [26] = true, [36] = true, [49] = true, [42] = true, [61] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [28] = true, },
	fromItem = true,
	minionList = {
		"SummonedSpectralWolf",
	},
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"number_of_wolves_allowed",
		"chance_to_cast_on_kill_%_target_self",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"spell_uncastable_if_triggerable",
	},
	statInterpolation = { },
	statLevels = {
		[18] = { 30000, 20, 10, 8, 65, nil, },
	},
	baseMods = {
		skill("castTime", 1),
	},
	levelMods = {
		[1] = skill("levelRequirement", nil),
	},
	levels = {
		[18] = { 66, },
	},
}