-- Path of Building
--
-- Active Dexterity skills
-- Skill gem data (c) Grinding Gear Games
--
local gems = ...

gems["Animate Weapon"] = {
	unsupported = true,
}
gems["Arctic Armor"] = {
	unsupported = true,
}
gems["Barrage"] = {
	attack = true,
	bow = true,
	projectile = true,
	base = {
	},
	quality = {
		projectile_damageInc = 0.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 7, attack_damageMore = 0.5, },
		[2] = { skill_manaCostBase = 7, attack_damageMore = 0.506, },
		[3] = { skill_manaCostBase = 7, attack_damageMore = 0.512, },
		[4] = { skill_manaCostBase = 8, attack_damageMore = 0.518, },
		[5] = { skill_manaCostBase = 8, attack_damageMore = 0.524, },
		[6] = { skill_manaCostBase = 8, attack_damageMore = 0.53, },
		[7] = { skill_manaCostBase = 8, attack_damageMore = 0.536, },
		[8] = { skill_manaCostBase = 8, attack_damageMore = 0.542, },
		[9] = { skill_manaCostBase = 9, attack_damageMore = 0.548, },
		[10] = { skill_manaCostBase = 9, attack_damageMore = 0.554, },
		[11] = { skill_manaCostBase = 9, attack_damageMore = 0.56, },
		[12] = { skill_manaCostBase = 9, attack_damageMore = 0.566, },
		[13] = { skill_manaCostBase = 9, attack_damageMore = 0.572, },
		[14] = { skill_manaCostBase = 10, attack_damageMore = 0.578, },
		[15] = { skill_manaCostBase = 10, attack_damageMore = 0.584, },
		[16] = { skill_manaCostBase = 10, attack_damageMore = 0.59, },
		[17] = { skill_manaCostBase = 10, attack_damageMore = 0.596, },
		[18] = { skill_manaCostBase = 10, attack_damageMore = 0.602, },
		[19] = { skill_manaCostBase = 11, attack_damageMore = 0.608, },
		[20] = { skill_manaCostBase = 11, attack_damageMore = 0.614, },
		[21] = { skill_manaCostBase = 11, attack_damageMore = 0.62, },
		[22] = { skill_manaCostBase = 11, attack_damageMore = 0.626, },
		[23] = { skill_manaCostBase = 11, attack_damageMore = 0.632, },
		[24] = { skill_manaCostBase = 11, attack_damageMore = 0.638, },
		[25] = { skill_manaCostBase = 11, attack_damageMore = 0.644, },
		[26] = { skill_manaCostBase = 12, attack_damageMore = 0.65, },
		[27] = { skill_manaCostBase = 12, attack_damageMore = 0.656, },
		[28] = { skill_manaCostBase = 12, attack_damageMore = 0.662, },
		[29] = { skill_manaCostBase = 12, attack_damageMore = 0.668, },
		[30] = { skill_manaCostBase = 12, attack_damageMore = 0.674, },
	}
}
gems["Bear Trap"] = {
	cast = true,
	trap = true,
	showAverage = true,
	base = {
		skill_castTime = 1,
		skill_damageEffectiveness = 2,
		skill_critChanceBase = 5,
	},
	quality = {
		physicalInc = 1,
	},
	levels = {
		[1] = { skill_manaCostBase = 11, skill_physicalMin = 16, skill_physicalMax = 22, },
		[2] = { skill_manaCostBase = 13, skill_physicalMin = 20, skill_physicalMax = 28, },
		[3] = { skill_manaCostBase = 15, skill_physicalMin = 27, skill_physicalMax = 38, },
		[4] = { skill_manaCostBase = 17, skill_physicalMin = 35, skill_physicalMax = 49, },
		[5] = { skill_manaCostBase = 20, skill_physicalMin = 49, skill_physicalMax = 69, },
		[6] = { skill_manaCostBase = 22, skill_physicalMin = 67, skill_physicalMax = 94, },
		[7] = { skill_manaCostBase = 24, skill_physicalMin = 90, skill_physicalMax = 126, },
		[8] = { skill_manaCostBase = 26, skill_physicalMin = 119, skill_physicalMax = 167, },
		[9] = { skill_manaCostBase = 28, skill_physicalMin = 156, skill_physicalMax = 218, },
		[10] = { skill_manaCostBase = 32, skill_physicalMin = 202, skill_physicalMax = 282, },
		[11] = { skill_manaCostBase = 35, skill_physicalMin = 259, skill_physicalMax = 363, },
		[12] = { skill_manaCostBase = 38, skill_physicalMin = 331, skill_physicalMax = 463, },
		[13] = { skill_manaCostBase = 39, skill_physicalMin = 420, skill_physicalMax = 587, },
		[14] = { skill_manaCostBase = 41, skill_physicalMin = 530, skill_physicalMax = 742, },
		[15] = { skill_manaCostBase = 42, skill_physicalMin = 630, skill_physicalMax = 881, },
		[16] = { skill_manaCostBase = 43, skill_physicalMin = 746, skill_physicalMax = 1045, },
		[17] = { skill_manaCostBase = 44, skill_physicalMin = 883, skill_physicalMax = 1236, },
		[18] = { skill_manaCostBase = 45, skill_physicalMin = 1043, skill_physicalMax = 1460, },
		[19] = { skill_manaCostBase = 46, skill_physicalMin = 1230, skill_physicalMax = 1721, },
		[20] = { skill_manaCostBase = 46, skill_physicalMin = 1447, skill_physicalMax = 2026, },
		[21] = { skill_manaCostBase = 47, skill_physicalMin = 1613, skill_physicalMax = 2258, },
		[22] = { skill_manaCostBase = 48, skill_physicalMin = 1795, skill_physicalMax = 2514, },
		[23] = { skill_manaCostBase = 49, skill_physicalMin = 1998, skill_physicalMax = 2797, },
		[24] = { skill_manaCostBase = 50, skill_physicalMin = 2222, skill_physicalMax = 3111, },
		[25] = { skill_manaCostBase = 50, skill_physicalMin = 2470, skill_physicalMax = 3458, },
		[26] = { skill_manaCostBase = 51, skill_physicalMin = 2744, skill_physicalMax = 3842, },
		[27] = { skill_manaCostBase = 52, skill_physicalMin = 3047, skill_physicalMax = 4266, },
		[28] = { skill_manaCostBase = 53, skill_physicalMin = 3382, skill_physicalMax = 4735, },
		[29] = { skill_manaCostBase = 54, skill_physicalMin = 3753, skill_physicalMax = 5254, },
		[30] = { skill_manaCostBase = 54, skill_physicalMin = 4162, skill_physicalMax = 5826, },
	}
}
gems["Blade Vortex"] = {
	spell = true,
	aoe = true,
	duration = true,
	showAverage = true,
	base = {
		skill_castTime = 0.5,
		skill_damageEffectiveness = 0.3,
		skill_critChanceBase = 6,
		skill_durationBase = 5,
	},
	quality = {
		aoeRadiusInc = 0.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 6, skill_physicalMin = 9, skill_physicalMax = 14, },
		[2] = { skill_manaCostBase = 7, skill_physicalMin = 11, skill_physicalMax = 17, },
		[3] = { skill_manaCostBase = 8, skill_physicalMin = 14, skill_physicalMax = 21, },
		[4] = { skill_manaCostBase = 9, skill_physicalMin = 18, skill_physicalMax = 26, },
		[5] = { skill_manaCostBase = 10, skill_physicalMin = 21, skill_physicalMax = 32, },
		[6] = { skill_manaCostBase = 11, skill_physicalMin = 26, skill_physicalMax = 38, },
		[7] = { skill_manaCostBase = 12, skill_physicalMin = 30, skill_physicalMax = 46, },
		[8] = { skill_manaCostBase = 13, skill_physicalMin = 34, skill_physicalMax = 52, },
		[9] = { skill_manaCostBase = 13, skill_physicalMin = 39, skill_physicalMax = 58, },
		[10] = { skill_manaCostBase = 14, skill_physicalMin = 44, skill_physicalMax = 65, },
		[11] = { skill_manaCostBase = 14, skill_physicalMin = 49, skill_physicalMax = 73, },
		[12] = { skill_manaCostBase = 15, skill_physicalMin = 55, skill_physicalMax = 82, },
		[13] = { skill_manaCostBase = 16, skill_physicalMin = 61, skill_physicalMax = 91, },
		[14] = { skill_manaCostBase = 16, skill_physicalMin = 68, skill_physicalMax = 101, },
		[15] = { skill_manaCostBase = 17, skill_physicalMin = 75, skill_physicalMax = 113, },
		[16] = { skill_manaCostBase = 18, skill_physicalMin = 83, skill_physicalMax = 125, },
		[17] = { skill_manaCostBase = 18, skill_physicalMin = 89, skill_physicalMax = 133, },
		[18] = { skill_manaCostBase = 19, skill_physicalMin = 95, skill_physicalMax = 142, },
		[19] = { skill_manaCostBase = 19, skill_physicalMin = 101, skill_physicalMax = 152, },
		[20] = { skill_manaCostBase = 19, skill_physicalMin = 108, skill_physicalMax = 162, },
		[21] = { skill_manaCostBase = 20, skill_physicalMin = 115, skill_physicalMax = 173, },
		[22] = { skill_manaCostBase = 21, skill_physicalMin = 123, skill_physicalMax = 184, },
		[23] = { skill_manaCostBase = 21, skill_physicalMin = 131, skill_physicalMax = 197, },
		[24] = { skill_manaCostBase = 21, skill_physicalMin = 139, skill_physicalMax = 209, },
		[25] = { skill_manaCostBase = 22, skill_physicalMin = 148, skill_physicalMax = 223, },
		[26] = { skill_manaCostBase = 23, skill_physicalMin = 158, skill_physicalMax = 237, },
		[27] = { skill_manaCostBase = 23, skill_physicalMin = 168, skill_physicalMax = 252, },
		[28] = { skill_manaCostBase = 23, skill_physicalMin = 178, skill_physicalMax = 267, },
		[29] = { skill_manaCostBase = 24, skill_physicalMin = 189, skill_physicalMax = 284, },
		[30] = { skill_manaCostBase = 24, skill_physicalMin = 201, skill_physicalMax = 302, },
	}
}
gems["Bladefall"] = {
	spell = true,
	aoe = true,
	base = {
		skill_castTime = 0.8,
		skill_damageEffectiveness = 0.9,
		skill_critChanceBase = 5,
	},
	quality = {
		aoeRadiusInc = 0.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 13, skill_physicalMin = 44, skill_physicalMax = 65, },
		[2] = { skill_manaCostBase = 14, skill_physicalMin = 52, skill_physicalMax = 78, },
		[3] = { skill_manaCostBase = 15, skill_physicalMin = 62, skill_physicalMax = 93, },
		[4] = { skill_manaCostBase = 16, skill_physicalMin = 73, skill_physicalMax = 110, },
		[5] = { skill_manaCostBase = 17, skill_physicalMin = 86, skill_physicalMax = 129, },
		[6] = { skill_manaCostBase = 18, skill_physicalMin = 96, skill_physicalMax = 144, },
		[7] = { skill_manaCostBase = 18, skill_physicalMin = 107, skill_physicalMax = 160, },
		[8] = { skill_manaCostBase = 19, skill_physicalMin = 118, skill_physicalMax = 177, },
		[9] = { skill_manaCostBase = 19, skill_physicalMin = 131, skill_physicalMax = 197, },
		[10] = { skill_manaCostBase = 20, skill_physicalMin = 145, skill_physicalMax = 218, },
		[11] = { skill_manaCostBase = 21, skill_physicalMin = 160, skill_physicalMax = 241, },
		[12] = { skill_manaCostBase = 21, skill_physicalMin = 177, skill_physicalMax = 266, },
		[13] = { skill_manaCostBase = 22, skill_physicalMin = 195, skill_physicalMax = 293, },
		[14] = { skill_manaCostBase = 22, skill_physicalMin = 215, skill_physicalMax = 323, },
		[15] = { skill_manaCostBase = 23, skill_physicalMin = 237, skill_physicalMax = 356, },
		[16] = { skill_manaCostBase = 24, skill_physicalMin = 261, skill_physicalMax = 392, },
		[17] = { skill_manaCostBase = 24, skill_physicalMin = 287, skill_physicalMax = 431, },
		[18] = { skill_manaCostBase = 25, skill_physicalMin = 315, skill_physicalMax = 473, },
		[19] = { skill_manaCostBase = 25, skill_physicalMin = 346, skill_physicalMax = 519, },
		[20] = { skill_manaCostBase = 26, skill_physicalMin = 380, skill_physicalMax = 570, },
		[21] = { skill_manaCostBase = 27, skill_physicalMin = 417, skill_physicalMax = 625, },
		[22] = { skill_manaCostBase = 27, skill_physicalMin = 457, skill_physicalMax = 685, },
		[23] = { skill_manaCostBase = 28, skill_physicalMin = 500, skill_physicalMax = 750, },
		[24] = { skill_manaCostBase = 28, skill_physicalMin = 548, skill_physicalMax = 821, },
		[25] = { skill_manaCostBase = 29, skill_physicalMin = 599, skill_physicalMax = 899, },
		[26] = { skill_manaCostBase = 30, skill_physicalMin = 655, skill_physicalMax = 983, },
		[27] = { skill_manaCostBase = 30, skill_physicalMin = 716, skill_physicalMax = 1074, },
		[28] = { skill_manaCostBase = 31, skill_physicalMin = 782, skill_physicalMax = 1174, },
		[29] = { skill_manaCostBase = 31, skill_physicalMin = 854, skill_physicalMax = 1282, },
		[30] = { skill_manaCostBase = 32, skill_physicalMin = 933, skill_physicalMax = 1399, },
	}
}
gems["Blast Rain"] = {
	attack = true,
	bow = true,
	projectile = true,
	aoe = true,
	fire = true,
	base = {
		physicalConvertTofire = 50,
	},
	quality = {
		aoeRadiusInc = 0.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 8, attack_damageMore = 0.4, },
		[2] = { skill_manaCostBase = 8, attack_damageMore = 0.404, },
		[3] = { skill_manaCostBase = 8, attack_damageMore = 0.408, },
		[4] = { skill_manaCostBase = 8, attack_damageMore = 0.412, },
		[5] = { skill_manaCostBase = 9, attack_damageMore = 0.416, },
		[6] = { skill_manaCostBase = 9, attack_damageMore = 0.42, },
		[7] = { skill_manaCostBase = 9, attack_damageMore = 0.424, },
		[8] = { skill_manaCostBase = 9, attack_damageMore = 0.428, },
		[9] = { skill_manaCostBase = 9, attack_damageMore = 0.432, },
		[10] = { skill_manaCostBase = 9, attack_damageMore = 0.436, },
		[11] = { skill_manaCostBase = 9, attack_damageMore = 0.44, },
		[12] = { skill_manaCostBase = 10, attack_damageMore = 0.444, },
		[13] = { skill_manaCostBase = 10, attack_damageMore = 0.448, },
		[14] = { skill_manaCostBase = 10, attack_damageMore = 0.452, },
		[15] = { skill_manaCostBase = 10, attack_damageMore = 0.456, },
		[16] = { skill_manaCostBase = 10, attack_damageMore = 0.46, },
		[17] = { skill_manaCostBase = 10, attack_damageMore = 0.464, },
		[18] = { skill_manaCostBase = 10, attack_damageMore = 0.468, },
		[19] = { skill_manaCostBase = 10, attack_damageMore = 0.472, },
		[20] = { skill_manaCostBase = 10, attack_damageMore = 0.476, },
		[21] = { skill_manaCostBase = 10, attack_damageMore = 0.48, },
		[22] = { skill_manaCostBase = 10, attack_damageMore = 0.484, },
		[23] = { skill_manaCostBase = 11, attack_damageMore = 0.488, },
		[24] = { skill_manaCostBase = 11, attack_damageMore = 0.492, },
		[25] = { skill_manaCostBase = 11, attack_damageMore = 0.496, },
		[26] = { skill_manaCostBase = 11, attack_damageMore = 0.5, },
		[27] = { skill_manaCostBase = 11, attack_damageMore = 0.504, },
		[28] = { skill_manaCostBase = 12, attack_damageMore = 0.508, },
		[29] = { skill_manaCostBase = 12, attack_damageMore = 0.512, },
		[30] = { skill_manaCostBase = 12, attack_damageMore = 0.516, },
	}
}
gems["Blink Arrow"] = {
	unsupported = true,
}
gems["Blood Rage"] = {
	spell = true,
	duration = true,
	base = {
	},
	quality = {
		buff_attackSpeedInc = 0.25,
	},
	levels = {
		[1] = { skill_manaCostBase = 17, skill_durationBase = 7, buff_attackSpeedInc = 5, },
		[2] = { skill_manaCostBase = 17, skill_durationBase = 7.2, buff_attackSpeedInc = 6, },
		[3] = { skill_manaCostBase = 17, skill_durationBase = 7.4, buff_attackSpeedInc = 6, },
		[4] = { skill_manaCostBase = 18, skill_durationBase = 7.6, buff_attackSpeedInc = 7, },
		[5] = { skill_manaCostBase = 18, skill_durationBase = 7.8, buff_attackSpeedInc = 7, },
		[6] = { skill_manaCostBase = 18, skill_durationBase = 8, buff_attackSpeedInc = 8, },
		[7] = { skill_manaCostBase = 18, skill_durationBase = 8.2, buff_attackSpeedInc = 8, },
		[8] = { skill_manaCostBase = 19, skill_durationBase = 8.4, buff_attackSpeedInc = 9, },
		[9] = { skill_manaCostBase = 19, skill_durationBase = 8.6, buff_attackSpeedInc = 9, },
		[10] = { skill_manaCostBase = 19, skill_durationBase = 8.8, buff_attackSpeedInc = 10, },
		[11] = { skill_manaCostBase = 20, skill_durationBase = 9, buff_attackSpeedInc = 10, },
		[12] = { skill_manaCostBase = 20, skill_durationBase = 9.2, buff_attackSpeedInc = 11, },
		[13] = { skill_manaCostBase = 20, skill_durationBase = 9.4, buff_attackSpeedInc = 11, },
		[14] = { skill_manaCostBase = 20, skill_durationBase = 9.6, buff_attackSpeedInc = 12, },
		[15] = { skill_manaCostBase = 20, skill_durationBase = 9.8, buff_attackSpeedInc = 12, },
		[16] = { skill_manaCostBase = 21, skill_durationBase = 10, buff_attackSpeedInc = 13, },
		[17] = { skill_manaCostBase = 21, skill_durationBase = 10.2, buff_attackSpeedInc = 13, },
		[18] = { skill_manaCostBase = 21, skill_durationBase = 10.4, buff_attackSpeedInc = 14, },
		[19] = { skill_manaCostBase = 21, skill_durationBase = 10.6, buff_attackSpeedInc = 14, },
		[20] = { skill_manaCostBase = 21, skill_durationBase = 10.8, buff_attackSpeedInc = 15, },
		[21] = { skill_manaCostBase = 22, skill_durationBase = 11, buff_attackSpeedInc = 15, },
		[22] = { skill_manaCostBase = 22, skill_durationBase = 11.2, buff_attackSpeedInc = 16, },
		[23] = { skill_manaCostBase = 22, skill_durationBase = 11.4, buff_attackSpeedInc = 16, },
		[24] = { skill_manaCostBase = 22, skill_durationBase = 11.6, buff_attackSpeedInc = 17, },
		[25] = { skill_manaCostBase = 22, skill_durationBase = 11.8, buff_attackSpeedInc = 17, },
		[26] = { skill_manaCostBase = 23, skill_durationBase = 12, buff_attackSpeedInc = 18, },
		[27] = { skill_manaCostBase = 23, skill_durationBase = 12.2, buff_attackSpeedInc = 18, },
		[28] = { skill_manaCostBase = 23, skill_durationBase = 12.4, buff_attackSpeedInc = 19, },
		[29] = { skill_manaCostBase = 23, skill_durationBase = 12.6, buff_attackSpeedInc = 19, },
		[30] = { skill_manaCostBase = 23, skill_durationBase = 12.8, buff_attackSpeedInc = 20, },
	}
}
gems["Burning Arrow"] = {
	attack = true,
	bow = true,
	projectile = true,
	fire = true,
	base = {
		physicalConvertTofire = 50,
		igniteChance = 20,
	},
	quality = {
		ignite_durationInc = 3,
	},
	levels = {
		[1] = { skill_manaCostBase = 5, attack_damageMore = 1.5, degen_fireInc = 10, },
		[2] = { skill_manaCostBase = 5, attack_damageMore = 1.518, degen_fireInc = 11, },
		[3] = { skill_manaCostBase = 5, attack_damageMore = 1.536, degen_fireInc = 12, },
		[4] = { skill_manaCostBase = 5, attack_damageMore = 1.554, degen_fireInc = 13, },
		[5] = { skill_manaCostBase = 5, attack_damageMore = 1.572, degen_fireInc = 14, },
		[6] = { skill_manaCostBase = 6, attack_damageMore = 1.59, degen_fireInc = 15, },
		[7] = { skill_manaCostBase = 6, attack_damageMore = 1.608, degen_fireInc = 16, },
		[8] = { skill_manaCostBase = 6, attack_damageMore = 1.626, degen_fireInc = 17, },
		[9] = { skill_manaCostBase = 6, attack_damageMore = 1.644, degen_fireInc = 18, },
		[10] = { skill_manaCostBase = 6, attack_damageMore = 1.662, degen_fireInc = 19, },
		[11] = { skill_manaCostBase = 7, attack_damageMore = 1.68, degen_fireInc = 20, },
		[12] = { skill_manaCostBase = 7, attack_damageMore = 1.698, degen_fireInc = 21, },
		[13] = { skill_manaCostBase = 7, attack_damageMore = 1.716, degen_fireInc = 22, },
		[14] = { skill_manaCostBase = 7, attack_damageMore = 1.734, degen_fireInc = 23, },
		[15] = { skill_manaCostBase = 7, attack_damageMore = 1.752, degen_fireInc = 24, },
		[16] = { skill_manaCostBase = 8, attack_damageMore = 1.77, degen_fireInc = 25, },
		[17] = { skill_manaCostBase = 8, attack_damageMore = 1.788, degen_fireInc = 26, },
		[18] = { skill_manaCostBase = 8, attack_damageMore = 1.806, degen_fireInc = 27, },
		[19] = { skill_manaCostBase = 8, attack_damageMore = 1.824, degen_fireInc = 28, },
		[20] = { skill_manaCostBase = 8, attack_damageMore = 1.842, degen_fireInc = 29, },
		[21] = { skill_manaCostBase = 9, attack_damageMore = 1.86, degen_fireInc = 30, },
		[22] = { skill_manaCostBase = 9, attack_damageMore = 1.878, degen_fireInc = 31, },
		[23] = { skill_manaCostBase = 9, attack_damageMore = 1.896, degen_fireInc = 32, },
		[24] = { skill_manaCostBase = 9, attack_damageMore = 1.914, degen_fireInc = 33, },
		[25] = { skill_manaCostBase = 9, attack_damageMore = 1.932, degen_fireInc = 34, },
		[26] = { skill_manaCostBase = 10, attack_damageMore = 1.95, degen_fireInc = 35, },
		[27] = { skill_manaCostBase = 10, attack_damageMore = 1.968, degen_fireInc = 36, },
		[28] = { skill_manaCostBase = 10, attack_damageMore = 1.986, degen_fireInc = 37, },
		[29] = { skill_manaCostBase = 10, attack_damageMore = 2.004, degen_fireInc = 38, },
		[30] = { skill_manaCostBase = 10, attack_damageMore = 2.022, degen_fireInc = 39, },
	}
}
gems["Caustic Arrow"] = {
	attack = true,
	bow = true,
	projectile = true,
	aoe = true,
	duration = true,
	chaos = true,
	base = {
	},
	quality = {
		aoeRadiusInc = 0.5,	
	},
	levels = {
		[1] = { skill_manaCostBase = 8, skill_durationBase = 2.8, skill_chaosDotBase = 5.2, physicalGainAschaos = 30, },
		[2] = { skill_manaCostBase = 8, skill_durationBase = 2.9, skill_chaosDotBase = 6.5, physicalGainAschaos = 31, },
		[3] = { skill_manaCostBase = 8, skill_durationBase = 3, skill_chaosDotBase = 8.8, physicalGainAschaos = 32, },
		[4] = { skill_manaCostBase = 9, skill_durationBase = 3.1, skill_chaosDotBase = 11.7, physicalGainAschaos = 33, },
		[5] = { skill_manaCostBase = 9, skill_durationBase = 3.2, skill_chaosDotBase = 16.5, physicalGainAschaos = 34, },
		[6] = { skill_manaCostBase = 9, skill_durationBase = 3.3, skill_chaosDotBase = 22.8, physicalGainAschaos = 35, },
		[7] = { skill_manaCostBase = 10, skill_durationBase = 3.4, skill_chaosDotBase = 30.8, physicalGainAschaos = 36, },
		[8] = { skill_manaCostBase = 10, skill_durationBase = 3.5, skill_chaosDotBase = 41, physicalGainAschaos = 37, },
		[9] = { skill_manaCostBase = 10, skill_durationBase = 3.6, skill_chaosDotBase = 54.1, physicalGainAschaos = 38, },
		[10] = { skill_manaCostBase = 11, skill_durationBase = 3.7, skill_chaosDotBase = 70.7, physicalGainAschaos = 39, },
		[11] = { skill_manaCostBase = 11, skill_durationBase = 3.9, skill_chaosDotBase = 91.7, physicalGainAschaos = 40, },
		[12] = { skill_manaCostBase = 12, skill_durationBase = 4, skill_chaosDotBase = 118.1, physicalGainAschaos = 41, },
		[13] = { skill_manaCostBase = 12, skill_durationBase = 4.1, skill_chaosDotBase = 151.3, physicalGainAschaos = 42, },
		[14] = { skill_manaCostBase = 13, skill_durationBase = 4.2, skill_chaosDotBase = 193, physicalGainAschaos = 43, },
		[15] = { skill_manaCostBase = 13, skill_durationBase = 4.3, skill_chaosDotBase = 230.9, physicalGainAschaos = 44, },
		[16] = { skill_manaCostBase = 14, skill_durationBase = 4.4, skill_chaosDotBase = 275.7, physicalGainAschaos = 45, },
		[17] = { skill_manaCostBase = 14, skill_durationBase = 4.5, skill_chaosDotBase = 328.6, physicalGainAschaos = 46, },
		[18] = { skill_manaCostBase = 15, skill_durationBase = 4.6, skill_chaosDotBase = 390.8, physicalGainAschaos = 47, },
		[19] = { skill_manaCostBase = 15, skill_durationBase = 4.7, skill_chaosDotBase = 464.1, physicalGainAschaos = 48, },
		[20] = { skill_manaCostBase = 16, skill_durationBase = 4.8, skill_chaosDotBase = 550.3, physicalGainAschaos = 49, },
		[21] = { skill_manaCostBase = 16, skill_durationBase = 5, skill_chaosDotBase = 616, physicalGainAschaos = 50, },
		[22] = { skill_manaCostBase = 17, skill_durationBase = 5.1, skill_chaosDotBase = 689.2, physicalGainAschaos = 51, },
		[23] = { skill_manaCostBase = 17, skill_durationBase = 5.2, skill_chaosDotBase = 770.6, physicalGainAschaos = 52, },
		[24] = { skill_manaCostBase = 18, skill_durationBase = 5.3, skill_chaosDotBase = 861.1, physicalGainAschaos = 53, },
		[25] = { skill_manaCostBase = 18, skill_durationBase = 5.4, skill_chaosDotBase = 961.8, physicalGainAschaos = 54, },
		[26] = { skill_manaCostBase = 19, skill_durationBase = 5.5, skill_chaosDotBase = 1073.7, physicalGainAschaos = 55, },
		[27] = { skill_manaCostBase = 19, skill_durationBase = 5.6, skill_chaosDotBase = 1198, physicalGainAschaos = 56, },
		[28] = { skill_manaCostBase = 20, skill_durationBase = 5.7, skill_chaosDotBase = 1336.2, physicalGainAschaos = 57, },
		[29] = { skill_manaCostBase = 20, skill_durationBase = 5.8, skill_chaosDotBase = 1489.6, physicalGainAschaos = 58, },
		[30] = { skill_manaCostBase = 21, skill_durationBase = 5.9, skill_chaosDotBase = 1660, physicalGainAschaos = 59, },
	}
}
gems["Cyclone"] = {
	attack = true,
	melee = true,
	aoe = true,
	movement = true,
	base = {
		skill_manaCostBase = 12,
		attackSpeedMore = 1.5,
	},
	quality = {
		aoeRadiusInc = 0.5,
	},
	levels = {
		[1] = { attack_damageMore = 0.45, },
		[2] = { attack_damageMore = 0.456, },
		[3] = { attack_damageMore = 0.462, },
		[4] = { attack_damageMore = 0.468, },
		[5] = { attack_damageMore = 0.474, },
		[6] = { attack_damageMore = 0.48, },
		[7] = { attack_damageMore = 0.486, },
		[8] = { attack_damageMore = 0.492, },
		[9] = { attack_damageMore = 0.498, },
		[10] = { attack_damageMore = 0.504, },
		[11] = { attack_damageMore = 0.51, },
		[12] = { attack_damageMore = 0.516, },
		[13] = { attack_damageMore = 0.522, },
		[14] = { attack_damageMore = 0.528, },
		[15] = { attack_damageMore = 0.534, },
		[16] = { attack_damageMore = 0.54, },
		[17] = { attack_damageMore = 0.546, },
		[18] = { attack_damageMore = 0.552, },
		[19] = { attack_damageMore = 0.558, },
		[20] = { attack_damageMore = 0.564, },
		[21] = { attack_damageMore = 0.57, },
		[22] = { attack_damageMore = 0.576, },
		[23] = { attack_damageMore = 0.582, },
		[24] = { attack_damageMore = 0.588, },
		[25] = { attack_damageMore = 0.594, },
		[26] = { attack_damageMore = 0.6, },
		[27] = { attack_damageMore = 0.606, },
		[28] = { attack_damageMore = 0.612, },
		[29] = { attack_damageMore = 0.618, },
		[30] = { attack_damageMore = 0.624, },
	}
}
gems["Desecrate"] = {
	spell = true,
	aoe = true,
	duration = true,
	chaos = true,
	base = {
		skill_castTime = 1,
		skill_durationBase = 5,
	},
	quality = {
		castSpeedInc = 1,
	},
	levels = {
		[1] = { skill_manaCostBase = 8, skill_chaosDotBase = 8.2, },
		[2] = { skill_manaCostBase = 8, skill_chaosDotBase = 11.3, },
		[3] = { skill_manaCostBase = 9, skill_chaosDotBase = 15.4, },
		[4] = { skill_manaCostBase = 9, skill_chaosDotBase = 20.6, },
		[5] = { skill_manaCostBase = 10, skill_chaosDotBase = 25.5, },
		[6] = { skill_manaCostBase = 11, skill_chaosDotBase = 31.4, },
		[7] = { skill_manaCostBase = 12, skill_chaosDotBase = 38.5, },
		[8] = { skill_manaCostBase = 12, skill_chaosDotBase = 46.9, },
		[9] = { skill_manaCostBase = 13, skill_chaosDotBase = 57, },
		[10] = { skill_manaCostBase = 14, skill_chaosDotBase = 69, },
		[11] = { skill_manaCostBase = 15, skill_chaosDotBase = 83.4, },
		[12] = { skill_manaCostBase = 16, skill_chaosDotBase = 100.5, },
		[13] = { skill_manaCostBase = 17, skill_chaosDotBase = 120.7, },
		[14] = { skill_manaCostBase = 18, skill_chaosDotBase = 144.8, },
		[15] = { skill_manaCostBase = 18, skill_chaosDotBase = 163.2, },
		[16] = { skill_manaCostBase = 18, skill_chaosDotBase = 183.9, },
		[17] = { skill_manaCostBase = 19, skill_chaosDotBase = 207, },
		[18] = { skill_manaCostBase = 19, skill_chaosDotBase = 232.8, },
		[19] = { skill_manaCostBase = 20, skill_chaosDotBase = 261.7, },
		[20] = { skill_manaCostBase = 20, skill_chaosDotBase = 294, },
		[21] = { skill_manaCostBase = 21, skill_chaosDotBase = 330.1, },
		[22] = { skill_manaCostBase = 22, skill_chaosDotBase = 370.3, },
		[23] = { skill_manaCostBase = 22, skill_chaosDotBase = 415.2, },
		[24] = { skill_manaCostBase = 22, skill_chaosDotBase = 465.3, },
		[25] = { skill_manaCostBase = 23, skill_chaosDotBase = 521.2, },
		[26] = { skill_manaCostBase = 23, skill_chaosDotBase = 583.5, },
		[27] = { skill_manaCostBase = 24, skill_chaosDotBase = 653, },
		[28] = { skill_manaCostBase = 25, skill_chaosDotBase = 730.4, },
		[29] = { skill_manaCostBase = 25, skill_chaosDotBase = 816.6, },
		[30] = { skill_manaCostBase = 26, skill_chaosDotBase = 912.6, },
	}
}
gems["Detonate Dead"] = {
	unsupported = true,
}
gems["Double Strike"] = {
	attack = true,
	melee = true,
	base = {
		skill_manaCostBase = 5,
	},
	quality = {
		attackSpeedInc = 0.5,
	},
	levels = {
		[1] = { attack_damageMore = 0.7, },
		[2] = { attack_damageMore = 0.708, },
		[3] = { attack_damageMore = 0.716, },
		[4] = { attack_damageMore = 0.724, },
		[5] = { attack_damageMore = 0.732, },
		[6] = { attack_damageMore = 0.74, },
		[7] = { attack_damageMore = 0.748, },
		[8] = { attack_damageMore = 0.756, },
		[9] = { attack_damageMore = 0.764, },
		[10] = { attack_damageMore = 0.772, },
		[11] = { attack_damageMore = 0.78, },
		[12] = { attack_damageMore = 0.788, },
		[13] = { attack_damageMore = 0.796, },
		[14] = { attack_damageMore = 0.804, },
		[15] = { attack_damageMore = 0.812, },
		[16] = { attack_damageMore = 0.82, },
		[17] = { attack_damageMore = 0.828, },
		[18] = { attack_damageMore = 0.836, },
		[19] = { attack_damageMore = 0.844, },
		[20] = { attack_damageMore = 0.852, },
		[21] = { attack_damageMore = 0.86, },
		[22] = { attack_damageMore = 0.868, },
		[23] = { attack_damageMore = 0.876, },
		[24] = { attack_damageMore = 0.884, },
		[25] = { attack_damageMore = 0.892, },
		[26] = { attack_damageMore = 0.9, },
		[27] = { attack_damageMore = 0.908, },
		[28] = { attack_damageMore = 0.916, },
		[29] = { attack_damageMore = 0.924, },
		[30] = { attack_damageMore = 0.932, },
	}
}
gems["Dual Strike"] = {
	unsupported = true,
}
gems["Elemental Hit"] = {
	attack = true,
	melee = true,
	bow = true,
	projectile = true,
	lightning = true,
	cold = true,
	fire = true,
	parts = {
		{
			name = "Added fire",
		},
		{
			name = "Added cold",
		},
		{
			name = "Added lightning",
		},
	},
	base = {
		freezeChance = 10,
		shockChance = 10,
		igniteChance = 10,
	},
	quality = {
		elementalInc = 1,
	},
	levels = {
		[1] = { skill_manaCostBase = 6, part1_attack_fireMin = 4, part1_attack_fireMax = 8, part2_attack_coldMin = 3, part2_attack_coldMax = 6, part3_attack_lightningMin = 1, part3_attack_lightningMax = 13, },
		[2] = { skill_manaCostBase = 6, part1_attack_fireMin = 5, part1_attack_fireMax = 9, part2_attack_coldMin = 4, part2_attack_coldMax = 7, part3_attack_lightningMin = 1, part3_attack_lightningMax = 14, },
		[3] = { skill_manaCostBase = 6, part1_attack_fireMin = 6, part1_attack_fireMax = 11, part2_attack_coldMin = 5, part2_attack_coldMax = 9, part3_attack_lightningMin = 1, part3_attack_lightningMax = 17, },
		[4] = { skill_manaCostBase = 7, part1_attack_fireMin = 7, part1_attack_fireMax = 14, part2_attack_coldMin = 6, part2_attack_coldMax = 11, part3_attack_lightningMin = 1, part3_attack_lightningMax = 23, },
		[5] = { skill_manaCostBase = 7, part1_attack_fireMin = 10, part1_attack_fireMax = 19, part2_attack_coldMin = 8, part2_attack_coldMax = 16, part3_attack_lightningMin = 2, part3_attack_lightningMax = 31, },
		[6] = { skill_manaCostBase = 7, part1_attack_fireMin = 14, part1_attack_fireMax = 27, part2_attack_coldMin = 12, part2_attack_coldMax = 22, part3_attack_lightningMin = 2, part3_attack_lightningMax = 44, },
		[7] = { skill_manaCostBase = 8, part1_attack_fireMin = 18, part1_attack_fireMax = 34, part2_attack_coldMin = 15, part2_attack_coldMax = 28, part3_attack_lightningMin = 3, part3_attack_lightningMax = 56, },
		[8] = { skill_manaCostBase = 8, part1_attack_fireMin = 23, part1_attack_fireMax = 43, part2_attack_coldMin = 19, part2_attack_coldMax = 35, part3_attack_lightningMin = 4, part3_attack_lightningMax = 70, },
		[9] = { skill_manaCostBase = 8, part1_attack_fireMin = 28, part1_attack_fireMax = 53, part2_attack_coldMin = 23, part2_attack_coldMax = 43, part3_attack_lightningMin = 5, part3_attack_lightningMax = 87, },
		[10] = { skill_manaCostBase = 9, part1_attack_fireMin = 35, part1_attack_fireMax = 64, part2_attack_coldMin = 28, part2_attack_coldMax = 53, part3_attack_lightningMin = 6, part3_attack_lightningMax = 106, },
		[11] = { skill_manaCostBase = 9, part1_attack_fireMin = 42, part1_attack_fireMax = 78, part2_attack_coldMin = 34, part2_attack_coldMax = 64, part3_attack_lightningMin = 7, part3_attack_lightningMax = 128, },
		[12] = { skill_manaCostBase = 9, part1_attack_fireMin = 50, part1_attack_fireMax = 93, part2_attack_coldMin = 41, part2_attack_coldMax = 76, part3_attack_lightningMin = 8, part3_attack_lightningMax = 153, },
		[13] = { skill_manaCostBase = 10, part1_attack_fireMin = 60, part1_attack_fireMax = 111, part2_attack_coldMin = 49, part2_attack_coldMax = 91, part3_attack_lightningMin = 10, part3_attack_lightningMax = 183, },
		[14] = { skill_manaCostBase = 10, part1_attack_fireMin = 71, part1_attack_fireMax = 132, part2_attack_coldMin = 58, part2_attack_coldMax = 108, part3_attack_lightningMin = 11, part3_attack_lightningMax = 217, },
		[15] = { skill_manaCostBase = 10, part1_attack_fireMin = 84, part1_attack_fireMax = 156, part2_attack_coldMin = 69, part2_attack_coldMax = 127, part3_attack_lightningMin = 13, part3_attack_lightningMax = 256, },
		[16] = { skill_manaCostBase = 11, part1_attack_fireMin = 99, part1_attack_fireMax = 183, part2_attack_coldMin = 81, part2_attack_coldMax = 150, part3_attack_lightningMin = 16, part3_attack_lightningMax = 301, },
		[17] = { skill_manaCostBase = 11, part1_attack_fireMin = 115, part1_attack_fireMax = 214, part2_attack_coldMin = 94, part2_attack_coldMax = 175, part3_attack_lightningMin = 19, part3_attack_lightningMax = 352, },
		[18] = { skill_manaCostBase = 11, part1_attack_fireMin = 135, part1_attack_fireMax = 250, part2_attack_coldMin = 110, part2_attack_coldMax = 205, part3_attack_lightningMin = 22, part3_attack_lightningMax = 411, },
		[19] = { skill_manaCostBase = 11, part1_attack_fireMin = 151, part1_attack_fireMax = 280, part2_attack_coldMin = 123, part2_attack_coldMax = 229, part3_attack_lightningMin = 24, part3_attack_lightningMax = 461, },
		[20] = { skill_manaCostBase = 12, part1_attack_fireMin = 169, part1_attack_fireMax = 314, part2_attack_coldMin = 138, part2_attack_coldMax = 257, part3_attack_lightningMin = 27, part3_attack_lightningMax = 516, },
		[21] = { skill_manaCostBase = 12, part1_attack_fireMin = 182, part1_attack_fireMax = 338, part2_attack_coldMin = 149, part2_attack_coldMax = 276, part3_attack_lightningMin = 29, part3_attack_lightningMax = 555, },
		[22] = { skill_manaCostBase = 12, part1_attack_fireMin = 196, part1_attack_fireMax = 364, part2_attack_coldMin = 160, part2_attack_coldMax = 297, part3_attack_lightningMin = 31, part3_attack_lightningMax = 598, },
		[23] = { skill_manaCostBase = 12, part1_attack_fireMin = 211, part1_attack_fireMax = 391, part2_attack_coldMin = 172, part2_attack_coldMax = 320, part3_attack_lightningMin = 34, part3_attack_lightningMax = 643, },
		[24] = { skill_manaCostBase = 13, part1_attack_fireMin = 226, part1_attack_fireMax = 420, part2_attack_coldMin = 185, part2_attack_coldMax = 344, part3_attack_lightningMin = 36, part3_attack_lightningMax = 691, },
		[25] = { skill_manaCostBase = 13, part1_attack_fireMin = 243, part1_attack_fireMax = 452, part2_attack_coldMin = 199, part2_attack_coldMax = 370, part3_attack_lightningMin = 39, part3_attack_lightningMax = 743, },
		[26] = { skill_manaCostBase = 13, part1_attack_fireMin = 261, part1_attack_fireMax = 485, part2_attack_coldMin = 214, part2_attack_coldMax = 397, part3_attack_lightningMin = 42, part3_attack_lightningMax = 798, },
		[27] = { skill_manaCostBase = 13, part1_attack_fireMin = 281, part1_attack_fireMax = 521, part2_attack_coldMin = 230, part2_attack_coldMax = 426, part3_attack_lightningMin = 45, part3_attack_lightningMax = 857, },
		[28] = { skill_manaCostBase = 14, part1_attack_fireMin = 301, part1_attack_fireMax = 559, part2_attack_coldMin = 246, part2_attack_coldMax = 457, part3_attack_lightningMin = 48, part3_attack_lightningMax = 919, },
		[29] = { skill_manaCostBase = 14, part1_attack_fireMin = 323, part1_attack_fireMax = 600, part2_attack_coldMin = 264, part2_attack_coldMax = 491, part3_attack_lightningMin = 52, part3_attack_lightningMax = 986, },
		[30] = { skill_manaCostBase = 14, part1_attack_fireMin = 346, part1_attack_fireMax = 643, part2_attack_coldMin = 283, part2_attack_coldMax = 526, part3_attack_lightningMin = 56, part3_attack_lightningMax = 1057, },
	}
}
gems["Ethereal Knives"] = {
	spell = true,
	projectile = true,
	base = {
		skill_castTime = 0.6,
		skill_damageEffectiveness = 1,
		skill_critChanceBase = 6,
	},
	quality = {
		projectileSpeedInc = 1,
	},
	levels = {
		[1] = { skill_manaCostBase = 5, skill_physicalMin = 4, skill_physicalMax = 6, projectileSpeedInc = 0, },
		[2] = { skill_manaCostBase = 6, skill_physicalMin = 5, skill_physicalMax = 7, projectileSpeedInc = 1, },
		[3] = { skill_manaCostBase = 7, skill_physicalMin = 6, skill_physicalMax = 9, projectileSpeedInc = 2, },
		[4] = { skill_manaCostBase = 8, skill_physicalMin = 8, skill_physicalMax = 12, projectileSpeedInc = 3, },
		[5] = { skill_manaCostBase = 9, skill_physicalMin = 12, skill_physicalMax = 18, projectileSpeedInc = 4, },
		[6] = { skill_manaCostBase = 10, skill_physicalMin = 18, skill_physicalMax = 27, projectileSpeedInc = 5, },
		[7] = { skill_manaCostBase = 11, skill_physicalMin = 24, skill_physicalMax = 37, projectileSpeedInc = 6, },
		[8] = { skill_manaCostBase = 12, skill_physicalMin = 32, skill_physicalMax = 49, projectileSpeedInc = 7, },
		[9] = { skill_manaCostBase = 13, skill_physicalMin = 42, skill_physicalMax = 64, projectileSpeedInc = 8, },
		[10] = { skill_manaCostBase = 14, skill_physicalMin = 55, skill_physicalMax = 82, projectileSpeedInc = 9, },
		[11] = { skill_manaCostBase = 16, skill_physicalMin = 70, skill_physicalMax = 105, projectileSpeedInc = 10, },
		[12] = { skill_manaCostBase = 17, skill_physicalMin = 89, skill_physicalMax = 134, projectileSpeedInc = 11, },
		[13] = { skill_manaCostBase = 18, skill_physicalMin = 112, skill_physicalMax = 169, projectileSpeedInc = 12, },
		[14] = { skill_manaCostBase = 18, skill_physicalMin = 141, skill_physicalMax = 212, projectileSpeedInc = 13, },
		[15] = { skill_manaCostBase = 19, skill_physicalMin = 176, skill_physicalMax = 265, projectileSpeedInc = 14, },
		[16] = { skill_manaCostBase = 20, skill_physicalMin = 219, skill_physicalMax = 329, projectileSpeedInc = 15, },
		[17] = { skill_manaCostBase = 21, skill_physicalMin = 272, skill_physicalMax = 408, projectileSpeedInc = 16, },
		[18] = { skill_manaCostBase = 22, skill_physicalMin = 336, skill_physicalMax = 504, projectileSpeedInc = 17, },
		[19] = { skill_manaCostBase = 22, skill_physicalMin = 393, skill_physicalMax = 590, projectileSpeedInc = 18, },
		[20] = { skill_manaCostBase = 23, skill_physicalMin = 459, skill_physicalMax = 688, projectileSpeedInc = 19, },
		[21] = { skill_manaCostBase = 24, skill_physicalMin = 509, skill_physicalMax = 763, projectileSpeedInc = 20, },
		[22] = { skill_manaCostBase = 24, skill_physicalMin = 563, skill_physicalMax = 845, projectileSpeedInc = 21, },
		[23] = { skill_manaCostBase = 25, skill_physicalMin = 623, skill_physicalMax = 935, projectileSpeedInc = 22, },
		[24] = { skill_manaCostBase = 25, skill_physicalMin = 690, skill_physicalMax = 1034, projectileSpeedInc = 23, },
		[25] = { skill_manaCostBase = 26, skill_physicalMin = 762, skill_physicalMax = 1144, projectileSpeedInc = 24, },
		[26] = { skill_manaCostBase = 26, skill_physicalMin = 842, skill_physicalMax = 1264, projectileSpeedInc = 25, },
		[27] = { skill_manaCostBase = 27, skill_physicalMin = 931, skill_physicalMax = 1396, projectileSpeedInc = 26, },
		[28] = { skill_manaCostBase = 27, skill_physicalMin = 1027, skill_physicalMax = 1541, projectileSpeedInc = 27, },
		[29] = { skill_manaCostBase = 28, skill_physicalMin = 1134, skill_physicalMax = 1701, projectileSpeedInc = 28, },
		[30] = { skill_manaCostBase = 29, skill_physicalMin = 1251, skill_physicalMax = 1876, projectileSpeedInc = 29, },
	}
}
gems["Explosive Arrow"] = {
	attack = true,
	bow = true,
	projectile = true,
	aoe = true,
	duration = true,
	fire = true,
	parts = {
		{
			name = "Explosion",
			attack = false,
			cast = true,
		},
		{
			name = "Arrow",
			attack = true,
			cast = false,
		},
	},
	base = {
		skill_critChanceBase = 6,
		skill_durationBase = 1,
		attack_damageMore = 0,
	},
	quality = {
		igniteChance = 1,
	},
	levels = {
		[1] = { skill_manaCostBase = 18, skill_fireMin = 44, skill_fireMax = 66, },
		[2] = { skill_manaCostBase = 19, skill_fireMin = 54, skill_fireMax = 81, },
		[3] = { skill_manaCostBase = 20, skill_fireMin = 66, skill_fireMax = 99, },
		[4] = { skill_manaCostBase = 21, skill_fireMin = 80, skill_fireMax = 121, },
		[5] = { skill_manaCostBase = 21, skill_fireMin = 98, skill_fireMax = 146, },
		[6] = { skill_manaCostBase = 22, skill_fireMin = 111, skill_fireMax = 166, },
		[7] = { skill_manaCostBase = 22, skill_fireMin = 126, skill_fireMax = 189, },
		[8] = { skill_manaCostBase = 23, skill_fireMin = 142, skill_fireMax = 214, },
		[9] = { skill_manaCostBase = 23, skill_fireMin = 161, skill_fireMax = 242, },
		[10] = { skill_manaCostBase = 24, skill_fireMin = 182, skill_fireMax = 273, },
		[11] = { skill_manaCostBase = 24, skill_fireMin = 205, skill_fireMax = 308, },
		[12] = { skill_manaCostBase = 24, skill_fireMin = 232, skill_fireMax = 347, },
		[13] = { skill_manaCostBase = 26, skill_fireMin = 261, skill_fireMax = 391, },
		[14] = { skill_manaCostBase = 26, skill_fireMin = 293, skill_fireMax = 440, },
		[15] = { skill_manaCostBase = 26, skill_fireMin = 330, skill_fireMax = 495, },
		[16] = { skill_manaCostBase = 26, skill_fireMin = 371, skill_fireMax = 556, },
		[17] = { skill_manaCostBase = 26, skill_fireMin = 416, skill_fireMax = 624, },
		[18] = { skill_manaCostBase = 27, skill_fireMin = 467, skill_fireMax = 700, },
		[19] = { skill_manaCostBase = 27, skill_fireMin = 523, skill_fireMax = 785, },
		[20] = { skill_manaCostBase = 27, skill_fireMin = 586, skill_fireMax = 879, },
		[21] = { skill_manaCostBase = 28, skill_fireMin = 656, skill_fireMax = 984, },
		[22] = { skill_manaCostBase = 28, skill_fireMin = 734, skill_fireMax = 1100, },
		[23] = { skill_manaCostBase = 29, skill_fireMin = 820, skill_fireMax = 1230, },
		[24] = { skill_manaCostBase = 29, skill_fireMin = 917, skill_fireMax = 1375, },
		[25] = { skill_manaCostBase = 30, skill_fireMin = 1024, skill_fireMax = 1536, },
		[26] = { skill_manaCostBase = 30, skill_fireMin = 1143, skill_fireMax = 1714, },
		[27] = { skill_manaCostBase = 30, skill_fireMin = 1275, skill_fireMax = 1913, },
		[28] = { skill_manaCostBase = 30, skill_fireMin = 1422, skill_fireMax = 2134, },
		[29] = { skill_manaCostBase = 31, skill_fireMin = 1586, skill_fireMax = 2379, },
		[30] = { skill_manaCostBase = 31, skill_fireMin = 1767, skill_fireMax = 2651, },
	}
}
gems["Fire Trap"] = {
	spell = true,
	trap = true,
	aoe = true,
	duration = true,
	fire = true,
	showAverage = true,
	base = {
		skill_castTime = 1,
		skill_damageEffectiveness = 1,
		skill_critChanceBase = 6,
		skill_durationBase = 8,
	},
	quality = {
		degen_fireInc = 1.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 7, skill_fireMin = 2, skill_fireMax = 4, skill_fireDotBase = 3.6, },
		[2] = { skill_manaCostBase = 8, skill_fireMin = 3, skill_fireMax = 5, skill_fireDotBase = 4.1, },
		[3] = { skill_manaCostBase = 9, skill_fireMin = 4, skill_fireMax = 6, skill_fireDotBase = 5.2, },
		[4] = { skill_manaCostBase = 10, skill_fireMin = 6, skill_fireMax = 8, skill_fireDotBase = 7.2, },
		[5] = { skill_manaCostBase = 11, skill_fireMin = 8, skill_fireMax = 12, skill_fireDotBase = 10.6, },
		[6] = { skill_manaCostBase = 12, skill_fireMin = 13, skill_fireMax = 19, skill_fireDotBase = 16.4, },
		[7] = { skill_manaCostBase = 13, skill_fireMin = 18, skill_fireMax = 27, skill_fireDotBase = 22.6, },
		[8] = { skill_manaCostBase = 14, skill_fireMin = 25, skill_fireMax = 37, skill_fireDotBase = 30.5, },
		[9] = { skill_manaCostBase = 14, skill_fireMin = 34, skill_fireMax = 50, skill_fireDotBase = 40.5, },
		[10] = { skill_manaCostBase = 16, skill_fireMin = 45, skill_fireMax = 67, skill_fireDotBase = 53.3, },
		[11] = { skill_manaCostBase = 17, skill_fireMin = 59, skill_fireMax = 89, skill_fireDotBase = 69.5, },
		[12] = { skill_manaCostBase = 18, skill_fireMin = 78, skill_fireMax = 117, skill_fireDotBase = 89.9, },
		[13] = { skill_manaCostBase = 19, skill_fireMin = 101, skill_fireMax = 152, skill_fireDotBase = 115.4, },
		[14] = { skill_manaCostBase = 20, skill_fireMin = 132, skill_fireMax = 197, skill_fireDotBase = 147.4, },
		[15] = { skill_manaCostBase = 21, skill_fireMin = 170, skill_fireMax = 255, skill_fireDotBase = 187.2, },
		[16] = { skill_manaCostBase = 22, skill_fireMin = 219, skill_fireMax = 328, skill_fireDotBase = 236.8, },
		[17] = { skill_manaCostBase = 22, skill_fireMin = 280, skill_fireMax = 420, skill_fireDotBase = 298.3, },
		[18] = { skill_manaCostBase = 23, skill_fireMin = 358, skill_fireMax = 536, skill_fireDotBase = 374.4, },
		[19] = { skill_manaCostBase = 24, skill_fireMin = 429, skill_fireMax = 643, skill_fireDotBase = 441.1, },
		[20] = { skill_manaCostBase = 24, skill_fireMin = 513, skill_fireMax = 770, skill_fireDotBase = 518.8, },
		[21] = { skill_manaCostBase = 25, skill_fireMin = 578, skill_fireMax = 867, skill_fireDotBase = 574, },
		[22] = { skill_manaCostBase = 26, skill_fireMin = 651, skill_fireMax = 976, skill_fireDotBase = 634.4, },
		[23] = { skill_manaCostBase = 26, skill_fireMin = 732, skill_fireMax = 1098, skill_fireDotBase = 700.6, },
		[24] = { skill_manaCostBase = 27, skill_fireMin = 823, skill_fireMax = 1235, skill_fireDotBase = 773, },
		[25] = { skill_manaCostBase = 27, skill_fireMin = 925, skill_fireMax = 1388, skill_fireDotBase = 852.1, },
		[26] = { skill_manaCostBase = 28, skill_fireMin = 1040, skill_fireMax = 1559, skill_fireDotBase = 938.5, },
		[27] = { skill_manaCostBase = 29, skill_fireMin = 1167, skill_fireMax = 1751, skill_fireDotBase = 1032.8, },
		[28] = { skill_manaCostBase = 30, skill_fireMin = 1310, skill_fireMax = 1965, skill_fireDotBase = 1135.5, },
		[29] = { skill_manaCostBase = 30, skill_fireMin = 1470, skill_fireMax = 2205, skill_fireDotBase = 1247.3, },
		[30] = { skill_manaCostBase = 30, skill_fireMin = 1648, skill_fireMax = 2472, skill_fireDotBase = 1369, },
	}
}
gems["Flicker Strike"] = {
	unsupported = true,
}
gems["Freeze Mine"] = {
	spell = true,
	mine = true,
	aoe = true,
	cold = true,
	showAverage = true,
	base = {
		skill_castTime = 0.5,
		skill_damageEffectiveness = 0.5,
	},
	quality = {
		aoeRadiusInc = 0.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 6, skill_coldMin = 7, skill_coldMax = 10, },
		[2] = { skill_manaCostBase = 8, skill_coldMin = 9, skill_coldMax = 13, },
		[3] = { skill_manaCostBase = 10, skill_coldMin = 12, skill_coldMax = 17, },
		[4] = { skill_manaCostBase = 10, skill_coldMin = 15, skill_coldMax = 23, },
		[5] = { skill_manaCostBase = 11, skill_coldMin = 19, skill_coldMax = 29, },
		[6] = { skill_manaCostBase = 12, skill_coldMin = 24, skill_coldMax = 37, },
		[7] = { skill_manaCostBase = 13, skill_coldMin = 30, skill_coldMax = 46, },
		[8] = { skill_manaCostBase = 14, skill_coldMin = 36, skill_coldMax = 54, },
		[9] = { skill_manaCostBase = 14, skill_coldMin = 42, skill_coldMax = 63, },
		[10] = { skill_manaCostBase = 16, skill_coldMin = 49, skill_coldMax = 73, },
		[11] = { skill_manaCostBase = 18, skill_coldMin = 57, skill_coldMax = 85, },
		[12] = { skill_manaCostBase = 18, skill_coldMin = 66, skill_coldMax = 99, },
		[13] = { skill_manaCostBase = 19, skill_coldMin = 76, skill_coldMax = 114, },
		[14] = { skill_manaCostBase = 20, skill_coldMin = 88, skill_coldMax = 131, },
		[15] = { skill_manaCostBase = 21, skill_coldMin = 101, skill_coldMax = 151, },
		[16] = { skill_manaCostBase = 21, skill_coldMin = 116, skill_coldMax = 173, },
		[17] = { skill_manaCostBase = 21, skill_coldMin = 132, skill_coldMax = 199, },
		[18] = { skill_manaCostBase = 21, skill_coldMin = 151, skill_coldMax = 227, },
		[19] = { skill_manaCostBase = 22, skill_coldMin = 165, skill_coldMax = 248, },
		[20] = { skill_manaCostBase = 22, skill_coldMin = 181, skill_coldMax = 271, },
		[21] = { skill_manaCostBase = 22, skill_coldMin = 197, skill_coldMax = 296, },
		[22] = { skill_manaCostBase = 22, skill_coldMin = 215, skill_coldMax = 322, },
		[23] = { skill_manaCostBase = 23, skill_coldMin = 234, skill_coldMax = 351, },
		[24] = { skill_manaCostBase = 23, skill_coldMin = 255, skill_coldMax = 383, },
		[25] = { skill_manaCostBase = 24, skill_coldMin = 278, skill_coldMax = 417, },
		[26] = { skill_manaCostBase = 24, skill_coldMin = 302, skill_coldMax = 454, },
		[27] = { skill_manaCostBase = 24, skill_coldMin = 329, skill_coldMax = 493, },
		[28] = { skill_manaCostBase = 24, skill_coldMin = 358, skill_coldMax = 536, },
		[29] = { skill_manaCostBase = 25, skill_coldMin = 389, skill_coldMax = 583, },
		[30] = { skill_manaCostBase = 25, skill_coldMin = 422, skill_coldMax = 633, },
	}
}
gems["Frenzy"] = {
	attack = true,
	melee = true,
	bow = true,
	projectile = true,
	base = {
		skill_manaCostBase = 10,
		frenzy_attack_physicalInc = 5,
		frenzy_attackSpeedInc = 5,
	},
	quality = {
		attackSpeedInc = 0.5,
	},
	levels = {
		[1] = { attack_damageMore = 1.1, },
		[2] = { attack_damageMore = 1.114, },
		[3] = { attack_damageMore = 1.128, },
		[4] = { attack_damageMore = 1.142, },
		[5] = { attack_damageMore = 1.156, },
		[6] = { attack_damageMore = 1.17, },
		[7] = { attack_damageMore = 1.184, },
		[8] = { attack_damageMore = 1.198, },
		[9] = { attack_damageMore = 1.212, },
		[10] = { attack_damageMore = 1.226, },
		[11] = { attack_damageMore = 1.24, },
		[12] = { attack_damageMore = 1.254, },
		[13] = { attack_damageMore = 1.268, },
		[14] = { attack_damageMore = 1.282, },
		[15] = { attack_damageMore = 1.296, },
		[16] = { attack_damageMore = 1.31, },
		[17] = { attack_damageMore = 1.324, },
		[18] = { attack_damageMore = 1.338, },
		[19] = { attack_damageMore = 1.352, },
		[20] = { attack_damageMore = 1.366, },
		[21] = { attack_damageMore = 1.38, },
		[22] = { attack_damageMore = 1.394, },
		[23] = { attack_damageMore = 1.408, },
		[24] = { attack_damageMore = 1.422, },
		[25] = { attack_damageMore = 1.436, },
		[26] = { attack_damageMore = 1.45, },
		[27] = { attack_damageMore = 1.464, },
		[28] = { attack_damageMore = 1.478, },
		[29] = { attack_damageMore = 1.492, },
		[30] = { attack_damageMore = 1.506, },
	}
}
gems["Frost Blades"] = {
	attack = true,
	melee = true,
	projectile = true,
	cold = true,
	parts = {
		{
			name = "Melee hit",
			melee = true,
			projectile = false,
		},
		{
			name = "Icy blades",
			melee = false,
			projectile = true,
		},
	},
	base = {
		skill_manaCostBase = 6,
		physicalGainAscold = 40,
	},
	quality = {
		projectile_damageInc = 1,
	},
	levels = {
		[1] = { attack_damageMore = 1, },
		[2] = { attack_damageMore = 1.012, },
		[3] = { attack_damageMore = 1.024, },
		[4] = { attack_damageMore = 1.036, },
		[5] = { attack_damageMore = 1.048, },
		[6] = { attack_damageMore = 1.06, },
		[7] = { attack_damageMore = 1.072, },
		[8] = { attack_damageMore = 1.084, },
		[9] = { attack_damageMore = 1.096, },
		[10] = { attack_damageMore = 1.108, },
		[11] = { attack_damageMore = 1.12, },
		[12] = { attack_damageMore = 1.132, },
		[13] = { attack_damageMore = 1.144, },
		[14] = { attack_damageMore = 1.156, },
		[15] = { attack_damageMore = 1.168, },
		[16] = { attack_damageMore = 1.18, },
		[17] = { attack_damageMore = 1.192, },
		[18] = { attack_damageMore = 1.204, },
		[19] = { attack_damageMore = 1.216, },
		[20] = { attack_damageMore = 1.228, },
		[21] = { attack_damageMore = 1.24, },
		[22] = { attack_damageMore = 1.252, },
		[23] = { attack_damageMore = 1.264, },
		[24] = { attack_damageMore = 1.276, },
		[25] = { attack_damageMore = 1.288, },
		[26] = { attack_damageMore = 1.3, },
		[27] = { attack_damageMore = 1.312, },
		[28] = { attack_damageMore = 1.324, },
		[29] = { attack_damageMore = 1.336, },
		[30] = { attack_damageMore = 1.348, },
	}
}
gems["Grace"] = {
	aura = true,
	spell = true,
	aoe = true,
	base = {
		skill_manaReservedPercent = 50,
	},
	quality = {
		auraRadiusInc = 1,
	},
	levels = {
		[1] = { auraRadiusInc = 0, evasionBase = 227, },
		[2] = { auraRadiusInc = 3, evasionBase = 271, },
		[3] = { auraRadiusInc = 6, evasionBase = 322, },
		[4] = { auraRadiusInc = 9, evasionBase = 379, },
		[5] = { auraRadiusInc = 12, evasionBase = 444, },
		[6] = { auraRadiusInc = 15, evasionBase = 528, },
		[7] = { auraRadiusInc = 18, evasionBase = 621, },
		[8] = { auraRadiusInc = 21, evasionBase = 722, },
		[9] = { auraRadiusInc = 23, evasionBase = 845, },
		[10] = { auraRadiusInc = 25, evasionBase = 940, },
		[11] = { auraRadiusInc = 27, evasionBase = 1043, },
		[12] = { auraRadiusInc = 29, evasionBase = 1155, },
		[13] = { auraRadiusInc = 31, evasionBase = 1283, },
		[14] = { auraRadiusInc = 33, evasionBase = 1413, },
		[15] = { auraRadiusInc = 35, evasionBase = 1567, },
		[16] = { auraRadiusInc = 36, evasionBase = 1732, },
		[17] = { auraRadiusInc = 37, evasionBase = 1914, },
		[18] = { auraRadiusInc = 38, evasionBase = 2115, },
		[19] = { auraRadiusInc = 39, evasionBase = 2335, },
		[20] = { auraRadiusInc = 40, evasionBase = 2575, },
		[21] = { auraRadiusInc = 41, evasionBase = 2700, },
		[22] = { auraRadiusInc = 42, evasionBase = 2835, },
		[23] = { auraRadiusInc = 43, evasionBase = 2979, },
		[24] = { auraRadiusInc = 44, evasionBase = 3124, },
		[25] = { auraRadiusInc = 45, evasionBase = 3279, },
		[26] = { auraRadiusInc = 46, evasionBase = 3444, },
		[27] = { auraRadiusInc = 47, evasionBase = 3611, },
		[28] = { auraRadiusInc = 48, evasionBase = 3795, },
		[29] = { auraRadiusInc = 49, evasionBase = 3982, },
		[30] = { auraRadiusInc = 50, evasionBase = 4179, },
	}
}
gems["Haste"] = {
	aura = true,
	spell = true,
	aoe = true,
	base = {
		skill_manaReservedPercent = 50,
	},
	quality = {
		auraRadiusInc = 1,
	},
	levels = {
		[1] = { auraRadiusInc = 0, attackSpeedInc = 9, castSpeedInc = 9, movementSpeedInc = 4, },
		[2] = { auraRadiusInc = 3, attackSpeedInc = 10, castSpeedInc = 9, movementSpeedInc = 4, },
		[3] = { auraRadiusInc = 6, attackSpeedInc = 10, castSpeedInc = 10, movementSpeedInc = 4, },
		[4] = { auraRadiusInc = 9, attackSpeedInc = 10, castSpeedInc = 10, movementSpeedInc = 5, },
		[5] = { auraRadiusInc = 12, attackSpeedInc = 11, castSpeedInc = 10, movementSpeedInc = 5, },
		[6] = { auraRadiusInc = 15, attackSpeedInc = 11, castSpeedInc = 11, movementSpeedInc = 5, },
		[7] = { auraRadiusInc = 18, attackSpeedInc = 11, castSpeedInc = 11, movementSpeedInc = 6, },
		[8] = { auraRadiusInc = 21, attackSpeedInc = 12, castSpeedInc = 11, movementSpeedInc = 6, },
		[9] = { auraRadiusInc = 23, attackSpeedInc = 12, castSpeedInc = 12, movementSpeedInc = 6, },
		[10] = { auraRadiusInc = 25, attackSpeedInc = 12, castSpeedInc = 12, movementSpeedInc = 7, },
		[11] = { auraRadiusInc = 27, attackSpeedInc = 13, castSpeedInc = 12, movementSpeedInc = 7, },
		[12] = { auraRadiusInc = 29, attackSpeedInc = 13, castSpeedInc = 13, movementSpeedInc = 7, },
		[13] = { auraRadiusInc = 31, attackSpeedInc = 13, castSpeedInc = 13, movementSpeedInc = 8, },
		[14] = { auraRadiusInc = 33, attackSpeedInc = 14, castSpeedInc = 13, movementSpeedInc = 8, },
		[15] = { auraRadiusInc = 35, attackSpeedInc = 14, castSpeedInc = 14, movementSpeedInc = 8, },
		[16] = { auraRadiusInc = 36, attackSpeedInc = 15, castSpeedInc = 14, movementSpeedInc = 8, },
		[17] = { auraRadiusInc = 37, attackSpeedInc = 15, castSpeedInc = 15, movementSpeedInc = 8, },
		[18] = { auraRadiusInc = 38, attackSpeedInc = 16, castSpeedInc = 15, movementSpeedInc = 8, },
		[19] = { auraRadiusInc = 39, attackSpeedInc = 16, castSpeedInc = 16, movementSpeedInc = 8, },
		[20] = { auraRadiusInc = 40, attackSpeedInc = 16, castSpeedInc = 16, movementSpeedInc = 9, },
		[21] = { auraRadiusInc = 41, attackSpeedInc = 17, castSpeedInc = 16, movementSpeedInc = 9, },
		[22] = { auraRadiusInc = 42, attackSpeedInc = 17, castSpeedInc = 17, movementSpeedInc = 9, },
		[23] = { auraRadiusInc = 43, attackSpeedInc = 17, castSpeedInc = 17, movementSpeedInc = 10, },
		[24] = { auraRadiusInc = 44, attackSpeedInc = 18, castSpeedInc = 17, movementSpeedInc = 10, },
		[25] = { auraRadiusInc = 45, attackSpeedInc = 18, castSpeedInc = 18, movementSpeedInc = 10, },
		[26] = { auraRadiusInc = 46, attackSpeedInc = 18, castSpeedInc = 18, movementSpeedInc = 11, },
		[27] = { auraRadiusInc = 47, attackSpeedInc = 19, castSpeedInc = 18, movementSpeedInc = 11, },
		[28] = { auraRadiusInc = 48, attackSpeedInc = 19, castSpeedInc = 19, movementSpeedInc = 11, },
		[29] = { auraRadiusInc = 49, attackSpeedInc = 19, castSpeedInc = 19, movementSpeedInc = 12, },
		[30] = { auraRadiusInc = 50, attackSpeedInc = 20, castSpeedInc = 19, movementSpeedInc = 12, },
	}
}
gems["Hatred"] = {
	aura = true,
	spell = true,
	aoe = true,
	cold = true,
	base = {
		skill_manaReservedPercent = 50,
	},
	quality = {
		auraRadiusInc = 1,
	},
	levels = {
		[1] = { auraRadiusInc = 0, physicalGainAscold = 26, },
		[2] = { auraRadiusInc = 3, physicalGainAscold = 26, },
		[3] = { auraRadiusInc = 6, physicalGainAscold = 27, },
		[4] = { auraRadiusInc = 9, physicalGainAscold = 27, },
		[5] = { auraRadiusInc = 12, physicalGainAscold = 28, },
		[6] = { auraRadiusInc = 15, physicalGainAscold = 28, },
		[7] = { auraRadiusInc = 18, physicalGainAscold = 29, },
		[8] = { auraRadiusInc = 21, physicalGainAscold = 29, },
		[9] = { auraRadiusInc = 23, physicalGainAscold = 30, },
		[10] = { auraRadiusInc = 25, physicalGainAscold = 30, },
		[11] = { auraRadiusInc = 27, physicalGainAscold = 31, },
		[12] = { auraRadiusInc = 29, physicalGainAscold = 31, },
		[13] = { auraRadiusInc = 31, physicalGainAscold = 32, },
		[14] = { auraRadiusInc = 33, physicalGainAscold = 32, },
		[15] = { auraRadiusInc = 35, physicalGainAscold = 33, },
		[16] = { auraRadiusInc = 36, physicalGainAscold = 34, },
		[17] = { auraRadiusInc = 37, physicalGainAscold = 34, },
		[18] = { auraRadiusInc = 38, physicalGainAscold = 35, },
		[19] = { auraRadiusInc = 39, physicalGainAscold = 35, },
		[20] = { auraRadiusInc = 40, physicalGainAscold = 36, },
		[21] = { auraRadiusInc = 41, physicalGainAscold = 36, },
		[22] = { auraRadiusInc = 42, physicalGainAscold = 37, },
		[23] = { auraRadiusInc = 43, physicalGainAscold = 37, },
		[24] = { auraRadiusInc = 44, physicalGainAscold = 38, },
		[25] = { auraRadiusInc = 45, physicalGainAscold = 38, },
		[26] = { auraRadiusInc = 46, physicalGainAscold = 39, },
		[27] = { auraRadiusInc = 47, physicalGainAscold = 39, },
		[28] = { auraRadiusInc = 48, physicalGainAscold = 40, },
		[29] = { auraRadiusInc = 49, physicalGainAscold = 40, },
		[30] = { auraRadiusInc = 50, physicalGainAscold = 41, },
	}
}
gems["Herald of Ice"] = {
	cast = true,
	aoe = true,
	cold = true,
	base = {
		skill_manaReservedPercent = 25,
		skill_damageEffectiveness = 0.8,
	},
	quality = {
		buff_coldInc = 0.75,
	},
	levels = {
		[1] = { buff_spell_coldMin = 4, buff_spell_coldMax = 5, buff_attack_coldMin = 4, buff_attack_coldMax = 5, skill_coldMin = 18, skill_coldMax = 26, },
		[2] = { buff_spell_coldMin = 5, buff_spell_coldMax = 7, buff_attack_coldMin = 5, buff_attack_coldMax = 7, skill_coldMin = 23, skill_coldMax = 35, },
		[3] = { buff_spell_coldMin = 6, buff_spell_coldMax = 8, buff_attack_coldMin = 6, buff_attack_coldMax = 8, skill_coldMin = 30, skill_coldMax = 45, },
		[4] = { buff_spell_coldMin = 7, buff_spell_coldMax = 10, buff_attack_coldMin = 7, buff_attack_coldMax = 10, skill_coldMin = 38, skill_coldMax = 57, },
		[5] = { buff_spell_coldMin = 8, buff_spell_coldMax = 12, buff_attack_coldMin = 8, buff_attack_coldMax = 12, skill_coldMin = 45, skill_coldMax = 67, },
		[6] = { buff_spell_coldMin = 9, buff_spell_coldMax = 14, buff_attack_coldMin = 9, buff_attack_coldMax = 14, skill_coldMin = 53, skill_coldMax = 80, },
		[7] = { buff_spell_coldMin = 10, buff_spell_coldMax = 16, buff_attack_coldMin = 10, buff_attack_coldMax = 16, skill_coldMin = 62, skill_coldMax = 94, },
		[8] = { buff_spell_coldMin = 12, buff_spell_coldMax = 18, buff_attack_coldMin = 12, buff_attack_coldMax = 18, skill_coldMin = 73, skill_coldMax = 110, },
		[9] = { buff_spell_coldMin = 13, buff_spell_coldMax = 20, buff_attack_coldMin = 13, buff_attack_coldMax = 20, skill_coldMin = 85, skill_coldMax = 128, },
		[10] = { buff_spell_coldMin = 15, buff_spell_coldMax = 23, buff_attack_coldMin = 15, buff_attack_coldMax = 23, skill_coldMin = 99, skill_coldMax = 149, },
		[11] = { buff_spell_coldMin = 17, buff_spell_coldMax = 26, buff_attack_coldMin = 17, buff_attack_coldMax = 26, skill_coldMin = 115, skill_coldMax = 173, },
		[12] = { buff_spell_coldMin = 19, buff_spell_coldMax = 29, buff_attack_coldMin = 19, buff_attack_coldMax = 29, skill_coldMin = 134, skill_coldMax = 200, },
		[13] = { buff_spell_coldMin = 22, buff_spell_coldMax = 33, buff_attack_coldMin = 22, buff_attack_coldMax = 33, skill_coldMin = 154, skill_coldMax = 232, },
		[14] = { buff_spell_coldMin = 24, buff_spell_coldMax = 37, buff_attack_coldMin = 24, buff_attack_coldMax = 37, skill_coldMin = 178, skill_coldMax = 267, },
		[15] = { buff_spell_coldMin = 26, buff_spell_coldMax = 39, buff_attack_coldMin = 26, buff_attack_coldMax = 39, skill_coldMin = 195, skill_coldMax = 293, },
		[16] = { buff_spell_coldMin = 28, buff_spell_coldMax = 42, buff_attack_coldMin = 28, buff_attack_coldMax = 42, skill_coldMin = 214, skill_coldMax = 321, },
		[17] = { buff_spell_coldMin = 30, buff_spell_coldMax = 46, buff_attack_coldMin = 30, buff_attack_coldMax = 46, skill_coldMin = 235, skill_coldMax = 352, },
		[18] = { buff_spell_coldMin = 33, buff_spell_coldMax = 49, buff_attack_coldMin = 33, buff_attack_coldMax = 49, skill_coldMin = 257, skill_coldMax = 386, },
		[19] = { buff_spell_coldMin = 35, buff_spell_coldMax = 53, buff_attack_coldMin = 35, buff_attack_coldMax = 53, skill_coldMin = 282, skill_coldMax = 422, },
		[20] = { buff_spell_coldMin = 38, buff_spell_coldMax = 56, buff_attack_coldMin = 38, buff_attack_coldMax = 56, skill_coldMin = 308, skill_coldMax = 462, },
		[21] = { buff_spell_coldMin = 40, buff_spell_coldMax = 61, buff_attack_coldMin = 40, buff_attack_coldMax = 61, skill_coldMin = 337, skill_coldMax = 505, },
		[22] = { buff_spell_coldMin = 43, buff_spell_coldMax = 65, buff_attack_coldMin = 43, buff_attack_coldMax = 65, skill_coldMin = 368, skill_coldMax = 552, },
		[23] = { buff_spell_coldMin = 46, buff_spell_coldMax = 70, buff_attack_coldMin = 46, buff_attack_coldMax = 70, skill_coldMin = 402, skill_coldMax = 603, },
		[24] = { buff_spell_coldMin = 50, buff_spell_coldMax = 75, buff_attack_coldMin = 50, buff_attack_coldMax = 75, skill_coldMin = 438, skill_coldMax = 658, },
		[25] = { buff_spell_coldMin = 53, buff_spell_coldMax = 80, buff_attack_coldMin = 53, buff_attack_coldMax = 80, skill_coldMin = 478, skill_coldMax = 717, },
		[26] = { buff_spell_coldMin = 57, buff_spell_coldMax = 85, buff_attack_coldMin = 57, buff_attack_coldMax = 85, skill_coldMin = 521, skill_coldMax = 782, },
		[27] = { buff_spell_coldMin = 61, buff_spell_coldMax = 91, buff_attack_coldMin = 61, buff_attack_coldMax = 91, skill_coldMin = 568, skill_coldMax = 852, },
		[28] = { buff_spell_coldMin = 65, buff_spell_coldMax = 98, buff_attack_coldMin = 65, buff_attack_coldMax = 98, skill_coldMin = 619, skill_coldMax = 928, },
		[29] = { buff_spell_coldMin = 69, buff_spell_coldMax = 104, buff_attack_coldMin = 69, buff_attack_coldMax = 104, skill_coldMin = 674, skill_coldMax = 1010, },
		[30] = { buff_spell_coldMin = 74, buff_spell_coldMax = 111, buff_attack_coldMin = 74, buff_attack_coldMax = 111, skill_coldMin = 733, skill_coldMax = 1100, },
	}
}
gems["Ice Shot"] = {
	attack = true,
	bow = true,
	projectile = true,
	aoe = true,
	duration = true,
	cold = true,
	parts = {
		{
			name = "Arrow",
			aoe = false,
		},
		{
			name = "Cone",
			aoe = true,
		},
	},
	base = {
		skill_durationBase = 1.5,
		part1_physicalGainAscold = 40,
		part2_physicalGainAscold = 100,
	},
	quality = {
		coldInc = 1,
	},
	levels = {
		[1] = { skill_manaCostBase = 6, attack_damageMore = 1.2, },
		[2] = { skill_manaCostBase = 6, attack_damageMore = 1.214, },
		[3] = { skill_manaCostBase = 6, attack_damageMore = 1.228, },
		[4] = { skill_manaCostBase = 7, attack_damageMore = 1.242, },
		[5] = { skill_manaCostBase = 7, attack_damageMore = 1.256, },
		[6] = { skill_manaCostBase = 7, attack_damageMore = 1.27, },
		[7] = { skill_manaCostBase = 7, attack_damageMore = 1.284, },
		[8] = { skill_manaCostBase = 8, attack_damageMore = 1.298, },
		[9] = { skill_manaCostBase = 8, attack_damageMore = 1.312, },
		[10] = { skill_manaCostBase = 8, attack_damageMore = 1.326, },
		[11] = { skill_manaCostBase = 8, attack_damageMore = 1.34, },
		[12] = { skill_manaCostBase = 8, attack_damageMore = 1.354, },
		[13] = { skill_manaCostBase = 9, attack_damageMore = 1.368, },
		[14] = { skill_manaCostBase = 9, attack_damageMore = 1.382, },
		[15] = { skill_manaCostBase = 9, attack_damageMore = 1.396, },
		[16] = { skill_manaCostBase = 9, attack_damageMore = 1.41, },
		[17] = { skill_manaCostBase = 9, attack_damageMore = 1.424, },
		[18] = { skill_manaCostBase = 10, attack_damageMore = 1.438, },
		[19] = { skill_manaCostBase = 10, attack_damageMore = 1.452, },
		[20] = { skill_manaCostBase = 10, attack_damageMore = 1.466, },
		[21] = { skill_manaCostBase = 10, attack_damageMore = 1.48, },
		[22] = { skill_manaCostBase = 10, attack_damageMore = 1.494, },
		[23] = { skill_manaCostBase = 11, attack_damageMore = 1.508, },
		[24] = { skill_manaCostBase = 11, attack_damageMore = 1.522, },
		[25] = { skill_manaCostBase = 11, attack_damageMore = 1.536, },
		[26] = { skill_manaCostBase = 11, attack_damageMore = 1.55, },
		[27] = { skill_manaCostBase = 11, attack_damageMore = 1.564, },
		[28] = { skill_manaCostBase = 12, attack_damageMore = 1.578, },
		[29] = { skill_manaCostBase = 12, attack_damageMore = 1.592, },
		[30] = { skill_manaCostBase = 12, attack_damageMore = 1.606, },
	}
}
gems["Ice Trap"] = {
	spell = true,
	trap = true,
	aoe = true,
	cold = true,
	showAverage = true,
	base = {
		skill_castTime = 1,
		skill_damageEffectiveness = 1.1,
		skill_critChanceBase = 5,
	},
	quality = {
		aoeRadiusInc = 0.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 13, skill_coldMin = 60, skill_coldMax = 90, },
		[2] = { skill_manaCostBase = 14, skill_coldMin = 72, skill_coldMax = 108, },
		[3] = { skill_manaCostBase = 15, skill_coldMin = 85, skill_coldMax = 128, },
		[4] = { skill_manaCostBase = 15, skill_coldMin = 101, skill_coldMax = 151, },
		[5] = { skill_manaCostBase = 16, skill_coldMin = 119, skill_coldMax = 178, },
		[6] = { skill_manaCostBase = 17, skill_coldMin = 132, skill_coldMax = 198, },
		[7] = { skill_manaCostBase = 17, skill_coldMin = 147, skill_coldMax = 220, },
		[8] = { skill_manaCostBase = 18, skill_coldMin = 163, skill_coldMax = 244, },
		[9] = { skill_manaCostBase = 19, skill_coldMin = 180, skill_coldMax = 270, },
		[10] = { skill_manaCostBase = 19, skill_coldMin = 199, skill_coldMax = 299, },
		[11] = { skill_manaCostBase = 20, skill_coldMin = 220, skill_coldMax = 330, },
		[12] = { skill_manaCostBase = 20, skill_coldMin = 243, skill_coldMax = 364, },
		[13] = { skill_manaCostBase = 21, skill_coldMin = 268, skill_coldMax = 402, },
		[14] = { skill_manaCostBase = 21, skill_coldMin = 295, skill_coldMax = 442, },
		[15] = { skill_manaCostBase = 22, skill_coldMin = 325, skill_coldMax = 487, },
		[16] = { skill_manaCostBase = 23, skill_coldMin = 357, skill_coldMax = 536, },
		[17] = { skill_manaCostBase = 23, skill_coldMin = 392, skill_coldMax = 589, },
		[18] = { skill_manaCostBase = 24, skill_coldMin = 431, skill_coldMax = 646, },
		[19] = { skill_manaCostBase = 24, skill_coldMin = 473, skill_coldMax = 709, },
		[20] = { skill_manaCostBase = 25, skill_coldMin = 519, skill_coldMax = 778, },
		[21] = { skill_manaCostBase = 26, skill_coldMin = 568, skill_coldMax = 853, },
		[22] = { skill_manaCostBase = 26, skill_coldMin = 623, skill_coldMax = 934, },
		[23] = { skill_manaCostBase = 27, skill_coldMin = 681, skill_coldMax = 1022, },
		[24] = { skill_manaCostBase = 27, skill_coldMin = 746, skill_coldMax = 1118, },
		[25] = { skill_manaCostBase = 28, skill_coldMin = 815, skill_coldMax = 1223, },
		[26] = { skill_manaCostBase = 28, skill_coldMin = 891, skill_coldMax = 1337, },
		[27] = { skill_manaCostBase = 29, skill_coldMin = 973, skill_coldMax = 1460, },
		[28] = { skill_manaCostBase = 30, skill_coldMin = 1063, skill_coldMax = 1595, },
		[29] = { skill_manaCostBase = 30, skill_coldMin = 1160, skill_coldMax = 1740, },
		[30] = { skill_manaCostBase = 31, skill_coldMin = 1266, skill_coldMax = 1899, },
	}
}
gems["Lightning Arrow"] = {
	attack = true,
	bow = true,
	projectile = true,
	aoe = true,
	lightning = true,
	parts = {
		{
			aoe = false,
		},
	},
	base = {
		physicalConvertTolightning = 50,
	},
	quality = {
		shockChance = 0.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 7, attack_damageMore = 1, },
		[2] = { skill_manaCostBase = 7, attack_damageMore = 1.01, },
		[3] = { skill_manaCostBase = 7, attack_damageMore = 1.02, },
		[4] = { skill_manaCostBase = 8, attack_damageMore = 1.03, },
		[5] = { skill_manaCostBase = 8, attack_damageMore = 1.04, },
		[6] = { skill_manaCostBase = 8, attack_damageMore = 1.05, },
		[7] = { skill_manaCostBase = 8, attack_damageMore = 1.06, },
		[8] = { skill_manaCostBase = 8, attack_damageMore = 1.07, },
		[9] = { skill_manaCostBase = 9, attack_damageMore = 1.08, },
		[10] = { skill_manaCostBase = 9, attack_damageMore = 1.09, },
		[11] = { skill_manaCostBase = 9, attack_damageMore = 1.1, },
		[12] = { skill_manaCostBase = 9, attack_damageMore = 1.11, },
		[13] = { skill_manaCostBase = 9, attack_damageMore = 1.12, },
		[14] = { skill_manaCostBase = 10, attack_damageMore = 1.13, },
		[15] = { skill_manaCostBase = 10, attack_damageMore = 1.14, },
		[16] = { skill_manaCostBase = 10, attack_damageMore = 1.15, },
		[17] = { skill_manaCostBase = 10, attack_damageMore = 1.16, },
		[18] = { skill_manaCostBase = 10, attack_damageMore = 1.17, },
		[19] = { skill_manaCostBase = 11, attack_damageMore = 1.18, },
		[20] = { skill_manaCostBase = 11, attack_damageMore = 1.19, },
		[21] = { skill_manaCostBase = 11, attack_damageMore = 1.2, },
		[22] = { skill_manaCostBase = 11, attack_damageMore = 1.21, },
		[23] = { skill_manaCostBase = 11, attack_damageMore = 1.22, },
		[24] = { skill_manaCostBase = 11, attack_damageMore = 1.23, },
		[25] = { skill_manaCostBase = 11, attack_damageMore = 1.24, },
		[26] = { skill_manaCostBase = 12, attack_damageMore = 1.25, },
		[27] = { skill_manaCostBase = 12, attack_damageMore = 1.26, },
		[28] = { skill_manaCostBase = 12, attack_damageMore = 1.27, },
		[29] = { skill_manaCostBase = 12, attack_damageMore = 1.28, },
		[30] = { skill_manaCostBase = 12, attack_damageMore = 1.29, },
	}
}
gems["Lightning Strike"] = {
	attack = true,
	melee = true,
	projectile = true,
	lightning = true,
	parts = {
		{
			name = "Melee hit",
			melee = true,
			projectile = false,
		},
		{
			name = "Projectiles",
			melee = false,
			projectile = true,
		},
	},
	base = {
		skill_manaCostBase = 6,
		physicalConvertTolightning = 50,
		part2_damageMore = 0.75,
	},
	quality = {
		pierceChance = 2,
	},
	levels = {
		[1] = { attack_damageMore = 1.3, },
		[2] = { attack_damageMore = 1.316, },
		[3] = { attack_damageMore = 1.332, },
		[4] = { attack_damageMore = 1.348, },
		[5] = { attack_damageMore = 1.364, },
		[6] = { attack_damageMore = 1.38, },
		[7] = { attack_damageMore = 1.396, },
		[8] = { attack_damageMore = 1.412, },
		[9] = { attack_damageMore = 1.428, },
		[10] = { attack_damageMore = 1.444, },
		[11] = { attack_damageMore = 1.46, },
		[12] = { attack_damageMore = 1.476, },
		[13] = { attack_damageMore = 1.492, },
		[14] = { attack_damageMore = 1.508, },
		[15] = { attack_damageMore = 1.524, },
		[16] = { attack_damageMore = 1.54, },
		[17] = { attack_damageMore = 1.556, },
		[18] = { attack_damageMore = 1.572, },
		[19] = { attack_damageMore = 1.588, },
		[20] = { attack_damageMore = 1.604, },
		[21] = { attack_damageMore = 1.62, },
		[22] = { attack_damageMore = 1.636, },
		[23] = { attack_damageMore = 1.652, },
		[24] = { attack_damageMore = 1.668, },
		[25] = { attack_damageMore = 1.684, },
		[26] = { attack_damageMore = 1.7, },
		[27] = { attack_damageMore = 1.716, },
		[28] = { attack_damageMore = 1.732, },
		[29] = { attack_damageMore = 1.748, },
		[30] = { attack_damageMore = 1.764, },
	}
}
gems["Mirror Arrow"] = {
	unsupported = true,
}
gems["Phase Run"] = {
	unsupported = true,
}
gems["Poacher's Mark"] = {
	unsupported = true,
}
gems["Projectile Weakness"] = {
	unsupported = true,
}
gems["Puncture"] = {
	attack = true,
	bow = true,
	projectile = true,
	melee = true,
	duration = true,
	base = {
		skill_manaCostBase = 6,
		bleedChance = 100,
	},
	quality = {
		durationInc = 1,
	},
	levels = {
		[1] = { attack_damageMore = 1, },
		[2] = { attack_damageMore = 1.012, },
		[3] = { attack_damageMore = 1.024, },
		[4] = { attack_damageMore = 1.036, },
		[5] = { attack_damageMore = 1.048, },
		[6] = { attack_damageMore = 1.06, },
		[7] = { attack_damageMore = 1.072, },
		[8] = { attack_damageMore = 1.084, },
		[9] = { attack_damageMore = 1.096, },
		[10] = { attack_damageMore = 1.108, },
		[11] = { attack_damageMore = 1.12, },
		[12] = { attack_damageMore = 1.132, },
		[13] = { attack_damageMore = 1.144, },
		[14] = { attack_damageMore = 1.156, },
		[15] = { attack_damageMore = 1.168, },
		[16] = { attack_damageMore = 1.18, },
		[17] = { attack_damageMore = 1.192, },
		[18] = { attack_damageMore = 1.204, },
		[19] = { attack_damageMore = 1.216, },
		[20] = { attack_damageMore = 1.228, },
		[21] = { attack_damageMore = 1.24, },
		[22] = { attack_damageMore = 1.252, },
		[23] = { attack_damageMore = 1.264, },
		[24] = { attack_damageMore = 1.276, },
		[25] = { attack_damageMore = 1.288, },
		[26] = { attack_damageMore = 1.3, },
		[27] = { attack_damageMore = 1.312, },
		[28] = { attack_damageMore = 1.324, },
		[29] = { attack_damageMore = 1.336, },
		[30] = { attack_damageMore = 1.348, },
	}
}
gems["Purity of Ice"] = {
	aura = true,
	spell = true,
	aoe = true,
	fire = true,
	base = {
		skill_manaReservedPercent = 35,
	},
	quality = {
		auraRadiusInc = 1,
	},
	levels = {
		[1] = { auraRadiusInc = 0, coldResist = 22, coldResistMax = 0, },
		[2] = { auraRadiusInc = 3, coldResist = 23, coldResistMax = 0, },
		[3] = { auraRadiusInc = 6, coldResist = 24, coldResistMax = 0, },
		[4] = { auraRadiusInc = 9, coldResist = 25, coldResistMax = 0, },
		[5] = { auraRadiusInc = 12, coldResist = 26, coldResistMax = 1, },
		[6] = { auraRadiusInc = 15, coldResist = 27, coldResistMax = 1, },
		[7] = { auraRadiusInc = 18, coldResist = 28, coldResistMax = 1, },
		[8] = { auraRadiusInc = 21, coldResist = 29, coldResistMax = 1, },
		[9] = { auraRadiusInc = 23, coldResist = 30, coldResistMax = 1, },
		[10] = { auraRadiusInc = 25, coldResist = 31, coldResistMax = 1, },
		[11] = { auraRadiusInc = 27, coldResist = 32, coldResistMax = 2, },
		[12] = { auraRadiusInc = 29, coldResist = 33, coldResistMax = 2, },
		[13] = { auraRadiusInc = 31, coldResist = 34, coldResistMax = 2, },
		[14] = { auraRadiusInc = 33, coldResist = 35, coldResistMax = 2, },
		[15] = { auraRadiusInc = 35, coldResist = 36, coldResistMax = 2, },
		[16] = { auraRadiusInc = 36, coldResist = 37, coldResistMax = 2, },
		[17] = { auraRadiusInc = 37, coldResist = 38, coldResistMax = 3, },
		[18] = { auraRadiusInc = 38, coldResist = 39, coldResistMax = 3, },
		[19] = { auraRadiusInc = 39, coldResist = 40, coldResistMax = 3, },
		[20] = { auraRadiusInc = 40, coldResist = 41, coldResistMax = 4, },
		[21] = { auraRadiusInc = 41, coldResist = 42, coldResistMax = 4, },
		[22] = { auraRadiusInc = 42, coldResist = 43, coldResistMax = 4, },
		[23] = { auraRadiusInc = 43, coldResist = 44, coldResistMax = 5, },
		[24] = { auraRadiusInc = 44, coldResist = 45, coldResistMax = 5, },
		[25] = { auraRadiusInc = 45, coldResist = 46, coldResistMax = 5, },
		[26] = { auraRadiusInc = 46, coldResist = 47, coldResistMax = 5, },
		[27] = { auraRadiusInc = 47, coldResist = 48, coldResistMax = 5, },
		[28] = { auraRadiusInc = 48, coldResist = 49, coldResistMax = 5, },
		[29] = { auraRadiusInc = 49, coldResist = 50, coldResistMax = 5, },
		[30] = { auraRadiusInc = 50, coldResist = 51, coldResistMax = 5, },
	}
}
gems["Rain of Arrows"] = {
	attack = true,
	bow = true,
	projectile = true,
	aoe = true,
	base = {
	},
	quality = {
		aoeRadiusInc = 0.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 7, attack_damageMore = 1.1, aoeRadiusInc = 0, },
		[2] = { skill_manaCostBase = 7, attack_damageMore = 1.11, aoeRadiusInc = 1, },
		[3] = { skill_manaCostBase = 7, attack_damageMore = 1.12, aoeRadiusInc = 2, },
		[4] = { skill_manaCostBase = 8, attack_damageMore = 1.13, aoeRadiusInc = 3, },
		[5] = { skill_manaCostBase = 8, attack_damageMore = 1.14, aoeRadiusInc = 4, },
		[6] = { skill_manaCostBase = 8, attack_damageMore = 1.15, aoeRadiusInc = 5, },
		[7] = { skill_manaCostBase = 8, attack_damageMore = 1.16, aoeRadiusInc = 6, },
		[8] = { skill_manaCostBase = 8, attack_damageMore = 1.17, aoeRadiusInc = 7, },
		[9] = { skill_manaCostBase = 9, attack_damageMore = 1.18, aoeRadiusInc = 8, },
		[10] = { skill_manaCostBase = 9, attack_damageMore = 1.19, aoeRadiusInc = 9, },
		[11] = { skill_manaCostBase = 9, attack_damageMore = 1.2, aoeRadiusInc = 10, },
		[12] = { skill_manaCostBase = 9, attack_damageMore = 1.21, aoeRadiusInc = 11, },
		[13] = { skill_manaCostBase = 9, attack_damageMore = 1.22, aoeRadiusInc = 12, },
		[14] = { skill_manaCostBase = 10, attack_damageMore = 1.23, aoeRadiusInc = 13, },
		[15] = { skill_manaCostBase = 10, attack_damageMore = 1.24, aoeRadiusInc = 14, },
		[16] = { skill_manaCostBase = 10, attack_damageMore = 1.25, aoeRadiusInc = 15, },
		[17] = { skill_manaCostBase = 10, attack_damageMore = 1.26, aoeRadiusInc = 16, },
		[18] = { skill_manaCostBase = 10, attack_damageMore = 1.27, aoeRadiusInc = 17, },
		[19] = { skill_manaCostBase = 11, attack_damageMore = 1.28, aoeRadiusInc = 18, },
		[20] = { skill_manaCostBase = 11, attack_damageMore = 1.29, aoeRadiusInc = 19, },
		[21] = { skill_manaCostBase = 11, attack_damageMore = 1.3, aoeRadiusInc = 20, },
		[22] = { skill_manaCostBase = 11, attack_damageMore = 1.31, aoeRadiusInc = 21, },
		[23] = { skill_manaCostBase = 11, attack_damageMore = 1.32, aoeRadiusInc = 22, },
		[24] = { skill_manaCostBase = 11, attack_damageMore = 1.33, aoeRadiusInc = 23, },
		[25] = { skill_manaCostBase = 11, attack_damageMore = 1.34, aoeRadiusInc = 24, },
		[26] = { skill_manaCostBase = 12, attack_damageMore = 1.35, aoeRadiusInc = 25, },
		[27] = { skill_manaCostBase = 12, attack_damageMore = 1.36, aoeRadiusInc = 26, },
		[28] = { skill_manaCostBase = 12, attack_damageMore = 1.37, aoeRadiusInc = 27, },
		[29] = { skill_manaCostBase = 12, attack_damageMore = 1.38, aoeRadiusInc = 28, },
		[30] = { skill_manaCostBase = 12, attack_damageMore = 1.39, aoeRadiusInc = 29, },
	}
}
gems["Reave"] = {
	attack = true,
	melee = true,
	aoe = true,
	base = {
		skill_manaCostBase = 6,
	},
	quality = {
		attackSpeedInc = 0.5,
	},
	levels = {
		[1] = { attack_damageMore = 1, },
		[2] = { attack_damageMore = 1.012, },
		[3] = { attack_damageMore = 1.024, },
		[4] = { attack_damageMore = 1.036, },
		[5] = { attack_damageMore = 1.048, },
		[6] = { attack_damageMore = 1.06, },
		[7] = { attack_damageMore = 1.072, },
		[8] = { attack_damageMore = 1.084, },
		[9] = { attack_damageMore = 1.096, },
		[10] = { attack_damageMore = 1.108, },
		[11] = { attack_damageMore = 1.12, },
		[12] = { attack_damageMore = 1.132, },
		[13] = { attack_damageMore = 1.144, },
		[14] = { attack_damageMore = 1.156, },
		[15] = { attack_damageMore = 1.168, },
		[16] = { attack_damageMore = 1.18, },
		[17] = { attack_damageMore = 1.192, },
		[18] = { attack_damageMore = 1.204, },
		[19] = { attack_damageMore = 1.216, },
		[20] = { attack_damageMore = 1.228, },
		[21] = { attack_damageMore = 1.24, },
		[22] = { attack_damageMore = 1.252, },
		[23] = { attack_damageMore = 1.264, },
		[24] = { attack_damageMore = 1.276, },
		[25] = { attack_damageMore = 1.288, },
		[26] = { attack_damageMore = 1.3, },
		[27] = { attack_damageMore = 1.312, },
		[28] = { attack_damageMore = 1.324, },
		[29] = { attack_damageMore = 1.336, },
		[30] = { attack_damageMore = 1.348, },
	}
}
gems["Riposte"] = {
	unsupported = true,
}
gems["Shrapnel Shot"] = {
	attack = true,
	bow = true,
	projectile = true,
	aoe = true,
	lightning = true,
	parts = {
		{
			name = "Arrow",
			aoe = false,
		},
		{
			name = "Cone",
			aoe = true,
		},
	},
	base = {
		pierceChance = 100,
		physicalConvertTolightning = 40,
	},
	quality = {
		aoeRadiusInc = 0.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 6, attack_damageMore = 0.8, },
		[2] = { skill_manaCostBase = 6, attack_damageMore = 0.81, },
		[3] = { skill_manaCostBase = 6, attack_damageMore = 0.82, },
		[4] = { skill_manaCostBase = 7, attack_damageMore = 0.83, },
		[5] = { skill_manaCostBase = 7, attack_damageMore = 0.84, },
		[6] = { skill_manaCostBase = 7, attack_damageMore = 0.85, },
		[7] = { skill_manaCostBase = 7, attack_damageMore = 0.86, },
		[8] = { skill_manaCostBase = 8, attack_damageMore = 0.87, },
		[9] = { skill_manaCostBase = 8, attack_damageMore = 0.88, },
		[10] = { skill_manaCostBase = 8, attack_damageMore = 0.89, },
		[11] = { skill_manaCostBase = 8, attack_damageMore = 0.9, },
		[12] = { skill_manaCostBase = 8, attack_damageMore = 0.91, },
		[13] = { skill_manaCostBase = 9, attack_damageMore = 0.92, },
		[14] = { skill_manaCostBase = 9, attack_damageMore = 0.93, },
		[15] = { skill_manaCostBase = 9, attack_damageMore = 0.94, },
		[16] = { skill_manaCostBase = 9, attack_damageMore = 0.95, },
		[17] = { skill_manaCostBase = 9, attack_damageMore = 0.96, },
		[18] = { skill_manaCostBase = 10, attack_damageMore = 0.97, },
		[19] = { skill_manaCostBase = 10, attack_damageMore = 0.98, },
		[20] = { skill_manaCostBase = 10, attack_damageMore = 0.99, },
		[21] = { skill_manaCostBase = 10, attack_damageMore = 1, },
		[22] = { skill_manaCostBase = 10, attack_damageMore = 1.01, },
		[23] = { skill_manaCostBase = 11, attack_damageMore = 1.02, },
		[24] = { skill_manaCostBase = 11, attack_damageMore = 1.03, },
		[25] = { skill_manaCostBase = 11, attack_damageMore = 1.04, },
		[26] = { skill_manaCostBase = 11, attack_damageMore = 1.05, },
		[27] = { skill_manaCostBase = 11, attack_damageMore = 1.06, },
		[28] = { skill_manaCostBase = 12, attack_damageMore = 1.07, },
		[29] = { skill_manaCostBase = 12, attack_damageMore = 1.08, },
		[30] = { skill_manaCostBase = 12, attack_damageMore = 1.09, },
	}
}
gems["Siege Ballista"] = {
	attack = true,
	totem = true,
	bow = true,
	projectile = true,
	duration = true,
	base = {
		skill_durationBase = 8,
		pierceChance = 100,
		attackSpeedMore = 0.5,
	},
	quality = {
		totemPlacementSpeedInc = 1,
	},
	levels = {
		[1] = { skill_manaCostBase = 8, attack_damageMore = 1.4, },
		[2] = { skill_manaCostBase = 8, attack_damageMore = 1.416, },
		[3] = { skill_manaCostBase = 8, attack_damageMore = 1.432, },
		[4] = { skill_manaCostBase = 9, attack_damageMore = 1.448, },
		[5] = { skill_manaCostBase = 9, attack_damageMore = 1.464, },
		[6] = { skill_manaCostBase = 9, attack_damageMore = 1.48, },
		[7] = { skill_manaCostBase = 9, attack_damageMore = 1.496, },
		[8] = { skill_manaCostBase = 9, attack_damageMore = 1.512, },
		[9] = { skill_manaCostBase = 9, attack_damageMore = 1.528, },
		[10] = { skill_manaCostBase = 10, attack_damageMore = 1.544, },
		[11] = { skill_manaCostBase = 10, attack_damageMore = 1.56, },
		[12] = { skill_manaCostBase = 10, attack_damageMore = 1.576, },
		[13] = { skill_manaCostBase = 10, attack_damageMore = 1.592, },
		[14] = { skill_manaCostBase = 10, attack_damageMore = 1.608, },
		[15] = { skill_manaCostBase = 11, attack_damageMore = 1.624, },
		[16] = { skill_manaCostBase = 11, attack_damageMore = 1.64, },
		[17] = { skill_manaCostBase = 12, attack_damageMore = 1.656, },
		[18] = { skill_manaCostBase = 12, attack_damageMore = 1.672, },
		[19] = { skill_manaCostBase = 12, attack_damageMore = 1.688, },
		[20] = { skill_manaCostBase = 13, attack_damageMore = 1.704, },
		[21] = { skill_manaCostBase = 13, attack_damageMore = 1.72, },
		[22] = { skill_manaCostBase = 13, attack_damageMore = 1.736, },
		[23] = { skill_manaCostBase = 14, attack_damageMore = 1.752, },
		[24] = { skill_manaCostBase = 14, attack_damageMore = 1.768, },
		[25] = { skill_manaCostBase = 14, attack_damageMore = 1.784, },
		[26] = { skill_manaCostBase = 14, attack_damageMore = 1.8, },
		[27] = { skill_manaCostBase = 14, attack_damageMore = 1.816, },
		[28] = { skill_manaCostBase = 14, attack_damageMore = 1.832, },
		[29] = { skill_manaCostBase = 15, attack_damageMore = 1.848, },
		[30] = { skill_manaCostBase = 15, attack_damageMore = 1.864, },
	}
}
gems["Smoke Mine"] = {
	unsupported = true,
}
gems["Spectral Throw"] = {
	attack = true,
	projectile = true,
	base = {
		pierceChance = 100,
	},
	quality = {
		attackSpeedInc = 0.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 7, attack_damageMore = 0.54, },
		[2] = { skill_manaCostBase = 7, attack_damageMore = 0.56, },
		[3] = { skill_manaCostBase = 7, attack_damageMore = 0.579, },
		[4] = { skill_manaCostBase = 7, attack_damageMore = 0.598, },
		[5] = { skill_manaCostBase = 7, attack_damageMore = 0.617, },
		[6] = { skill_manaCostBase = 7, attack_damageMore = 0.636, },
		[7] = { skill_manaCostBase = 7, attack_damageMore = 0.656, },
		[8] = { skill_manaCostBase = 7, attack_damageMore = 0.675, },
		[9] = { skill_manaCostBase = 7, attack_damageMore = 0.694, },
		[10] = { skill_manaCostBase = 7, attack_damageMore = 0.713, },
		[11] = { skill_manaCostBase = 8, attack_damageMore = 0.732, },
		[12] = { skill_manaCostBase = 8, attack_damageMore = 0.752, },
		[13] = { skill_manaCostBase = 8, attack_damageMore = 0.771, },
		[14] = { skill_manaCostBase = 8, attack_damageMore = 0.79, },
		[15] = { skill_manaCostBase = 8, attack_damageMore = 0.809, },
		[16] = { skill_manaCostBase = 9, attack_damageMore = 0.828, },
		[17] = { skill_manaCostBase = 9, attack_damageMore = 0.848, },
		[18] = { skill_manaCostBase = 9, attack_damageMore = 0.867, },
		[19] = { skill_manaCostBase = 9, attack_damageMore = 0.886, },
		[20] = { skill_manaCostBase = 9, attack_damageMore = 0.905, },
		[21] = { skill_manaCostBase = 10, attack_damageMore = 0.924, },
		[22] = { skill_manaCostBase = 10, attack_damageMore = 0.944, },
		[23] = { skill_manaCostBase = 10, attack_damageMore = 0.963, },
		[24] = { skill_manaCostBase = 10, attack_damageMore = 0.982, },
		[25] = { skill_manaCostBase = 10, attack_damageMore = 1, },
		[26] = { skill_manaCostBase = 10, attack_damageMore = 1.02, },
		[27] = { skill_manaCostBase = 10, attack_damageMore = 1.039, },
		[28] = { skill_manaCostBase = 10, attack_damageMore = 1.058, },
		[29] = { skill_manaCostBase = 10, attack_damageMore = 1.077, },
		[30] = { skill_manaCostBase = 10, attack_damageMore = 1.096, },
	}
}
gems["Split Arrow"] = {
	attack = true,
	bow = true,
	projectile = true,
	base = {
	},
	quality = {
		attackSpeedInc = 0.5,
	},
	levels = {
		[1] = { skill_manaCostBase = 6, attack_damageMore = 0.9, },
		[2] = { skill_manaCostBase = 6, attack_damageMore = 0.91, },
		[3] = { skill_manaCostBase = 6, attack_damageMore = 0.92, },
		[4] = { skill_manaCostBase = 7, attack_damageMore = 0.93, },
		[5] = { skill_manaCostBase = 7, attack_damageMore = 0.94, },
		[6] = { skill_manaCostBase = 7, attack_damageMore = 0.95, },
		[7] = { skill_manaCostBase = 7, attack_damageMore = 0.96, },
		[8] = { skill_manaCostBase = 8, attack_damageMore = 0.97, },
		[9] = { skill_manaCostBase = 8, attack_damageMore = 0.98, },
		[10] = { skill_manaCostBase = 8, attack_damageMore = 0.99, },
		[11] = { skill_manaCostBase = 8, attack_damageMore = 1, },
		[12] = { skill_manaCostBase = 8, attack_damageMore = 1.01, },
		[13] = { skill_manaCostBase = 9, attack_damageMore = 1.02, },
		[14] = { skill_manaCostBase = 9, attack_damageMore = 1.03, },
		[15] = { skill_manaCostBase = 9, attack_damageMore = 1.04, },
		[16] = { skill_manaCostBase = 9, attack_damageMore = 1.05, },
		[17] = { skill_manaCostBase = 9, attack_damageMore = 1.06, },
		[18] = { skill_manaCostBase = 10, attack_damageMore = 1.07, },
		[19] = { skill_manaCostBase = 10, attack_damageMore = 1.08, },
		[20] = { skill_manaCostBase = 10, attack_damageMore = 1.09, },
		[21] = { skill_manaCostBase = 10, attack_damageMore = 1.1, },
		[22] = { skill_manaCostBase = 10, attack_damageMore = 1.11, },
		[23] = { skill_manaCostBase = 11, attack_damageMore = 1.12, },
		[24] = { skill_manaCostBase = 11, attack_damageMore = 1.13, },
		[25] = { skill_manaCostBase = 11, attack_damageMore = 1.14, },
		[26] = { skill_manaCostBase = 11, attack_damageMore = 1.15, },
		[27] = { skill_manaCostBase = 11, attack_damageMore = 1.16, },
		[28] = { skill_manaCostBase = 12, attack_damageMore = 1.17, },
		[29] = { skill_manaCostBase = 12, attack_damageMore = 1.18, },
		[30] = { skill_manaCostBase = 12, attack_damageMore = 1.19, },
	}
}
gems["Summon Ice Golem"] = {
	spell = true,
	minion = true,
	golem = true,
	cold = true,
	base = {
		skill_castTime = 1,
	},
	quality = {
		minionLifeInc = 1,
		minion_damageInc = 1,
	},
	levels = {
		[1] = { skill_manaCostBase = 30, minionLifeInc = 30, buff_critChanceInc = 20, buff_accuracyInc = 20, },
		[2] = { skill_manaCostBase = 32, minionLifeInc = 32, buff_critChanceInc = 21, buff_accuracyInc = 21, },
		[3] = { skill_manaCostBase = 34, minionLifeInc = 34, buff_critChanceInc = 21, buff_accuracyInc = 21, },
		[4] = { skill_manaCostBase = 36, minionLifeInc = 36, buff_critChanceInc = 22, buff_accuracyInc = 22, },
		[5] = { skill_manaCostBase = 38, minionLifeInc = 38, buff_critChanceInc = 22, buff_accuracyInc = 22, },
		[6] = { skill_manaCostBase = 40, minionLifeInc = 40, buff_critChanceInc = 23, buff_accuracyInc = 23, },
		[7] = { skill_manaCostBase = 42, minionLifeInc = 42, buff_critChanceInc = 23, buff_accuracyInc = 23, },
		[8] = { skill_manaCostBase = 44, minionLifeInc = 44, buff_critChanceInc = 24, buff_accuracyInc = 24, },
		[9] = { skill_manaCostBase = 44, minionLifeInc = 46, buff_critChanceInc = 24, buff_accuracyInc = 24, },
		[10] = { skill_manaCostBase = 46, minionLifeInc = 48, buff_critChanceInc = 25, buff_accuracyInc = 25, },
		[11] = { skill_manaCostBase = 48, minionLifeInc = 50, buff_critChanceInc = 25, buff_accuracyInc = 25, },
		[12] = { skill_manaCostBase = 48, minionLifeInc = 52, buff_critChanceInc = 26, buff_accuracyInc = 26, },
		[13] = { skill_manaCostBase = 50, minionLifeInc = 54, buff_critChanceInc = 26, buff_accuracyInc = 26, },
		[14] = { skill_manaCostBase = 50, minionLifeInc = 56, buff_critChanceInc = 27, buff_accuracyInc = 27, },
		[15] = { skill_manaCostBase = 52, minionLifeInc = 58, buff_critChanceInc = 27, buff_accuracyInc = 27, },
		[16] = { skill_manaCostBase = 52, minionLifeInc = 60, buff_critChanceInc = 28, buff_accuracyInc = 28, },
		[17] = { skill_manaCostBase = 52, minionLifeInc = 62, buff_critChanceInc = 28, buff_accuracyInc = 28, },
		[18] = { skill_manaCostBase = 52, minionLifeInc = 64, buff_critChanceInc = 29, buff_accuracyInc = 29, },
		[19] = { skill_manaCostBase = 54, minionLifeInc = 66, buff_critChanceInc = 29, buff_accuracyInc = 29, },
		[20] = { skill_manaCostBase = 54, minionLifeInc = 68, buff_critChanceInc = 30, buff_accuracyInc = 30, },
		[21] = { skill_manaCostBase = 56, minionLifeInc = 70, buff_critChanceInc = 30, buff_accuracyInc = 30, },
		[22] = { skill_manaCostBase = 56, minionLifeInc = 72, buff_critChanceInc = 31, buff_accuracyInc = 31, },
		[23] = { skill_manaCostBase = 58, minionLifeInc = 74, buff_critChanceInc = 31, buff_accuracyInc = 31, },
		[24] = { skill_manaCostBase = 58, minionLifeInc = 76, buff_critChanceInc = 32, buff_accuracyInc = 32, },
		[25] = { skill_manaCostBase = 60, minionLifeInc = 78, buff_critChanceInc = 32, buff_accuracyInc = 32, },
		[26] = { skill_manaCostBase = 60, minionLifeInc = 80, buff_critChanceInc = 33, buff_accuracyInc = 33, },
		[27] = { skill_manaCostBase = 60, minionLifeInc = 82, buff_critChanceInc = 33, buff_accuracyInc = 33, },
		[28] = { skill_manaCostBase = 60, minionLifeInc = 84, buff_critChanceInc = 34, buff_accuracyInc = 34, },
		[29] = { skill_manaCostBase = 62, minionLifeInc = 86, buff_critChanceInc = 34, buff_accuracyInc = 34, },
		[30] = { skill_manaCostBase = 62, minionLifeInc = 88, buff_critChanceInc = 35, buff_accuracyInc = 35, },
	}
}
gems["Temporal Chains"] = {
	unsupported = true,
}
gems["Tornado Shot"] = {
	attack = true,
	bow = true,
	projectile = true,
	base = {
	},
	quality = {
		projectile_damageInc = 1,
	},
	levels = {
		[1] = { skill_manaCostBase = 8, attack_damageMore = 0.9, },
		[2] = { skill_manaCostBase = 8, attack_damageMore = 0.91, },
		[3] = { skill_manaCostBase = 8, attack_damageMore = 0.92, },
		[4] = { skill_manaCostBase = 8, attack_damageMore = 0.93, },
		[5] = { skill_manaCostBase = 9, attack_damageMore = 0.94, },
		[6] = { skill_manaCostBase = 9, attack_damageMore = 0.95, },
		[7] = { skill_manaCostBase = 9, attack_damageMore = 0.96, },
		[8] = { skill_manaCostBase = 9, attack_damageMore = 0.97, },
		[9] = { skill_manaCostBase = 9, attack_damageMore = 0.98, },
		[10] = { skill_manaCostBase = 9, attack_damageMore = 0.99, },
		[11] = { skill_manaCostBase = 9, attack_damageMore = 1, },
		[12] = { skill_manaCostBase = 10, attack_damageMore = 1.01, },
		[13] = { skill_manaCostBase = 10, attack_damageMore = 1.02, },
		[14] = { skill_manaCostBase = 10, attack_damageMore = 1.03, },
		[15] = { skill_manaCostBase = 10, attack_damageMore = 1.04, },
		[16] = { skill_manaCostBase = 10, attack_damageMore = 1.05, },
		[17] = { skill_manaCostBase = 10, attack_damageMore = 1.06, },
		[18] = { skill_manaCostBase = 10, attack_damageMore = 1.07, },
		[19] = { skill_manaCostBase = 10, attack_damageMore = 1.08, },
		[20] = { skill_manaCostBase = 10, attack_damageMore = 1.09, },
		[21] = { skill_manaCostBase = 10, attack_damageMore = 1.1, },
		[22] = { skill_manaCostBase = 10, attack_damageMore = 1.11, },
		[23] = { skill_manaCostBase = 11, attack_damageMore = 1.12, },
		[24] = { skill_manaCostBase = 11, attack_damageMore = 1.13, },
		[25] = { skill_manaCostBase = 11, attack_damageMore = 1.14, },
		[26] = { skill_manaCostBase = 11, attack_damageMore = 1.15, },
		[27] = { skill_manaCostBase = 11, attack_damageMore = 1.16, },
		[28] = { skill_manaCostBase = 12, attack_damageMore = 1.17, },
		[29] = { skill_manaCostBase = 12, attack_damageMore = 1.18, },
		[30] = { skill_manaCostBase = 12, attack_damageMore = 1.19, },
	}
}
gems["Viper Strike"] = {
	attack = true,
	melee = true,
	duration = true,
	chaos = true,
	base = {
		skill_manaCostBase = 5,
		physicalConvertTochaos = 25,
		poisonChance = 100,
		poison_durationMore = 4,
	},
	quality = {
		attackSpeedInc = 0.5
	},
	levels = {
		[1] = { attack_damageMore = 1.3, },
		[2] = { attack_damageMore = 1.316, },
		[3] = { attack_damageMore = 1.332, },
		[4] = { attack_damageMore = 1.348, },
		[5] = { attack_damageMore = 1.364, },
		[6] = { attack_damageMore = 1.38, },
		[7] = { attack_damageMore = 1.396, },
		[8] = { attack_damageMore = 1.412, },
		[9] = { attack_damageMore = 1.428, },
		[10] = { attack_damageMore = 1.444, },
		[11] = { attack_damageMore = 1.46, },
		[12] = { attack_damageMore = 1.476, },
		[13] = { attack_damageMore = 1.492, },
		[14] = { attack_damageMore = 1.508, },
		[15] = { attack_damageMore = 1.524, },
		[16] = { attack_damageMore = 1.54, },
		[17] = { attack_damageMore = 1.556, },
		[18] = { attack_damageMore = 1.572, },
		[19] = { attack_damageMore = 1.588, },
		[20] = { attack_damageMore = 1.604, },
		[21] = { attack_damageMore = 1.62, },
		[22] = { attack_damageMore = 1.636, },
		[23] = { attack_damageMore = 1.652, },
		[24] = { attack_damageMore = 1.668, },
		[25] = { attack_damageMore = 1.684, },
		[26] = { attack_damageMore = 1.7, },
		[27] = { attack_damageMore = 1.716, },
		[28] = { attack_damageMore = 1.732, },
		[29] = { attack_damageMore = 1.748, },
		[30] = { attack_damageMore = 1.764, },
	}
}
gems["Whirling Blades"] = {
	unsupported = true,
}
gems["Wild Strike"] = {
	attack = true,
	melee = true,
	projectile = true,
	aoe = true,
	lightning = true,
	cold = true,
	fire = true,
	parts = {
		{
			name = "Fire hit",
			melee = true,
			projectile = false,
			aoe = false,
		},
		{
			name = "Fire explosion",
			melee = false,
			projectile = false,
			aoe = true,
		},
		{
			name = "Lightning hit",
			melee = true,
			projectile = false,
			aoe = false,
		},
		{
			name = "Lightning bolt",
			melee = false,
			projectile = false,
			aoe = false,
		},
		{
			name = "Cold hit",
			melee = true,
			projectile = false,
			aoe = false,
		},
		{
			name = "Icy wave",
			melee = false,
			projectile = true,
			aoe = false,
		},
	},
	base = {
		skill_manaCostBase = 6,
		part1_physicalConvertTofire = 60,
		part2_physicalConvertTofire = 60,
		part3_physicalConvertTolightning = 60,
		part4_physicalConvertTolightning = 60,
		part5_physicalGainAscold = 60,
		part6_physicalGainAscold = 60,
	},
	quality = {
		elementalInc = 1,
	},
	levels = {
		[1] = { attack_damageMore = 1.2, },
		[2] = { attack_damageMore = 1.214, },
		[3] = { attack_damageMore = 1.228, },
		[4] = { attack_damageMore = 1.242, },
		[5] = { attack_damageMore = 1.256, },
		[6] = { attack_damageMore = 1.27, },
		[7] = { attack_damageMore = 1.284, },
		[8] = { attack_damageMore = 1.298, },
		[9] = { attack_damageMore = 1.312, },
		[10] = { attack_damageMore = 1.326, },
		[11] = { attack_damageMore = 1.34, },
		[12] = { attack_damageMore = 1.354, },
		[13] = { attack_damageMore = 1.368, },
		[14] = { attack_damageMore = 1.382, },
		[15] = { attack_damageMore = 1.396, },
		[16] = { attack_damageMore = 1.41, },
		[17] = { attack_damageMore = 1.424, },
		[18] = { attack_damageMore = 1.438, },
		[19] = { attack_damageMore = 1.452, },
		[20] = { attack_damageMore = 1.466, },
		[21] = { attack_damageMore = 1.48, },
		[22] = { attack_damageMore = 1.494, },
		[23] = { attack_damageMore = 1.508, },
		[24] = { attack_damageMore = 1.522, },
		[25] = { attack_damageMore = 1.536, },
		[26] = { attack_damageMore = 1.55, },
		[27] = { attack_damageMore = 1.564, },
		[28] = { attack_damageMore = 1.578, },
		[29] = { attack_damageMore = 1.592, },
		[30] = { attack_damageMore = 1.606, },
	}
}


