return  {
	["keystoneActive"]={{
		["filename"]="skills-additional-3.jpg",
		["coords"]={
			["Art/2DArt/SkillIcons/passives/DivineFlesh.dds"]={["x"]=0,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/EternalYouth.dds"]={["x"]=53,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/CorruptedDefences.dds"]={["x"]=106,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/SoulTetherKeystone.dds"]={["x"]=54,["y"]=119,["w"]=54,["h"]=54},

			["Art/2DArt/SkillIcons/passives/StrengthOfBlood.dds"]={["x"]=159,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/GlancingBlows.dds"]={["x"]=265,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/TemperedByWar.dds"]={["x"]=212,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/FocusedRage.dds"]={["x"]=0,["y"]=119,["w"]=54,["h"]=54},

			["Art/2DArt/SkillIcons/passives/WindDancer.dds"]={["x"]=318,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/SharpandBrittle.dds"]={["x"]=371,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/TheBlindMonk.dds"]={["x"]=424,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/OasisKeystone.dds"]={["x"]=108,["y"]=119,["w"]=54,["h"]=54},

			["Art/2DArt/SkillIcons/passives/MiracleMaker.dds"]={["x"]=477,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/InnerConviction.dds"]={["x"]=530,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/PowerOfPurpose.dds"]={["x"]=583,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/TranscendenceKeystone.dds"]={["x"]=162,["y"]=119,["w"]=54,["h"]=54},

			["Art/2DArt/SkillIcons/passives/SupremeDecadence.dds"]={["x"]=636,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/SupremeGrandstand.dds"]={["x"]=689,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/SupremeEgo.dds"]={["x"]=742,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/SupremeProdigy.dds"]={["x"]=216,["y"]=119,["w"]=54,["h"]=54},
		}
		}
	},
	["keystoneInactive"]={{
		["filename"]="skills-additional-disabled-3.jpg",
		["coords"]={
			["Art/2DArt/SkillIcons/passives/DivineFlesh.dds"]={["x"]=0,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/EternalYouth.dds"]={["x"]=53,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/CorruptedDefences.dds"]={["x"]=106,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/SoulTetherKeystone.dds"]={["x"]=54,["y"]=119,["w"]=54,["h"]=54},

			["Art/2DArt/SkillIcons/passives/StrengthOfBlood.dds"]={["x"]=159,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/GlancingBlows.dds"]={["x"]=265,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/TemperedByWar.dds"]={["x"]=212,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/FocusedRage.dds"]={["x"]=0,["y"]=119,["w"]=54,["h"]=54},

			["Art/2DArt/SkillIcons/passives/WindDancer.dds"]={["x"]=318,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/SharpandBrittle.dds"]={["x"]=371,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/TheBlindMonk.dds"]={["x"]=424,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/OasisKeystone.dds"]={["x"]=108,["y"]=119,["w"]=54,["h"]=54},

			["Art/2DArt/SkillIcons/passives/MiracleMaker.dds"]={["x"]=477,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/InnerConviction.dds"]={["x"]=530,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/PowerOfPurpose.dds"]={["x"]=583,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/TranscendenceKeystone.dds"]={["x"]=162,["y"]=119,["w"]=54,["h"]=54},

			["Art/2DArt/SkillIcons/passives/SupremeDecadence.dds"]={["x"]=636,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/SupremeGrandstand.dds"]={["x"]=689,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/SupremeEgo.dds"]={["x"]=742,["y"]=65,["w"]=53,["h"]=54},
			["Art/2DArt/SkillIcons/passives/SupremeProdigy.dds"]={["x"]=216,["y"]=119,["w"]=54,["h"]=54},
		}
		}
	},
	["notableActive"]={{
		["filename"]="skills-additional-3.jpg",
		["coords"]={
			["Art/2DArt/SkillIcons/passives/VaalNotableOffensive.dds"]={["x"]=0,["y"]=27,["w"]=38,["h"]=38},
			["Art/2DArt/SkillIcons/passives/VaalNotableDefensive.dds"]={["x"]=38,["y"]=27,["w"]=38,["h"]=38},
			["Art/2DArt/SkillIcons/passives/DevotionNotable.dds"]={["x"]=76,["y"]=27,["w"]=38,["h"]=38},
			["Art/2DArt/SkillIcons/passives/EternalEmpireOffensiveNotable.dds"]={["x"]=114,["y"]=27,["w"]=38,["h"]=38},
			["Art/2DArt/SkillIcons/passives/EternalEmpireDefensiveNotable.dds"]={["x"]=152,["y"]=27,["w"]=38,["h"]=38},
		}
	}
	},
	["notableInactive"]={{
		["filename"]="skills-additional-disabled-3.jpg",
		["coords"]={
			["Art/2DArt/SkillIcons/passives/VaalNotableOffensive.dds"]={["x"]=0,["y"]=27,["w"]=38,["h"]=38},
			["Art/2DArt/SkillIcons/passives/VaalNotableDefensive.dds"]={["x"]=38,["y"]=27,["w"]=38,["h"]=38},
			["Art/2DArt/SkillIcons/passives/DevotionNotable.dds"]={["x"]=76,["y"]=27,["w"]=38,["h"]=38},
			["Art/2DArt/SkillIcons/passives/EternalEmpireOffensiveNotable.dds"]={["x"]=114,["y"]=27,["w"]=38,["h"]=38},
			["Art/2DArt/SkillIcons/passives/EternalEmpireDefensiveNotable.dds"]={["x"]=152,["y"]=27,["w"]=38,["h"]=38},
		}
	}
	},
	["normalActive"]={{
		["filename"]="skills-additional-3.jpg",
		["coords"]={
			["Art/2DArt/SkillIcons/passives/VaalOffensive.dds"]={["x"]=0,["y"]=0,["w"]=27,["h"]=27},
			["Art/2DArt/SkillIcons/passives/VaalDefensive.dds"]={["x"]=27,["y"]=0,["w"]=27,["h"]=27},
			["Art/2DArt/SkillIcons/passives/DevotionNode.dds"]={["x"]=54,["y"]=0,["w"]=27,["h"]=27},
			["Art/2DArt/SkillIcons/passives/EternalEmpireBlank.dds"]={["x"]=81,["y"]=0,["w"]=27,["h"]=27},
		}
	}
	},
	["normalInactive"]={{
		["filename"]="skills-additional-disabled-3.jpg",
		["coords"]={
			["Art/2DArt/SkillIcons/passives/VaalOffensive.dds"]={["x"]=0,["y"]=0,["w"]=27,["h"]=27},
			["Art/2DArt/SkillIcons/passives/VaalDefensive.dds"]={["x"]=27,["y"]=0,["w"]=27,["h"]=27},
			["Art/2DArt/SkillIcons/passives/DevotionNode.dds"]={["x"]=54,["y"]=0,["w"]=27,["h"]=27},
			["Art/2DArt/SkillIcons/passives/EternalEmpireBlank.dds"]={["x"]=81,["y"]=0,["w"]=27,["h"]=27},
		}
	}
	},
}