-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Glove enchantment skills
-- Skill data (c) Grinding Gear Games
--
local skills, mod, flag, skill = ...

skills["EnchantmentOfBladesOnHit"] = {
	name = "Word of Blades",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.7000000476837,
	incrementalEffectiveness = 0.037000000476837,
	description = "Fires a chaining burst of ethereal blades.",
	skillTypes = { ["Spell"] = true, ["Projectile"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["ProjectilesFromUser"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"number_of_chains",
		"cast_on_hit_%",
		"skill_art_variation",
		"number_of_additional_projectiles",
		"base_is_projectile",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1, 126, 3, 100, 0, 2, critChance = 7, cooldown = 5, levelRequirement = 32, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfBladesOnHit2"] = {
	name = "Edict of Blades",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.7000000476837,
	incrementalEffectiveness = 0.037000000476837,
	description = "Fires a chaining burst of ethereal blades.",
	skillTypes = { ["Spell"] = true, ["Projectile"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["ProjectilesFromUser"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"number_of_chains",
		"cast_on_hit_%",
		"skill_art_variation",
		"number_of_additional_projectiles",
		"base_is_projectile",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1.5, 585, 3, 100, 0, 2, critChance = 7, cooldown = 5, levelRequirement = 53, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfBladesOnHit3"] = {
	name = "Decree of Blades",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.7000000476837,
	incrementalEffectiveness = 0.037000000476837,
	description = "Fires a chaining burst of ethereal blades.",
	skillTypes = { ["Spell"] = true, ["Projectile"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["ProjectilesFromUser"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"number_of_chains",
		"cast_on_hit_%",
		"skill_art_variation",
		"number_of_additional_projectiles",
		"base_is_projectile",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2, 1477, 3, 100, 0, 2, critChance = 7, cooldown = 5, levelRequirement = 66, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfBladesOnHit4"] = {
	name = "Commandment of Blades",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.7000000476837,
	incrementalEffectiveness = 0.037000000476837,
	description = "Fires a chaining burst of ethereal blades.",
	skillTypes = { ["Spell"] = true, ["Projectile"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["ProjectilesFromUser"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"number_of_chains",
		"cast_on_hit_%",
		"skill_art_variation",
		"number_of_additional_projectiles",
		"base_is_projectile",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2.4000000953674, 2903, 4, 100, 0, 2, critChance = 7, cooldown = 5, levelRequirement = 75, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfFlamesOnHit"] = {
	name = "Word of Flames",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.7777999639511,
	incrementalEffectiveness = 0.035000000149012,
	description = "Releases a nova of fire around you, damaging nearby enemies.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["Damage"] = true, ["Fire"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"cast_on_hit_%",
		"is_area_damage",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1.2000000476837, 140, 100, critChance = 5, cooldown = 5, levelRequirement = 32, statInterpolation = { 3, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfFlamesOnHit2"] = {
	name = "Edict of Flames",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.7777999639511,
	incrementalEffectiveness = 0.035000000149012,
	description = "Releases a nova of fire around you, damaging nearby enemies.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["Damage"] = true, ["Fire"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"cast_on_hit_%",
		"is_area_damage",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1.7000000476837, 601, 100, critChance = 5, cooldown = 5, levelRequirement = 53, statInterpolation = { 3, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfFlamesOnHit3"] = {
	name = "Decree of Flames",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.7777999639511,
	incrementalEffectiveness = 0.035000000149012,
	description = "Releases a nova of fire around you, damaging nearby enemies.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["Damage"] = true, ["Fire"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"cast_on_hit_%",
		"is_area_damage",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2.2000000476837, 1453, 100, critChance = 5, cooldown = 5, levelRequirement = 66, statInterpolation = { 3, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfFlamesOnHit4"] = {
	name = "Commandment of Flames",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.7777999639511,
	incrementalEffectiveness = 0.035000000149012,
	description = "Releases a nova of fire around you, damaging nearby enemies.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["Damage"] = true, ["Fire"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"cast_on_hit_%",
		"is_area_damage",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2.5999999046326, 2770, 100, critChance = 5, cooldown = 5, levelRequirement = 75, statInterpolation = { 3, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfForceOnHit"] = {
	name = "Word of Force",
	hidden = true,
	color = 4,
	description = "Release an arc of force from your weapon or fists, damaging enemies in front of you.",
	skillTypes = { ["Attack"] = true, ["Area"] = true, ["Damage"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"attack_trigger_on_hit_%",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 100, damageEffectiveness = 1.35, cooldown = 5, baseMultiplier = 1.35, levelRequirement = 32, statInterpolation = { 1, }, cost = { }, },
	},
}
skills["EnchantmentOfForceOnHit2"] = {
	name = "Edict of Force",
	hidden = true,
	color = 4,
	description = "Release an arc of force from your weapon or fists, damaging enemies in front of you.",
	skillTypes = { ["Attack"] = true, ["Area"] = true, ["Damage"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"attack_trigger_on_hit_%",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 100, damageEffectiveness = 1.89, cooldown = 5, baseMultiplier = 1.89, levelRequirement = 53, statInterpolation = { 1, }, cost = { }, },
	},
}
skills["EnchantmentOfForceOnHit3"] = {
	name = "Decree of Force",
	hidden = true,
	color = 4,
	description = "Release an arc of force from your weapon or fists, damaging enemies in front of you.",
	skillTypes = { ["Attack"] = true, ["Area"] = true, ["Damage"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"attack_trigger_on_hit_%",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 100, damageEffectiveness = 2.43, cooldown = 5, baseMultiplier = 2.43, levelRequirement = 66, statInterpolation = { 1, }, cost = { }, },
	},
}
skills["EnchantmentOfForceOnHit4"] = {
	name = "Commandment of Force",
	hidden = true,
	color = 4,
	description = "Release an arc of force from your weapon or fists, damaging enemies in front of you.",
	skillTypes = { ["Attack"] = true, ["Area"] = true, ["Damage"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"attack_trigger_on_hit_%",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 100, damageEffectiveness = 2.97, cooldown = 5, baseMultiplier = 2.97, levelRequirement = 75, statInterpolation = { 1, }, cost = { }, },
	},
}
skills["EnchantmentOfFrostOnKill"] = {
	name = "Word of Frost",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.6363999843597,
	incrementalEffectiveness = 0.035000000149012,
	description = "Fire icy projectiles around you in all directions.",
	skillTypes = { ["Spell"] = true, ["Projectile"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["ProjectilesFromUser"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"skill_art_variation",
		"chance_to_cast_on_kill_%_target_self",
		"number_of_additional_projectiles",
		"base_is_projectile",
		"projectiles_nova",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1, 114, 1, 100, 8, critChance = 5, cooldown = 5, levelRequirement = 32, statInterpolation = { 3, 1, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfFrostOnKill2"] = {
	name = "Edict of Frost",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.6363999843597,
	incrementalEffectiveness = 0.035000000149012,
	description = "Fire icy projectiles around you in all directions.",
	skillTypes = { ["Spell"] = true, ["Projectile"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["ProjectilesFromUser"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"skill_art_variation",
		"chance_to_cast_on_kill_%_target_self",
		"number_of_additional_projectiles",
		"base_is_projectile",
		"projectiles_nova",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1.5, 509, 1, 100, 8, critChance = 5, cooldown = 5, levelRequirement = 53, statInterpolation = { 3, 1, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfFrostOnKill3"] = {
	name = "Decree of Frost",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.6363999843597,
	incrementalEffectiveness = 0.035000000149012,
	description = "Fire icy projectiles around you in all directions.",
	skillTypes = { ["Spell"] = true, ["Projectile"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["ProjectilesFromUser"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"skill_art_variation",
		"chance_to_cast_on_kill_%_target_self",
		"number_of_additional_projectiles",
		"base_is_projectile",
		"projectiles_nova",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2, 1254, 1, 100, 8, critChance = 5, cooldown = 5, levelRequirement = 66, statInterpolation = { 3, 1, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfFrostOnKill4"] = {
	name = "Commandment of Frost",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.6363999843597,
	incrementalEffectiveness = 0.035000000149012,
	description = "Fire icy projectiles around you in all directions.",
	skillTypes = { ["Spell"] = true, ["Projectile"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["ProjectilesFromUser"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"skill_art_variation",
		"chance_to_cast_on_kill_%_target_self",
		"number_of_additional_projectiles",
		"base_is_projectile",
		"projectiles_nova",
		"spell_uncastable_if_triggerable",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2.4000000953674, 2422, 1, 100, 8, critChance = 5, cooldown = 5, levelRequirement = 75, statInterpolation = { 3, 1, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfFuryOnHit"] = {
	name = "Word of Fury",
	hidden = true,
	color = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Repeatedly fires a piercing projectile based on your weapon, converting some physical damage to fire. The projectiles form an arc in front of you.",
	skillTypes = { ["Attack"] = true, ["RangedAttack"] = true, ["Projectile"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Fire"] = true, ["ProjectilesNotFromUser"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"attack_trigger_on_hit_%",
		"projectile_spiral_nova_time_ms",
		"projectile_spiral_nova_angle",
		"base_number_of_projectiles_in_spiral_nova",
		"skill_art_variation",
		"skill_physical_damage_%_to_convert_to_fire",
		"projectile_spiral_nova_starting_angle_offset",
		"projectile_base_number_of_targets_to_pierce",
		"base_is_projectile",
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 100, 800, 180, 10, 1, 50, -90, 2, damageEffectiveness = 1.5, cooldown = 5, baseMultiplier = 1.5, levelRequirement = 32, statInterpolation = { 1, 1, 3325, 2122, 2123, 2121, 347, 1101, }, cost = { }, },
	},
}
skills["EnchantmentOfFuryOnHit2"] = {
	name = "Edict of Fury",
	hidden = true,
	color = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Repeatedly fires a piercing projectile based on your weapon, converting some physical damage to fire. The projectiles form an arc in front of you.",
	skillTypes = { ["Attack"] = true, ["RangedAttack"] = true, ["Projectile"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Fire"] = true, ["ProjectilesNotFromUser"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"attack_trigger_on_hit_%",
		"projectile_spiral_nova_time_ms",
		"projectile_spiral_nova_angle",
		"base_number_of_projectiles_in_spiral_nova",
		"skill_art_variation",
		"skill_physical_damage_%_to_convert_to_fire",
		"projectile_spiral_nova_starting_angle_offset",
		"projectile_base_number_of_targets_to_pierce",
		"base_is_projectile",
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 100, 800, 180, 10, 1, 50, -90, 3, damageEffectiveness = 2.1, cooldown = 5, baseMultiplier = 2.1, levelRequirement = 53, statInterpolation = { 1, 1, 3325, 2122, 2123, 2121, 347, 1101, }, cost = { }, },
	},
}
skills["EnchantmentOfFuryOnHit3"] = {
	name = "Decree of Fury",
	hidden = true,
	color = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Repeatedly fires a piercing projectile based on your weapon, converting some physical damage to fire. The projectiles form an arc in front of you.",
	skillTypes = { ["Attack"] = true, ["RangedAttack"] = true, ["Projectile"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Fire"] = true, ["ProjectilesNotFromUser"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"attack_trigger_on_hit_%",
		"projectile_spiral_nova_time_ms",
		"projectile_spiral_nova_angle",
		"base_number_of_projectiles_in_spiral_nova",
		"skill_art_variation",
		"skill_physical_damage_%_to_convert_to_fire",
		"projectile_spiral_nova_starting_angle_offset",
		"projectile_base_number_of_targets_to_pierce",
		"base_is_projectile",
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 100, 800, 180, 10, 1, 50, -90, 4, damageEffectiveness = 2.7, cooldown = 5, baseMultiplier = 2.7, levelRequirement = 66, statInterpolation = { 1, 1, 3325, 2122, 2123, 2121, 347, 1101, }, cost = { }, },
	},
}
skills["EnchantmentOfFuryOnHit4"] = {
	name = "Commandment of Fury",
	hidden = true,
	color = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Repeatedly fires a piercing projectile based on your weapon, converting some physical damage to fire. The projectiles form an arc in front of you.",
	skillTypes = { ["Attack"] = true, ["RangedAttack"] = true, ["Projectile"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Fire"] = true, ["ProjectilesNotFromUser"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"attack_trigger_on_hit_%",
		"projectile_spiral_nova_time_ms",
		"projectile_spiral_nova_angle",
		"base_number_of_projectiles_in_spiral_nova",
		"skill_art_variation",
		"skill_physical_damage_%_to_convert_to_fire",
		"projectile_spiral_nova_starting_angle_offset",
		"projectile_base_number_of_targets_to_pierce",
		"base_is_projectile",
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 100, 800, 180, 10, 1, 50, -90, 5, damageEffectiveness = 3.3, cooldown = 5, baseMultiplier = 3.3, levelRequirement = 75, statInterpolation = { 1, 1, 3520, 173, 2547, 347, 1102, 2, }, cost = { }, },
	},
}
skills["EnchantmentOfInfernoOnKill"] = {
	name = "Word of Inferno",
	hidden = true,
	color = 4,
	baseEffectiveness = 3.5555999279022,
	incrementalEffectiveness = 0.035000000149012,
	description = "Drops a meteor from above on a nearby foe, dealing fire damage in an area around them.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["Fire"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["AreaSpell"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"base_skill_effect_duration",
		"fire_storm_fireball_delay_ms",
		"skill_override_pvp_scaling_time_ms",
		"chance_to_cast_on_kill_%_target_self",
		"base_skill_show_average_damage_instead_of_dps",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1, 249, 2000, 100, 450, 100, critChance = 5, cooldown = 10, levelRequirement = 32, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfInfernoOnKill2"] = {
	name = "Edict of Inferno",
	hidden = true,
	color = 4,
	baseEffectiveness = 3.5555999279022,
	incrementalEffectiveness = 0.035000000149012,
	description = "Drops a meteor from above on a nearby foe, dealing fire damage in an area around them.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["Fire"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["AreaSpell"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"base_skill_effect_duration",
		"fire_storm_fireball_delay_ms",
		"skill_override_pvp_scaling_time_ms",
		"chance_to_cast_on_kill_%_target_self",
		"base_skill_show_average_damage_instead_of_dps",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1.5, 1107, 2000, 100, 450, 100, critChance = 5, cooldown = 10, levelRequirement = 53, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfInfernoOnKill3"] = {
	name = "Decree of Inferno",
	hidden = true,
	color = 4,
	baseEffectiveness = 3.5555999279022,
	incrementalEffectiveness = 0.035000000149012,
	description = "Drops a meteor from above on a nearby foe, dealing fire damage in an area around them.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["Fire"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["AreaSpell"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"base_skill_effect_duration",
		"fire_storm_fireball_delay_ms",
		"skill_override_pvp_scaling_time_ms",
		"chance_to_cast_on_kill_%_target_self",
		"base_skill_show_average_damage_instead_of_dps",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2, 2725, 2000, 100, 450, 100, critChance = 5, cooldown = 10, levelRequirement = 66, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfInfernoOnKill4"] = {
	name = "Commandment of Inferno",
	hidden = true,
	color = 4,
	baseEffectiveness = 3.5555999279022,
	incrementalEffectiveness = 0.035000000149012,
	description = "Drops a meteor from above on a nearby foe, dealing fire damage in an area around them.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["Fire"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["AreaSpell"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"base_skill_effect_duration",
		"fire_storm_fireball_delay_ms",
		"skill_override_pvp_scaling_time_ms",
		"chance_to_cast_on_kill_%_target_self",
		"base_skill_show_average_damage_instead_of_dps",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2.4000000953674, 5263, 2000, 100, 450, 100, critChance = 5, cooldown = 10, levelRequirement = 75, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfIreWhenHit"] = {
	name = "Word of Ire",
	hidden = true,
	color = 2,
	baseEffectiveness = 1.2000000476837,
	incrementalEffectiveness = 0.019999999552965,
	description = "Release a lightning charged spinning copy of your weapon or its projectiles that rotates around a point, damaging enemies in an area.",
	skillTypes = { ["Attack"] = true, ["Damage"] = true, ["Area"] = true, ["Duration"] = true, ["Totemable"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Lightning"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.5,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"extra_gore_chance_override_%",
		"melee_counterattack_trigger_on_hit_%",
		"skill_physical_damage_%_to_convert_to_lightning",
		"is_area_damage",
		"attack_unusable_if_triggerable",
		"attack_is_not_melee_override",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 5000, 30, 100, 50, damageEffectiveness = 0.6, cooldown = 10, baseMultiplier = 0.6, levelRequirement = 32, statInterpolation = { 1, 357, 3897, 2547, }, cost = { }, },
	},
}
skills["EnchantmentOfIreWhenHit2"] = {
	name = "Edict of Ire",
	hidden = true,
	color = 2,
	baseEffectiveness = 1.2000000476837,
	incrementalEffectiveness = 0.019999999552965,
	description = "Release a lightning charged spinning copy of your weapon or its projectiles that rotates around a point, damaging enemies in an area.",
	skillTypes = { ["Attack"] = true, ["Damage"] = true, ["Area"] = true, ["Duration"] = true, ["Totemable"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Lightning"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.5,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"extra_gore_chance_override_%",
		"melee_counterattack_trigger_on_hit_%",
		"skill_physical_damage_%_to_convert_to_lightning",
		"is_area_damage",
		"attack_unusable_if_triggerable",
		"attack_is_not_melee_override",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 5000, 30, 100, 50, damageEffectiveness = 0.9, cooldown = 10, baseMultiplier = 0.9, levelRequirement = 53, statInterpolation = { 1, 357, 3897, 2547, }, cost = { }, },
	},
}
skills["EnchantmentOfIreWhenHit3"] = {
	name = "Decree of Ire",
	hidden = true,
	color = 2,
	baseEffectiveness = 1.2000000476837,
	incrementalEffectiveness = 0.019999999552965,
	description = "Release a lightning charged spinning copy of your weapon or its projectiles that rotates around a point, damaging enemies in an area.",
	skillTypes = { ["Attack"] = true, ["Damage"] = true, ["Area"] = true, ["Duration"] = true, ["Totemable"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Lightning"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.5,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"extra_gore_chance_override_%",
		"melee_counterattack_trigger_on_hit_%",
		"skill_physical_damage_%_to_convert_to_lightning",
		"is_area_damage",
		"attack_unusable_if_triggerable",
		"attack_is_not_melee_override",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 5000, 30, 100, 50, damageEffectiveness = 1.2, cooldown = 10, baseMultiplier = 1.2, levelRequirement = 66, statInterpolation = { 1, 357, 3897, 2547, }, cost = { }, },
	},
}
skills["EnchantmentOfIreWhenHit4"] = {
	name = "Commandment of Ire",
	hidden = true,
	color = 2,
	baseEffectiveness = 1.2000000476837,
	incrementalEffectiveness = 0.019999999552965,
	description = "Release a lightning charged spinning copy of your weapon or its projectiles that rotates around a point, damaging enemies in an area.",
	skillTypes = { ["Attack"] = true, ["Damage"] = true, ["Area"] = true, ["Duration"] = true, ["Totemable"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Lightning"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.5,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"extra_gore_chance_override_%",
		"melee_counterattack_trigger_on_hit_%",
		"skill_physical_damage_%_to_convert_to_lightning",
		"is_area_damage",
		"attack_unusable_if_triggerable",
		"attack_is_not_melee_override",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 5000, 30, 100, 50, damageEffectiveness = 1.5, cooldown = 10, baseMultiplier = 1.5, levelRequirement = 75, statInterpolation = { 1, 357, 3897, 3325, }, cost = { }, },
	},
}
skills["EnchantmentOfLightWhenCrit"] = {
	name = "Word of Light",
	hidden = true,
	color = 4,
	description = "Deals a portion of your main hand damage in an area around you and creates Consecrated Ground, causing you and your allies to regenerate life.",
	skillTypes = { ["Attack"] = true, ["Area"] = true, ["Duration"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"life_regeneration_rate_per_minute_%",
		"attack_trigger_when_critically_hit_%",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 5000, 360, 100, damageEffectiveness = 1.35, cooldown = 5, baseMultiplier = 1.35, levelRequirement = 32, statInterpolation = { 1, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfLightWhenCrit2"] = {
	name = "Edict of Light",
	hidden = true,
	color = 4,
	description = "Deals a portion of your main hand damage in an area around you and creates Consecrated Ground, causing you and your allies to regenerate life.",
	skillTypes = { ["Attack"] = true, ["Area"] = true, ["Duration"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"life_regeneration_rate_per_minute_%",
		"attack_trigger_when_critically_hit_%",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 5000, 360, 100, damageEffectiveness = 1.89, cooldown = 5, baseMultiplier = 1.89, levelRequirement = 53, statInterpolation = { 1, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfLightWhenCrit3"] = {
	name = "Decree of Light",
	hidden = true,
	color = 4,
	description = "Deals a portion of your main hand damage in an area around you and creates Consecrated Ground, causing you and your allies to regenerate life.",
	skillTypes = { ["Attack"] = true, ["Area"] = true, ["Duration"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"life_regeneration_rate_per_minute_%",
		"attack_trigger_when_critically_hit_%",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 5000, 360, 100, damageEffectiveness = 2.43, cooldown = 5, baseMultiplier = 2.43, levelRequirement = 66, statInterpolation = { 1, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfLightWhenCrit4"] = {
	name = "Commandment of Light",
	hidden = true,
	color = 4,
	description = "Deals a portion of your main hand damage in an area around you and creates Consecrated Ground, causing you and your allies to regenerate life.",
	skillTypes = { ["Attack"] = true, ["Area"] = true, ["Duration"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"life_regeneration_rate_per_minute_%",
		"attack_trigger_when_critically_hit_%",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 5000, 360, 100, damageEffectiveness = 2.97, cooldown = 5, baseMultiplier = 2.97, levelRequirement = 75, statInterpolation = { 1, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfReflectionWhenHit"] = {
	name = "Word of Reflection",
	hidden = true,
	color = 4,
	description = "Creates a clone of you that attacks with your weapon.",
	skillTypes = { ["Spell"] = true, ["Minion"] = true, ["MinionsCanExplode"] = true, ["Triggered"] = true, ["Duration"] = true, ["Triggerable"] = true, ["CreatesMinion"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "minion_skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	minionList = {
		"Clone",
	},
	minionUses = {
		["Weapon 1"] = true,
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"minion_damage_+%",
		"minion_maximum_life_+%",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"cast_when_hit_%",
		"active_skill_minion_damage_+%_final",
	},
	levels = {
		[1] = { 5000, 1, 80, 150, 4, 32, 100, 100, cooldown = 10, levelRequirement = 32, statInterpolation = { 1, 1, 357, 2156, 488, 159, 458, 457, }, cost = { }, },
	},
}
skills["EnchantmentOfReflectionWhenHit2"] = {
	name = "Edict of Reflection",
	hidden = true,
	color = 4,
	description = "Creates a clone of you that attacks with your weapon.",
	skillTypes = { ["Spell"] = true, ["Minion"] = true, ["MinionsCanExplode"] = true, ["Triggered"] = true, ["Duration"] = true, ["Triggerable"] = true, ["CreatesMinion"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	minionList = {
		"Clone",
	},
	minionUses = {
		["Weapon 1"] = true,
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"minion_damage_+%",
		"minion_maximum_life_+%",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"cast_when_hit_%",
		"active_skill_minion_damage_+%_final",
	},
	levels = {
		[1] = { 5000, 1, 100, 150, 4, 53, 100, 200, cooldown = 10, levelRequirement = 53, statInterpolation = { 1, 1, 357, 2156, 488, 159, 458, 457, }, cost = { }, },
	},
}
skills["EnchantmentOfReflectionWhenHit3"] = {
	name = "Decree of Reflection",
	hidden = true,
	color = 4,
	description = "Creates a clone of you that attacks with your weapon.",
	skillTypes = { ["Spell"] = true, ["Minion"] = true, ["MinionsCanExplode"] = true, ["Triggered"] = true, ["Duration"] = true, ["Triggerable"] = true, ["CreatesMinion"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	minionList = {
		"Clone",
	},
	minionUses = {
		["Weapon 1"] = true,
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"minion_damage_+%",
		"minion_maximum_life_+%",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"cast_when_hit_%",
		"active_skill_minion_damage_+%_final",
	},
	levels = {
		[1] = { 5000, 1, 120, 150, 4, 66, 100, 300, cooldown = 10, levelRequirement = 66, statInterpolation = { 1, 1, 357, 2156, 488, 159, 458, 457, }, cost = { }, },
	},
}
skills["EnchantmentOfReflectionWhenHit4"] = {
	name = "Commandment of Reflection",
	hidden = true,
	color = 4,
	description = "Creates a clone of you that attacks with your weapon.",
	skillTypes = { ["Spell"] = true, ["Minion"] = true, ["MinionsCanExplode"] = true, ["Triggered"] = true, ["Duration"] = true, ["Triggerable"] = true, ["CreatesMinion"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	minionList = {
		"Clone",
	},
	minionUses = {
		["Weapon 1"] = true,
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"minion_damage_+%",
		"minion_maximum_life_+%",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"cast_when_hit_%",
		"active_skill_minion_damage_+%_final",
	},
	levels = {
		[1] = { 5000, 1, 140, 150, 4, 75, 100, 400, cooldown = 10, levelRequirement = 75, statInterpolation = { 1, 1, 3325, 2, 618, 2301, 1, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfSpiteWhenHit"] = {
	name = "Word of Spite",
	hidden = true,
	color = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Releases a circle of projectiles based on your weapon, leaving chilled ground in their wake.",
	skillTypes = { ["Attack"] = true, ["RangedAttack"] = true, ["Projectile"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["ChillingArea"] = true, ["Cold"] = true, ["ProjectilesNotFromUser"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_projectile_ground_effect_duration",
		"number_of_additional_projectiles",
		"melee_counterattack_trigger_on_hit_%",
		"skill_art_variation",
		"skill_physical_damage_%_to_convert_to_cold",
		"projectiles_drop_ground_ice",
		"projectiles_drop_ground_effects_on_client",
		"base_is_projectile",
		"projectiles_nova",
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2000, 9, 100, 2, 50, damageEffectiveness = 1.5, cooldown = 5, baseMultiplier = 1.5, levelRequirement = 32, statInterpolation = { 1, 1, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfSpiteWhenHit2"] = {
	name = "Edict of Spite",
	hidden = true,
	color = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Releases a circle of projectiles based on your weapon, leaving chilled ground in their wake.",
	skillTypes = { ["Attack"] = true, ["RangedAttack"] = true, ["Projectile"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["ChillingArea"] = true, ["Cold"] = true, ["ProjectilesNotFromUser"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_projectile_ground_effect_duration",
		"number_of_additional_projectiles",
		"melee_counterattack_trigger_on_hit_%",
		"skill_art_variation",
		"skill_physical_damage_%_to_convert_to_cold",
		"projectiles_drop_ground_ice",
		"projectiles_drop_ground_effects_on_client",
		"base_is_projectile",
		"projectiles_nova",
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2000, 9, 100, 2, 50, damageEffectiveness = 2.1, cooldown = 5, baseMultiplier = 2.1, levelRequirement = 53, statInterpolation = { 1, 1, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfSpiteWhenHit3"] = {
	name = "Decree of Spite",
	hidden = true,
	color = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Releases a circle of projectiles based on your weapon, leaving chilled ground in their wake.",
	skillTypes = { ["Attack"] = true, ["RangedAttack"] = true, ["Projectile"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["ChillingArea"] = true, ["Cold"] = true, ["ProjectilesNotFromUser"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_projectile_ground_effect_duration",
		"number_of_additional_projectiles",
		"melee_counterattack_trigger_on_hit_%",
		"skill_art_variation",
		"skill_physical_damage_%_to_convert_to_cold",
		"projectiles_drop_ground_ice",
		"projectiles_drop_ground_effects_on_client",
		"base_is_projectile",
		"projectiles_nova",
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2000, 9, 100, 2, 50, damageEffectiveness = 2.7, cooldown = 5, baseMultiplier = 2.7, levelRequirement = 66, statInterpolation = { 1, 1, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfSpiteWhenHit4"] = {
	name = "Commandment of Spite",
	hidden = true,
	color = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Releases a circle of projectiles based on your weapon, leaving chilled ground in their wake.",
	skillTypes = { ["Attack"] = true, ["RangedAttack"] = true, ["Projectile"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["ChillingArea"] = true, ["Cold"] = true, ["ProjectilesNotFromUser"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_projectile_ground_effect_duration",
		"number_of_additional_projectiles",
		"melee_counterattack_trigger_on_hit_%",
		"skill_art_variation",
		"skill_physical_damage_%_to_convert_to_cold",
		"projectiles_drop_ground_ice",
		"projectiles_drop_ground_effects_on_client",
		"base_is_projectile",
		"projectiles_nova",
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2000, 9, 100, 2, 50, damageEffectiveness = 3.3, cooldown = 5, baseMultiplier = 3.3, levelRequirement = 75, statInterpolation = { 1, 1, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfTempestOnHit"] = {
	name = "Word of the Tempest",
	hidden = true,
	color = 4,
	baseEffectiveness = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Charges you with lightning which lasts a duration before unleashing, damaging surrounding enemies.",
	skillTypes = { ["Spell"] = true, ["Damage"] = true, ["Area"] = true, ["Trappable"] = true, ["Totemable"] = true, ["Mineable"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 4,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"base_skill_area_of_effect_+%",
		"skill_art_variation",
		"cast_on_hit_%",
		"base_skill_effect_duration",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1, 280, 0, 0, 100, 2000, critChance = 7, cooldown = 10, levelRequirement = 32, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfTempestOnHit2"] = {
	name = "Edict of the Tempest",
	hidden = true,
	color = 4,
	baseEffectiveness = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Charges you with lightning which lasts a duration before unleashing, damaging surrounding enemies.",
	skillTypes = { ["Spell"] = true, ["Damage"] = true, ["Area"] = true, ["Trappable"] = true, ["Totemable"] = true, ["Mineable"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 4,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"base_skill_area_of_effect_+%",
		"skill_art_variation",
		"cast_on_hit_%",
		"base_skill_effect_duration",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1.5, 1245, 0, 0, 100, 2000, critChance = 7, cooldown = 10, levelRequirement = 53, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfTempestOnHit3"] = {
	name = "Decree of the Tempest",
	hidden = true,
	color = 4,
	baseEffectiveness = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Charges you with lightning which lasts a duration before unleashing, damaging surrounding enemies.",
	skillTypes = { ["Spell"] = true, ["Damage"] = true, ["Area"] = true, ["Trappable"] = true, ["Totemable"] = true, ["Mineable"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 4,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"base_skill_area_of_effect_+%",
		"skill_art_variation",
		"cast_on_hit_%",
		"base_skill_effect_duration",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2, 3065, 0, 0, 100, 2000, critChance = 7, cooldown = 10, levelRequirement = 66, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfTempestOnHit4"] = {
	name = "Commandment of the Tempest",
	hidden = true,
	color = 4,
	baseEffectiveness = 4,
	incrementalEffectiveness = 0.035000000149012,
	description = "Charges you with lightning which lasts a duration before unleashing, damaging surrounding enemies.",
	skillTypes = { ["Spell"] = true, ["Damage"] = true, ["Area"] = true, ["Trappable"] = true, ["Totemable"] = true, ["Mineable"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 4,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"base_skill_area_of_effect_+%",
		"skill_art_variation",
		"cast_on_hit_%",
		"base_skill_effect_duration",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2.4000000953674, 5920, 0, 0, 100, 2000, critChance = 7, cooldown = 10, levelRequirement = 75, statInterpolation = { 3, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfTheGraveOnKill"] = {
	name = "Word of the Grave",
	hidden = true,
	color = 4,
	description = "Summons three icy skull minions that explode at the end of their duration.",
	skillTypes = { ["Spell"] = true, ["Minion"] = true, ["MinionsCanExplode"] = true, ["Cold"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["Duration"] = true, ["CreatesMinion"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	minionList = {
		"IcyRagingSpirit",
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"chance_to_cast_on_owned_kill_%",
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"minions_explode_on_death_for_%_max_life_at_end_of_duration",
		"minions_cannot_taunt_enemies",
	},
	levels = {
		[1] = { 100, 5000, 3, 10, 32, 20, cooldown = 5, levelRequirement = 32, statInterpolation = { 1, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfTheGraveOnKill2"] = {
	name = "Edict of the Grave",
	hidden = true,
	color = 4,
	description = "Summons three icy skull minions that explode at the end of their duration.",
	skillTypes = { ["Spell"] = true, ["Minion"] = true, ["MinionsCanExplode"] = true, ["Cold"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["Duration"] = true, ["CreatesMinion"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	minionList = {
		"IcyRagingSpirit",
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"chance_to_cast_on_owned_kill_%",
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"minions_explode_on_death_for_%_max_life_at_end_of_duration",
		"minions_cannot_taunt_enemies",
	},
	levels = {
		[1] = { 100, 5000, 3, 10, 53, 20, cooldown = 5, levelRequirement = 53, statInterpolation = { 1, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfTheGraveOnKill3"] = {
	name = "Decree of the Grave",
	hidden = true,
	color = 4,
	description = "Summons three icy skull minions that explode at the end of their duration.",
	skillTypes = { ["Spell"] = true, ["Minion"] = true, ["MinionsCanExplode"] = true, ["Cold"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["Duration"] = true, ["CreatesMinion"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	minionList = {
		"IcyRagingSpirit",
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"chance_to_cast_on_owned_kill_%",
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"minions_explode_on_death_for_%_max_life_at_end_of_duration",
		"minions_cannot_taunt_enemies",
	},
	levels = {
		[1] = { 100, 5000, 3, 10, 66, 20, cooldown = 5, levelRequirement = 66, statInterpolation = { 1, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfTheGraveOnKill4"] = {
	name = "Commandment of the Grave",
	hidden = true,
	color = 4,
	description = "Summons three icy skull minions that explode at the end of their duration.",
	skillTypes = { ["Spell"] = true, ["Minion"] = true, ["MinionsCanExplode"] = true, ["Cold"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["Duration"] = true, ["CreatesMinion"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	minionList = {
		"IcyRagingSpirit",
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"chance_to_cast_on_owned_kill_%",
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"minions_explode_on_death_for_%_max_life_at_end_of_duration",
		"minions_cannot_taunt_enemies",
	},
	levels = {
		[1] = { 100, 5000, 3, 10, 75, 20, cooldown = 5, levelRequirement = 75, statInterpolation = { 1, 1, 0, 0, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfThunderOnKill"] = {
	name = "Word of Thunder",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.625,
	incrementalEffectiveness = 0.035000000149012,
	description = "Damaging cones of lightning surround you.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["TotemCastsWhenNotDetached"] = true, ["Lightning"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"chance_to_cast_on_kill_%_target_self",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1, 114, 100, critChance = 7, cooldown = 5, levelRequirement = 32, statInterpolation = { 3, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfThunderOnKill2"] = {
	name = "Edict of Thunder",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.625,
	incrementalEffectiveness = 0.035000000149012,
	description = "Damaging cones of lightning surround you.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["TotemCastsWhenNotDetached"] = true, ["Lightning"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"chance_to_cast_on_kill_%_target_self",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1.5, 506, 100, critChance = 7, cooldown = 5, levelRequirement = 53, statInterpolation = { 3, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfThunderOnKill3"] = {
	name = "Decree of Thunder",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.625,
	incrementalEffectiveness = 0.035000000149012,
	description = "Damaging cones of lightning surround you.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["TotemCastsWhenNotDetached"] = true, ["Lightning"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"chance_to_cast_on_kill_%_target_self",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2, 1245, 100, critChance = 7, cooldown = 5, levelRequirement = 66, statInterpolation = { 3, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfThunderOnKill4"] = {
	name = "Commandment of Thunder",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.625,
	incrementalEffectiveness = 0.035000000149012,
	description = "Damaging cones of lightning surround you.",
	skillTypes = { ["Spell"] = true, ["Area"] = true, ["TotemCastsWhenNotDetached"] = true, ["Lightning"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["AreaSpell"] = true, ["Nova"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"chance_to_cast_on_kill_%_target_self",
		"is_area_damage",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2.4000000953674, 2405, 100, critChance = 7, cooldown = 5, levelRequirement = 75, statInterpolation = { 3, 0, 0, }, cost = { }, },
	},
}
skills["EnchantmentOfWarOnKill"] = {
	name = "Word of War",
	hidden = true,
	color = 4,
	description = "This attack is performed repeatedly by a ghostly imitation of your weapon.",
	skillTypes = { ["Attack"] = true, ["MeleeSingleTarget"] = true, ["Multistrikeable"] = true, ["Melee"] = true, ["Duration"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"attack_trigger_on_kill_%",
		"active_skill_minion_damage_+%_final",
	},
	levels = {
		[1] = { 10000, 1, 100, 50, cooldown = 5, levelRequirement = 32, statInterpolation = { 1, 357, 2156, 4515, }, cost = { }, },
	},
}
skills["EnchantmentOfWarOnKill2"] = {
	name = "Edict of War",
	hidden = true,
	color = 4,
	description = "This attack is performed repeatedly by a ghostly imitation of your weapon.",
	skillTypes = { ["Attack"] = true, ["MeleeSingleTarget"] = true, ["Multistrikeable"] = true, ["Melee"] = true, ["Duration"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"attack_trigger_on_kill_%",
		"active_skill_minion_damage_+%_final",
	},
	levels = {
		[1] = { 10000, 1, 100, 100, cooldown = 5, levelRequirement = 53, statInterpolation = { 1, 357, 2156, 4515, }, cost = { }, },
	},
}
skills["EnchantmentOfWarOnKill3"] = {
	name = "Decree of War",
	hidden = true,
	color = 4,
	description = "This attack is performed repeatedly by a ghostly imitation of your weapon.",
	skillTypes = { ["Attack"] = true, ["MeleeSingleTarget"] = true, ["Multistrikeable"] = true, ["Melee"] = true, ["Duration"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"attack_trigger_on_kill_%",
		"active_skill_minion_damage_+%_final",
	},
	levels = {
		[1] = { 10000, 1, 100, 150, cooldown = 5, levelRequirement = 66, statInterpolation = { 1, 357, 2156, 4515, }, cost = { }, },
	},
}
skills["EnchantmentOfWarOnKill4"] = {
	name = "Commandment of War",
	hidden = true,
	color = 4,
	description = "This attack is performed repeatedly by a ghostly imitation of your weapon.",
	skillTypes = { ["Attack"] = true, ["MeleeSingleTarget"] = true, ["Multistrikeable"] = true, ["Melee"] = true, ["Duration"] = true, ["Triggered"] = true, ["Triggerable"] = true, ["Cooldown"] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Wand"] = true,
		["Bow"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		attack = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"number_of_monsters_to_summon",
		"attack_trigger_on_kill_%",
		"active_skill_minion_damage_+%_final",
	},
	levels = {
		[1] = { 10000, 1, 100, 200, cooldown = 5, levelRequirement = 75, statInterpolation = { 1, 1470, 1471, 357, }, cost = { }, },
	},
}
skills["EnchantmentOfWinterWhenHit"] = {
	name = "Word of Winter",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.0908999443054,
	incrementalEffectiveness = 0.035000000149012,
	description = "Unleashes an icy projectile that pulses with cold as it travels.",
	skillTypes = { ["Projectile"] = true, ["ProjectilesFromUser"] = true, ["Spell"] = true, ["Damage"] = true, ["Area"] = true, ["Trappable"] = true, ["Totemable"] = true, ["Mineable"] = true, ["Multicastable"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["AreaSpell"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.4,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"skill_art_variation",
		"cast_when_hit_%",
		"is_area_damage",
		"base_is_projectile",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1, 76, 1, 100, critChance = 5, cooldown = 10, levelRequirement = 32, statInterpolation = { 3, 1472, 1473, 347, }, cost = { }, },
	},
}
skills["EnchantmentOfWinterWhenHit2"] = {
	name = "Edict of Winter",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.0908999443054,
	incrementalEffectiveness = 0.035000000149012,
	description = "Unleashes an icy projectile that pulses with cold as it travels.",
	skillTypes = { ["Projectile"] = true, ["ProjectilesFromUser"] = true, ["Spell"] = true, ["Damage"] = true, ["Area"] = true, ["Trappable"] = true, ["Totemable"] = true, ["Mineable"] = true, ["Multicastable"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["AreaSpell"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.4,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"skill_art_variation",
		"cast_when_hit_%",
		"is_area_damage",
		"base_is_projectile",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 1.5, 340, 1, 100, critChance = 5, cooldown = 10, levelRequirement = 53, statInterpolation = { 3, 1472, 1473, 347, }, cost = { }, },
	},
}
skills["EnchantmentOfWinterWhenHit3"] = {
	name = "Decree of Winter",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.0908999443054,
	incrementalEffectiveness = 0.035000000149012,
	description = "Unleashes an icy projectile that pulses with cold as it travels.",
	skillTypes = { ["Projectile"] = true, ["ProjectilesFromUser"] = true, ["Spell"] = true, ["Damage"] = true, ["Area"] = true, ["Trappable"] = true, ["Totemable"] = true, ["Mineable"] = true, ["Multicastable"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["AreaSpell"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.4,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"skill_art_variation",
		"cast_when_hit_%",
		"is_area_damage",
		"base_is_projectile",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2, 836, 1, 100, critChance = 5, cooldown = 10, levelRequirement = 66, statInterpolation = { 3, 1472, 1473, 347, }, cost = { }, },
	},
}
skills["EnchantmentOfWinterWhenHit4"] = {
	name = "Commandment of Winter",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.0908999443054,
	incrementalEffectiveness = 0.035000000149012,
	description = "Unleashes an icy projectile that pulses with cold as it travels.",
	skillTypes = { ["Projectile"] = true, ["ProjectilesFromUser"] = true, ["Spell"] = true, ["Damage"] = true, ["Area"] = true, ["Trappable"] = true, ["Totemable"] = true, ["Mineable"] = true, ["Multicastable"] = true, ["Triggerable"] = true, ["Triggered"] = true, ["AreaSpell"] = true, ["Cooldown"] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.4,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"skill_art_variation",
		"cast_when_hit_%",
		"is_area_damage",
		"base_is_projectile",
		"damage_cannot_be_reflected",
	},
	levels = {
		[1] = { 2.4000000953674, 1615, 1, 100, critChance = 5, cooldown = 10, levelRequirement = 75, statInterpolation = { 3, 1474, 1475, 434, }, cost = { }, },
	},
}