-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Boss Data
-- Boss data (c) Grinding Gear Games
--
local bosses = ...

bosses["Venarius"] = {
	armourMult = 100,
	evasionMult = 20,
	isUber = true,
}
bosses["EaterOfWorlds"] = {
	armourMult = 100,
	evasionMult = 0,
	isUber = true,
}
bosses["SearingExarch"] = {
	armourMult = 50,
	evasionMult = 0,
	isUber = true,
}
bosses["Maven"] = {
	armourMult = 100,
	evasionMult = 20,
	isUber = true,
}
bosses["Sirus"] = {
	armourMult = 100,
	evasionMult = 20,
	isUber = true,
}
bosses["Shaper"] = {
	armourMult = 33,
	evasionMult = 20,
	isUber = true,
}
bosses["Elder"] = {
	armourMult = 2000,
	evasionMult = 20,
	isUber = true,
}

bosses["BlackStar"] = {
	armourMult = 50,
	evasionMult = 0,
	isUber = false,
}
bosses["InfiniteHunger"] = {
	armourMult = 0,
	evasionMult = 0,
	isUber = false,
}

bosses["Atziri"] = {
	armourMult = 50,
	evasionMult = 20,
	isUber = false,
}

bosses["Phoenix"] = {
	armourMult = 0,
	evasionMult = 20,
	isUber = false,
}
bosses["Hydra"] = {
	armourMult = 0,
	evasionMult = 20,
	isUber = false,
}
bosses["Minotaur"] = {
	armourMult = 0,
	evasionMult = 20,
	isUber = false,
}
bosses["Chimera"] = {
	armourMult = 50,
	evasionMult = 20,
	isUber = false,
}

bosses["Enslaver"] = {
	armourMult = 33,
	evasionMult = 20,
	isUber = false,
}
bosses["Eradicator"] = {
	armourMult = 33,
	evasionMult = 20,
	isUber = false,
}
bosses["Constrictor"] = {
	armourMult = 33,
	evasionMult = 20,
	isUber = false,
}
bosses["Purifier"] = {
	armourMult = 33,
	evasionMult = 20,
	isUber = false,
}

bosses["Baran"] = {
	armourMult = 100,
	evasionMult = 20,
	isUber = false,
}
bosses["Veritania"] = {
	armourMult = 100,
	evasionMult = 20,
	isUber = false,
}
bosses["AlHezmin"] = {
	armourMult = 100,
	evasionMult = 20,
	isUber = false,
}
bosses["Drox"] = {
	armourMult = 100,
	evasionMult = 20,
	isUber = false,
}
