-- This file is automatically generated, do not edit!
-- Game data (c) Grinding Gear Games


-- spell-checker: disable
return {
	["DivergentAbyssJewelSocketUnique__10"] = {
		"Command of the Pit",
	},
	["DivergentAbyssJewelSocketUnique__12"] = {
		"Bubonic Trail",
	},
	["DivergentAbyssJewelSocketUnique__14"] = {
		"Replica Shroud of the Lightless",
	},
	["DivergentAbyssJewelSocketUnique__15"] = {
		"Shroud of the Lightless",
	},
	["DivergentAbyssJewelSocketUnique__17"] = {
		"Wraithlord",
	},
	["DivergentAbyssJewelSocketUnique__18"] = {
		"Hale Negator",
	},
	["DivergentAddedChaosDamagePerCurseUnique__1"] = {
		"Doedre's Scorn",
	},
	["DivergentAddedChaosDamageToAttacksPer50StrengthUnique__1"] = {
		"Replica Alberon's Warpath",
	},
	["DivergentAddedColdDamageUniqueBodyDex1"] = {
		"Hyrri's Ire",
	},
	["DivergentAddedLightningDamageUnique__4"] = {
		"Replica Hyrri's Ire",
	},
	["DivergentAddedPhysicalDamageUniqueShieldDex6"] = {
		"Great Old One's Ward",
	},
	["DivergentAdditionalBlockChanceUniqueShieldDex2"] = {
		"The Unshattered Will",
	},
	["DivergentAdditionalCurseOnEnemiesUnique__1"] = {
		"Windscream",
	},
	["DivergentAdditionalHolyRelicUnique__1"] = {
		"Geofri's Crest",
	},
	["DivergentAdditionalPierceWhilePhasingUnique__1"] = {
		"Voidwalker",
	},
	["DivergentAdrenalineOnFillingLifeLeechUnique__1"] = {
		"Tanu Ahi",
	},
	["DivergentAdrenalineOnWardBreakUnique__1"] = {
		"Olroth's Charge",
	},
	["DivergentAilmentDamageOverTimeMultiplierPerElderItemUnique__1"] = {
		"Blasphemer's Grasp",
	},
	["DivergentAllAttributesUnique__21"] = {
		"Forbidden Shako",
	},
	["DivergentAllAttributesUnique__6"] = {
		"Loreweave",
	},
	["DivergentAllDamageCanFreezeUnique__1"] = {
		"Expedition's End",
	},
	["DivergentAllDamageCanPoisonGloriousMadnessUnique___1"] = {
		"Beacon of Madness",
	},
	["DivergentAllDefencesUnique__2"] = {
		"Skin of the Loyal",
	},
	["DivergentAllResistancesUniqueHelmetDex3"] = {
		"Goldrim",
	},
	["DivergentAllResistancesUnique__23__"] = {
		"Medved's Challenge",
	},
	["DivergentAlternateColdAilmentUnique__1"] = {
		"Galesight",
	},
	["DivergentAlternateFireAilmentUnique__1"] = {
		"Flamesight",
	},
	["DivergentAlternateLightningAilmentUnique__1__"] = {
		"Thundersight",
	},
	["DivergentAnimatedMinionsHaveMeleeSplashUnique__1"] = {
		"Chains of Command",
	},
	["DivergentAnyRingMagicDamageExtraRollUnique__1"] = {
		"Viridi's Veil",
	},
	["DivergentApplyAilmentsMoreDamageUnique__1"] = {
		"Painseeker",
	},
	["DivergentArcaneSurgeOnMovementSkillUnique"] = {
		"Scornflux",
	},
	["DivergentArcticArmourReservationCostUnique__1"] = {
		"The Snowblind Grace",
	},
	["DivergentAreaOfEffectPerEnemyKilledRecentlyCapped25Unique__1"] = {
		"Zeel's Amplifier",
	},
	["DivergentAreaOfEffectUniqueBodyDexInt1"] = {
		"Carcass Jack",
	},
	["DivergentArmourAppliesToChaosDamagePercentUnique__1"] = {
		"The Fourth Vow",
	},
	["DivergentArmourAppliesToLightningDamagePercentUnique__1"] = {
		"Doryani's Prototype",
	},
	["DivergentArmourIncreasedByUncappedFireResistanceUnique__1"] = {
		"The Formless Flame",
	},
	["DivergentArmourPerTotemUnique__1"] = {
		"Tukohama's Fortress",
	},
	["DivergentAttackCorrosionOnHitChanceUnique__1"] = {
		"Ceaseless Feast",
	},
	["DivergentAttackLightningDamageMaximumManaUnique__1__"] = {
		"Mind of the Council",
	},
	["DivergentAttackSpeedOnFullLifeUniqueGlovesStr1"] = {
		"Ondar's Clasp",
	},
	["DivergentAttackerTakesColdDamageUnique__1"] = {
		"The Trickster's Smile",
	},
	["DivergentAttackerTakesFireDamageUnique__1"] = {
		"The Trickster's Smile",
	},
	["DivergentAttackerTakesLightningDamageUnique__1"] = {
		"The Trickster's Smile",
	},
	["DivergentAttacksBleedOnHitWithCatsStealthUnique__1_"] = {
		"Farrul's Pounce",
	},
	["DivergentAuraEffectUniqueShieldInt2"] = {
		"Matua Tupuna",
	},
	["DivergentAuraEffectWhileLinkedUnique__1"] = {
		"The Hand of Phrecia",
	},
	["DivergentAvianAspectBuffEffectUnique__1"] = {
		"Saqawal's Nest",
	},
	["DivergentAviansMightColdDamageUnique__1"] = {
		"Saqawal's Winds",
	},
	["DivergentAviansMightLightningDamageUnique__1_"] = {
		"Saqawal's Winds",
	},
	["DivergentAvoidFreezeAndChillIfFireSkillUsedRecentlyUnique__1"] = {
		"Hrimnor's Resolve",
	},
	["DivergentAvoidIgniteOnLowLifeUniqueShieldStrInt5"] = {
		"Rise of the Phoenix",
	},
	["DivergentAvoidInterruptionWhileCastingUnique__1"] = {
		"Sandstorm Visage",
	},
	["DivergentBannerResourceGainedUnique__1"] = {
		"Perfidy",
	},
	["DivergentBaseManaRegenerationUniqueBodyDexInt2"] = {
		"Cloak of Defiance",
	},
	["DivergentBaseUnarmedCriticalStrikeChanceUnique__2"] = {
		"Seven Teachings",
	},
	["DivergentBleedOnSelfDealChaosDamageUnique__1"] = {
		"Apep's Supremacy",
	},
	["DivergentBleedingEnemiesExplodeUnique__1"] = {
		"Haemophilia",
	},
	["DivergentBleedingImmunityUnique__1"] = {
		"Death's Door",
	},
	["DivergentBlightSecondarySkillEffectDurationUnique__1"] = {
		"Allelopathy",
	},
	["DivergentBlockChancePer50StrengthUnique__1"] = {
		"The Iron Fortress",
	},
	["DivergentBlockChanceVersusCursedEnemiesUnique__1"] = {
		"Chalice of Horrors",
	},
	["DivergentBlockVsProjectilesUniqueShieldStr2"] = {
		"Titucius' Span",
	},
	["DivergentCannotBeFrozenUnique__1"] = {
		"Vix Lunaris",
	},
	["DivergentCannotBeShockedWhileMaximumEnduranceChargesUnique_1"] = {
		"Veruso's Battering Rams",
	},
	["DivergentCannotBeSlowedBelowBaseUnique__1"] = {
		"Kaom's Roots",
	},
	["DivergentCannotBeStunnedSuppressedDamageUnique__1"] = {
		"Orbala's Stand",
	},
	["DivergentCannotLoseCrabBarriersIfLostRecentlyUnique__1"] = {
		"Craiceann's Chitin",
	},
	["DivergentCastSpeedAppliesToTrapSpeedUnique__1"] = {
		"Architect's Hand",
	},
	["DivergentCatAspectReservesNoManaUnique__1___"] = {
		"Farrul's Fur",
	},
	["DivergentCatsStealthTriggeredIntimidatingCry"] = {
		"Farrul's Chase",
	},
	["DivergentChanceToBlockSpellsPerPowerChargeUnique__2_"] = {
		"Willclash",
	},
	["DivergentChanceToCastOnManaSpentUnique__1"] = {
		"Kitava's Thirst",
	},
	["DivergentChanceToFreezeShockIgniteUnique__1"] = {
		"The Admiral",
	},
	["DivergentChanceToGainMaximumCrabBarriersUnique__1_"] = {
		"Craiceann's Pincers",
	},
	["DivergentChanceToGainMaximumPowerChargesUnique__1_"] = {
		"Inya's Epiphany",
	},
	["DivergentChanceToGainMaximumRageUnique__1"] = {
		"Admiral's Arrogance",
	},
	["DivergentChanceToSapVsEnemiesInChillingAreasUnique__1"] = {
		"Algor Mortis",
	},
	["DivergentChanceToSuppressSpellsUnique__1_"] = {
		"The Oppressor",
	},
	["DivergentChanceToSuppressSpellsWhileChannellingUnique__1____"] = {
		"Assailum",
	},
	["DivergentChanceToThrowFourAdditionalTrapsUnique__1"] = {
		"Architect's Hand",
	},
	["DivergentChaosDamageCanIgniteUnique__1"] = {
		"Replica Volkuur's Guidance",
	},
	["DivergentChaosDamageDoesNotBypassESNotLowLifeOrManaUnique__1"] = {
		"Esh's Visage",
	},
	["DivergentChaosDamageDoesNotBypassEnergyShieldPercentUnique__2"] = {
		"Solaris Lorica",
	},
	["DivergentChaosDamageOverTimeUnique__1"] = {
		"Solaris Lorica",
	},
	["DivergentChaosDamageRemovedFromManaBeforeLifeUnique__1___"] = {
		"The Ivory Tower",
	},
	["DivergentChaosDegenAuraUnique__1"] = {
		"Death's Oath",
	},
	["DivergentChaosResistanceIsZeroUnique__1"] = {
		"Glimpse of Chaos",
	},
	["DivergentChaosResistanceWhileStationaryUnique__1"] = {
		"Replica Red Trail",
	},
	["DivergentChaosResistanceWhileUsingFlaskUniqueBootsStrDex3"] = {
		"Dusktoe",
	},
	["DivergentChargeDurationUniqueBodyDexInt3"] = {
		"The Restless Ward",
	},
	["DivergentColdAddedAsFireChilledEnemyUnique__1"] = {
		"Heatshiver",
	},
	["DivergentColdDamageCanPoisonAndLessDurationUnique__1"] = {
		"Volkuur's Guidance",
	},
	["DivergentColdDamageOverTimeMultiplierUnique__2"] = {
		"Rime Gaze",
	},
	["DivergentColdExposureOnHitUnique__1"] = {
		"Eye of Malice",
	},
	["DivergentColdHitAndDoTDamageTakenAsLightningUnique__1"] = {
		"Font of Thunder",
	},
	["DivergentColdIgnitesUniqueHelmetDexInt4_"] = {
		"The Three Dragons",
	},
	["DivergentColdResistanceOverrideUnique__1"] = {
		"Cowl of the Cryophile",
	},
	["DivergentCommandmentOfInfernoOnCritUnique__1"] = {
		"Unyielding Flame",
	},
	["DivergentConvertFireToChaosUniqueBodyInt4Updated"] = {
		"Infernal Mantle",
	},
	["DivergentConvertPhysicalToColdUniqueGlovesDex1"] = {
		"Hrimsorrow",
	},
	["DivergentConvertPhysicalToFireUniqueShieldStr3"] = {
		"Chernobog's Pillar",
	},
	["DivergentCorpseWalkUnique__1"] = {
		"Corpsewalker",
	},
	["DivergentCounterAttacksAddedColdDamageUnique__1"] = {
		"Lycosidae",
	},
	["DivergentCrabBarriersLostWhenHitUnique__1_"] = {
		"Craiceann's Tracks",
	},
	["DivergentCreateSmokeCloudWhenTrapTriggeredUnique__1"] = {
		"Kongming's Stratagem",
	},
	["DivergentCriticalMultiplierPerBlockChanceUnique__1"] = {
		"Light of Lunaris",
	},
	["DivergentCriticalStrikeChancePerBrandUnique__1___"] = {
		"Replica Tukohama's Fortress",
	},
	["DivergentCriticalStrikeChanceUniqueGlovesDex2"] = {
		"Maligaro's Virtuosity",
	},
	["DivergentCriticalStrikeChanceUniqueHelmetDex6"] = {
		"Rat's Nest",
	},
	["DivergentCurseOnHitCriticalWeaknessUniqueNewUnique__1"] = {
		"Oskarm",
	},
	["DivergentCurseOnHitTemporalChainsUnique__1"] = {
		"Asenath's Gentle Touch",
	},
	["DivergentCurseSkillsCostAndReserveLifeUnique__1"] = {
		"Waxen Soul",
	},
	["DivergentDamageOverTimeMultiplierIfCrit8SecondsUnique__1_"] = {
		"Qotra's Regulator",
	},
	["DivergentDamagePer15DexterityUnique__2"] = {
		"Briskwrap",
	},
	["DivergentDamageTakenFromMarkedTargetUnique__1"] = {
		"Mercenary's Lot",
	},
	["DivergentDamageTakenFromTotemLifeBeforePlayerUnique__1"] = {
		"Dawnstrider",
	},
	["DivergentDamageTakenPer5RageCappedAt50PercentUnique_1"] = {
		"The Caged Mammoth",
	},
	["DivergentDamageYouReflectGainedAsLifeUniqueHelmetDexInt6"] = {
		"Crown of the Pale King",
	},
	["DivergentDebuffTimePassedUnique__2"] = {
		"Stasis Prison",
	},
	["DivergentDisplayDamageAuraUniqueHelmetDexInt2"] = {
		"Leer Cast",
	},
	["DivergentDisplayGrantsBloodOfferingUnique__1_"] = {
		"Bloodbond",
	},
	["DivergentDisplaySocketedGemGetsAddedLightningDamageUnique__1"] = {
		"Thunderfist",
	},
	["DivergentDisplaySocketedGemGetsFasterAttackUniqueHelmetStrDex4"] = {
		"The Bringer of Rain",
	},
	["DivergentDisplaySocketedGemGetsSpellTotemBodyInt7"] = {
		"Soul Mantle",
	},
	["DivergentDisplaySocketedMinionGemsSupportedByLifeLeechUnique__1"] = {
		"Cloak of Tawm'r Isley",
	},
	["DivergentDisplaySupportedByAddedColdDamageUnique__2"] = {
		"Replica Covenant",
	},
	["DivergentDisplaySupportedByUnleashUnique__1"] = {
		"Replica Kalisa's Grace",
	},
	["DivergentDodgeAndSpellDodgePerMaximumManaUnique__1"] = {
		"Omeyocan",
	},
	["DivergentDoubleDamageChanceGloriousMadnessUnique_1"] = {
		"Beacon of Madness",
	},
	["DivergentDrainAllManaLightningDamageUnique__1"] = {
		"Manastorm",
	},
	["DivergentElementalAilmentImmunityGloriousMadnessUnique1"] = {
		"Beacon of Madness",
	},
	["DivergentElementalConfluxesGloriousMadnessUnique1"] = {
		"Beacon of Madness",
	},
	["DivergentElementalDamageTakenAsChaosUniqueBodyStrInt5"] = {
		"Incandescent Heart",
	},
	["DivergentElementalDamageTakenAsPhysicalUnique__1"] = {
		"The Flawed Refuge",
	},
	["DivergentElementalWeaknessOnSpellBlockUniqueShieldInt4"] = {
		"Sentari's Answer",
	},
	["DivergentElusiveEffectUnique__1"] = {
		"Replica Three-step Assault",
	},
	["DivergentEnemiesBlockedAreIntimidatedUnique__1"] = {
		"The Anticipation",
	},
	["DivergentEnemiesCantLifeLeechUnique__1"] = {
		"Sin Trek",
	},
	["DivergentEnemiesCountAsMovingElementalAilmentsUnique__1"] = {
		"The Tempest Rising",
	},
	["DivergentEnemiesExplodeOnDeathChaosGloriousMadnessUnique1"] = {
		"Beacon of Madness",
	},
	["DivergentEnemiesKilledApplyImpaleDamageUnique__1"] = {
		"Great Old One's Tentacles",
	},
	["DivergentEnemiesKilledCountAsYoursUnique__1"] = {
		"Gravebind",
	},
	["DivergentEnemyExtraDamageRollsOnFullLifeUnique__2"] = {
		"Foxshade",
	},
	["DivergentEnemyExtraDamagerollsWithPhysicalDamageUnique_1"] = {
		"Refuge in Isolation",
	},
	["DivergentEnemyKnockbackDirectionReversedUniqueGlovesStr5_"] = {
		"Empire's Grasp",
	},
	["DivergentEnergyShieldAdditiveModifiersInsteadApplyToWardUnique__"] = {
		"Faithguard",
	},
	["DivergentEnergyShieldGainedOnBlockUniqueShieldStrInt4"] = {
		"Aegis Aurora",
	},
	["DivergentEnergyShieldPerStrengthUnique__1"] = {
		"Shaper's Touch",
	},
	["DivergentEnergyShieldRechargeOnKillUnique__1__"] = {
		"Sudden Dawn",
	},
	["DivergentEnergyShieldRecoveryRateUnique__1"] = {
		"The Beast Fur Shawl",
	},
	["DivergentEvasionIncreasedByUncappedColdResistanceUnique__1"] = {
		"The Snowblind Grace",
	},
	["DivergentEvasionIncreasedByUncappedColdResistanceUnique__2"] = {
		"The Perfect Form",
	},
	["DivergentEvasionModifersApplyToSpellDamageUnique__1"] = {
		"The Unblinking Eye",
	},
	["DivergentEvasionRatingPerIntelligenceUnique__1"] = {
		"Shaper's Touch",
	},
	["DivergentEvasionRatingPercentOnLowLifeUniqueHelmetDex4"] = {
		"Starkonja's Head",
	},
	["DivergentExcommunicateOnMeleeHitUnique"] = {
		"Hand of Heresy",
	},
	["DivergentFacebreakerUnarmedMoreDamage"] = {
		"Facebreaker",
	},
	["DivergentFireDamageCanPoisonAndLessDurationUnique__1"] = {
		"Volkuur's Guidance",
	},
	["DivergentFireDamageTakenConvertedToPhysicalUnique__1"] = {
		"The Rat Cage",
	},
	["DivergentFireExposureOnHitUnique__1"] = {
		"Eye of Malice",
	},
	["DivergentFireHitAndDoTDamageTakenAsLightningUnique__1"] = {
		"Font of Thunder",
	},
	["DivergentFireResistanceOverrideUnique__1__"] = {
		"Cowl of the Thermophile",
	},
	["DivergentFireShocksUniqueHelmetDexInt4"] = {
		"The Three Dragons",
	},
	["DivergentFortifyEffectSelfGloriousMadnessUnique1"] = {
		"Beacon of Madness",
	},
	["DivergentFreezeDurationUniqueGlovesStrInt3"] = {
		"Southbound",
	},
	["DivergentFreezeEnemiesWhenHitChanceUnique__1"] = {
		"Icetomb",
	},
	["DivergentFrenzyChargeOnCritCloseRangeUnique__1"] = {
		"Usurper's Penance",
	},
	["DivergentFungalAroundWhenStationaryUnique__1_"] = {
		"Sporeguard",
	},
	["DivergentGainArmourEqualToManaReservedUnique__1"] = {
		"Memory Vault",
	},
	["DivergentGainFrenzyChargeOnTrapTriggeredUnique__1"] = {
		"Tinkerskin",
	},
	["DivergentGainLifeOnBlockUnique__1"] = {
		"The Surrender",
	},
	["DivergentGainManaAsExtraEnergyShieldUnique__1"] = {
		"Mindspiral",
	},
	["DivergentGainMaximumEnduranceChargesWhenCritUnique__1"] = {
		"Ambu's Charge",
	},
	["DivergentGainOnslaughtWhileCatsAgilityUnique__1_"] = {
		"Replica Farrul's Fur",
	},
	["DivergentGainSoulEaterStackOnHitUnique__1"] = {
		"Soul Ascension",
	},
	["DivergentGainThaumaturgyBuffRotationUnique__1_"] = {
		"Malachai's Mark",
	},
	["DivergentGhostFurnace1"] = {
		"The Draugur's Lantern",
	},
	["DivergentGlimpseOfEternityWhenHitUnique__1"] = {
		"The Eternity Shroud",
	},
	["DivergentGlobalAddedChaosDamageWardUnique__"] = {
		"Nightgrip",
	},
	["DivergentGlobalIncreaseMinionSpellSkillGemLevelUnique__3"] = {
		"The Devourer of Minds",
	},
	["DivergentGlobalIncreaseMinionSpellSkillGemLevelUnique__4"] = {
		"The Dark Monarch",
	},
	["DivergentGrantAlliesFrenzyChargeOnHitUnique__1"] = {
		"Victario's Charity",
	},
	["DivergentGrantAlliesPowerChargeOnKillUnique__1"] = {
		"Victario's Charity",
	},
	["DivergentGrantsAlliesEnduranceChargeOnHitUnique__1"] = {
		"Replica Victario's Charity",
	},
	["DivergentGrantsAlliesFrenzyChargeOnKillUnique__1_"] = {
		"Replica Victario's Charity",
	},
	["DivergentGrantsAvianTornadoUnique__1__"] = {
		"Saqawal's Flock",
	},
	["DivergentGrantsBirdAspect1_"] = {
		"Saqawal's Talons",
	},
	["DivergentGrantsCatAspect1"] = {
		"Farrul's Bite",
	},
	["DivergentGrantsRavenousSkillUnique__1"] = {
		"Veruso's Ambition",
	},
	["DivergentGrantsSpiderAspect1"] = {
		"Fenumus' Weave",
	},
	["DivergentGrantsSummonArbalistsSkillUnique__1_"] = {
		"Vorana's March",
	},
	["DivergentGrantsSummonBeastRhoaUnique__1"] = {
		"Yriel's Fostering",
	},
	["DivergentGrantsSummonBeastSnakeUnique__1"] = {
		"Yriel's Fostering",
	},
	["DivergentGrantsSummonBeastUrsaUnique__1"] = {
		"Yriel's Fostering",
	},
	["DivergentGrantsSummonVoidSpawnUnique__1"] = {
		"Servant of Decay",
	},
	["DivergentGrantsTouchOfGodUnique__1"] = {
		"Doryani's Fist",
	},
	["DivergentGrantsVoidGazeUnique__1"] = {
		"Eber's Unification",
	},
	["DivergentGraspFromBeyondTrapUnique_1"] = {
		"Hand of the Lords",
	},
	["DivergentHarbingerSkillOnEquipUnique2_5"] = {
		"The Tempest's Liberation",
	},
	["DivergentHarbingerSkillOnEquipUnique2__3"] = {
		"The Immortal Will",
	},
	["DivergentHarbingerSkillOnEquipUnique__3"] = {
		"The Unshattered Will",
	},
	["DivergentHarbingerSkillOnEquipUnique__5"] = {
		"The Tempest's Binding",
	},
	["DivergentHasBrutalShrineBuffUnique__1"] = {
		"Blunderbore",
	},
	["DivergentHasMassiveShrineBuffUnique__1"] = {
		"Blunderbore",
	},
	["DivergentHealAlliesOnDeathUniqueShieldDexInt2"] = {
		"Maligaro's Lens",
	},
	["DivergentIgnoreHexproofUnique___1"] = {
		"Cospri's Will",
	},
	["DivergentImmuneToBurningGroundUniqueBootsStr3"] = {
		"Redblade Tramplers",
	},
	["DivergentImmuneToDesecratedGroundUniqueBootsInt6"] = {
		"Steppan Eard",
	},
	["DivergentImmuneToElementalAilmentsWhileLifeAndManaCloseUnique__1"] = {
		"The Scales of Justice",
	},
	["DivergentIncreaseProjectileAttackDamagePerAccuracyUnique__1"] = {
		"Obscurantis",
	},
	["DivergentIncreaseSocketedSupportGemQualityUnique__1___"] = {
		"The Squire",
	},
	["DivergentIncreasedAttackSpeedUniqueBootsDexInt1"] = {
		"Sundance",
	},
	["DivergentIncreasedDamagePerPowerChargeUnique__1"] = {
		"Inya's Epiphany",
	},
	["DivergentIncreasedDamageToIgnitedTargetsUniqueBootsStrInt3"] = {
		"Gang's Momentum",
	},
	["DivergentIncreasedDamageWhileLeechingUnique__2__"] = {
		"Offering to the Serpent",
	},
	["DivergentIncreasedElementalResistancesUnique__1"] = {
		"Replica Veil of the Night",
	},
	["DivergentIncreasedEvasionIfHitRecentlyUnique___1"] = {
		"Kintsugi",
	},
	["DivergentIncreasedEvasionWithOnslaughtUnique_1"] = {
		"Three-step Assault",
	},
	["DivergentIncreasedExperienceUniqueIntHelmet3"] = {
		"Chitus' Apex",
	},
	["DivergentIncreasedItemRarityUniqueShieldStrDex2"] = {
		"Wheel of the Stormsail",
	},
	["DivergentIncreasedLifeLeechRateUniqueBodyStrDex4"] = {
		"Cherrubim's Maleficence",
	},
	["DivergentIncreasedLifeNoLifeModifiersUnique__1"] = {
		"Utula's Hunger",
	},
	["DivergentIncreasedLifeUniqueBodyStr1"] = {
		"Kaom's Heart",
	},
	["DivergentIncreasedLifeUnique__114"] = {
		"Kaom's Spirit",
	},
	["DivergentIncreasedLifeWhileNoCorruptedItemsUnique__1"] = {
		"Voll's Vision",
	},
	["DivergentIncreasedManaUnique__19"] = {
		"Replica Kaom's Heart",
	},
	["DivergentIncreasedMaximumResistsUniqueShieldStrInt1"] = {
		"Saffell's Frame",
	},
	["DivergentIncreasedPhysicalDamagePercentUnique__4"] = {
		"Gruthkul's Pelt",
	},
	["DivergentIncreasedProjectileDamageUniqueBootsDexInt4"] = {
		"Brinerot Whalers",
	},
	["DivergentIncreasedSpellDamagePerPowerChargeUnique__1"] = {
		"Malachai's Loop",
	},
	["DivergentIncreasedSpiderWebCountUnique__1"] = {
		"Fenumus' Spinnerets",
	},
	["DivergentIronWillUniqueGlovesStrInt4__"] = {
		"Repentance",
	},
	["DivergentItemActsAsConcentratedAOESupportUnique__1"] = {
		"Wyrmsign",
	},
	["DivergentItemFoundRarityIncreaseUniqueBodyStr5"] = {
		"Greed's Embrace",
	},
	["DivergentItemFoundRarityIncreaseUniqueGlovesStrDex2"] = {
		"Aurseize",
	},
	["DivergentItemFoundRarityIncreaseUnique__10"] = {
		"Goldwyrm",
	},
	["DivergentItemFoundRarityIncreaseUnique__7"] = {
		"Sadima's Touch",
	},
	["DivergentItemHasSixLinkedWhiteSocketsUniqueBodyInt6"] = {
		"Tabula Rasa",
	},
	["DivergentItemRarityOnLowLifeUniqueBootsInt1"] = {
		"Wondertrap",
	},
	["DivergentKeystoneAncestralBondUnique__2"] = {
		"Wilma's Requital",
	},
	["DivergentKeystoneCallToArmsUnique__2_"] = {
		"Mutewind Pennant",
	},
	["DivergentKeystoneCorruptedSoulUnique__2_"] = {
		"Mahuxotl's Machination",
	},
	["DivergentKeystoneDivineFleshUnique__1_"] = {
		"Mahuxotl's Machination",
	},
	["DivergentKeystoneEternalYouthUnique__2_"] = {
		"Mahuxotl's Machination",
	},
	["DivergentKeystoneEverlastingSacrificeUnique__1"] = {
		"Mahuxotl's Machination",
	},
	["DivergentKeystoneGlancingBlowsUnique__1___"] = {
		"Emperor's Vigilance",
	},
	["DivergentKeystoneInnerConvictionUnique__1"] = {
		"Voll's Protector",
	},
	["DivergentKeystoneIronGripUnique__1"] = {
		"Giantsbane",
	},
	["DivergentKeystoneSoulTetherUnique__2"] = {
		"Mahuxotl's Machination",
	},
	["DivergentKeystoneUnwaveringStanceUnique__1"] = {
		"Kaom's Roots",
		"Ezomyte Peak",
	},
	["DivergentKeystoneVaalPactUnique__2"] = {
		"Mahuxotl's Machination",
	},
	["DivergentLifeFromEnergyShieldArmourPercentUnique__1"] = {
		"The Apostate",
	},
	["DivergentLifeGainOnEndurangeChargeConsumptionUniqueBodyStrInt6"] = {
		"Kingsguard",
	},
	["DivergentLifeRegenPerMinutePerEnduranceChargeUnique__1"] = {
		"The Restless Ward",
	},
	["DivergentLifeRegenerationFlatOnLowLifeUnique__1"] = {
		"Springleaf",
	},
	["DivergentLifeRegenerationPer500EnergyShieldUnique__1"] = {
		"Mask of the Stitched Demon",
	},
	["DivergentLifeRegenerationWith1000EnergyShieldUnique__1"] = {
		"Mask of the Spirit Drinker",
	},
	["DivergentLightRadiusToDamageUnique_1"] = {
		"Wreath of Phrecia",
	},
	["DivergentLightRadiusUniqueBodyInt8"] = {
		"Zahndethus' Cassock",
	},
	["DivergentLightningAddedAsColdShockedEnemyUnique__1"] = {
		"Replica Heatshiver",
	},
	["DivergentLightningDamageCanPoisonAndLessDurationUnique__1"] = {
		"Volkuur's Guidance",
	},
	["DivergentLightningFreezesUniqueHelmetDexInt4"] = {
		"The Three Dragons",
	},
	["DivergentLightningResistanceOverrideUnique__1_"] = {
		"Cowl of the Ceraunophile",
	},
	["DivergentLinkedMinionsStealRareModsUnique_1"] = {
		"The Hallowed Monarch",
	},
	["DivergentLocalArmourAndEvasionAndEnergyShieldUniqueBodyStrDexInt"] = {
		"Atziri's Splendour",
	},
	["DivergentLocalIncreaseSocketedActiveSkillGemLevelUnique__1"] = {
		"Pragmatism",
	},
	["DivergentLocalIncreaseSocketedAuraGemLevelUnique___3"] = {
		"March of the Legion",
	},
	["DivergentLocalIncreaseSocketedElementalGemUniqueGlovesInt6"] = {
		"Voidbringer",
	},
	["DivergentLocalIncreaseSocketedGemLevelUnique__8"] = {
		"Honourhome",
	},
	["DivergentLocalIncreaseSocketedHeraldLevelUnique__2"] = {
		"Replica Alpha's Howl",
	},
	["DivergentLocalIncreaseSocketedMovementGemLevelUniqueBodyDex5"] = {
		"Bronn's Lithe",
	},
	["DivergentLocalIncreaseSocketedProjectileGemLevelUnique__1"] = {
		"Black Zenith",
	},
	["DivergentManaLeechPermyriadUniqueGlovesStrDex1"] = {
		"Slitherpinch",
	},
	["DivergentManaRegenerationAuraUnique__1"] = {
		"Replica Leer Cast",
	},
	["DivergentManaReservationEfficiencyPerAttributeUnique__1"] = {
		"Mask of the Tribunal",
	},
	["DivergentManaReservationEfficiencyUniqueHelmetDex5_"] = {
		"Replica Alpha's Howl",
	},
	["DivergentMaximumCrabBarriersUnique__1"] = {
		"Craiceann's Carapace",
	},
	["DivergentMaximumFortificationUnique__1"] = {
		"The Celestial Brace",
	},
	["DivergentMaximumFrenzyChargesUniqueBootsStrDex2"] = {
		"Darkray Vectors",
	},
	["DivergentMaximumLifeConvertedToEnergyShieldUnique__2"] = {
		"Ghostwrithe",
	},
	["DivergentMaximumLifePer10DexterityUnique__1"] = {
		"Garukhan's Flight",
	},
	["DivergentMaximumLifeUniqueBodyStrDex1"] = {
		"Belly of the Beast",
	},
	["DivergentMaximumMinionCountUniqueBootsInt4"] = {
		"Bones of Ullr",
	},
	["DivergentMaximumResistanceWithNoEnduranceChargesUnique__1__"] = {
		"Ahn's Heritage",
	},
	["DivergentMaximumResistancesOverrideUnique__1"] = {
		"Loreweave",
	},
	["DivergentMaximumResistancesWhilePoisonedUnique__1"] = {
		"Apep's Slumber",
	},
	["DivergentMeleePhysicalDamagePerDexterityUnique__1_"] = {
		"Shaper's Touch",
	},
	["DivergentMeleeSplashUnique__1"] = {
		"Meginord's Vise",
	},
	["DivergentMeleeWeaponCriticalStrikeMultiplierReplicaUniqueHelmetStr3"] = {
		"Replica Abyssus",
	},
	["DivergentMeleeWeaponCriticalStrikeMultiplierUniqueHelmetStr3"] = {
		"Abyssus",
	},
	["DivergentMineDamageLeechedToYouUnique__1"] = {
		"Machina Mitts",
	},
	["DivergentMinimumEnduranceChargesUnique__1"] = {
		"Ralakesh's Impatience",
	},
	["DivergentMinimumFrenzyChargesUnique__1"] = {
		"Ralakesh's Impatience",
	},
	["DivergentMinimumPowerChargesUnique__1"] = {
		"Ralakesh's Impatience",
	},
	["DivergentMinionAttackBlockChanceUnique__2"] = {
		"Skullhead",
	},
	["DivergentMinionAttackSpeedPerXDexUnique__1"] = {
		"Speaker's Wreath",
	},
	["DivergentMinionChanceToFreezeShockIgnite"] = {
		"Triad Grip",
	},
	["DivergentMinionCriticalStrikeChanceMaximumPowerChargeUnique__1"] = {
		"Ancient Skull",
	},
	["DivergentMinionElementalDamageAddedAsChaosUnique__1"] = {
		"Vis Mortis",
	},
	["DivergentMinionEnergyShieldRechargeDelayUnique__1"] = {
		"Fleshcrafter",
	},
	["DivergentMinionLargerAggroRadiusUnique__1"] = {
		"Maw of Mischief",
	},
	["DivergentMinionLifeAlsoAffectsYouUnique__1"] = {
		"Rigwald's Hunt",
	},
	["DivergentMinionLifeIncreasedByOvercappedFireResistanceUnique__1"] = {
		"The Formless Inferno",
	},
	["DivergentMinionPhysicalDamageAddedAsColdUnique__1_"] = {
		"Grip of the Council",
	},
	["DivergentMinionPhysicalDamageAddedAsFireUnique__1"] = {
		"Replica Grip of the Council",
	},
	["DivergentMinionSpellBlockChanceUnique__2"] = {
		"Skullhead",
	},
	["DivergentMinionsGainYourStrengthUnique__1"] = {
		"The Baron",
	},
	["DivergentModifyableWhileCorruptedUnique__2"] = {
		"Hands of the High Templar",
	},
	["DivergentMovementSpeedPerPoisonOnSelfUnique__1"] = {
		"Temptation Step",
	},
	["DivergentMovementVelocityOnFullLifeUniqueBootsInt3"] = {
		"Shavronne's Pace",
	},
	["DivergentMovementVelocityOverrideUnique__1"] = {
		"The Stampede",
	},
	["DivergentMovementVelocityOverrideUnique__2"] = {
		"Replica Stampede",
	},
	["DivergentMovementVelocityPerEvasionLesserUnique__1"] = {
		"Queen of the Forest",
	},
	["DivergentMovementVelocityPerFrenzyChargeUniqueBootsDex4"] = {
		"The Blood Dance",
	},
	["DivergentMovementVelocityPerFrenzyChargeUnique__2"] = {
		"Replica Restless Ward",
	},
	["DivergentMovementVelocityUniqueHelmetStrDex2"] = {
		"Devoto's Devotion",
	},
	["DivergentMovementVelocityUnique___6"] = {
		"Seven-League Step",
	},
	["DivergentMovementVelocityWhileOnFullEnergyShieldUniqueBootsDex8"] = {
		"Nomic's Storm",
	},
	["DivergentNearbyEnemiesAreScorchedUnique__1"] = {
		"Legacy of Fury",
	},
	["DivergentNearbyEnemiesCannotCritUnique__1"] = {
		"Garb of the Ephemeral",
	},
	["DivergentNearbyEnemiesHaveReducedAllResistancesUnique__1"] = {
		"Crown of the Tyrant",
	},
	["DivergentNearbyEnemyReservesLifeUnique__1"] = {
		"Blood Price",
	},
	["DivergentNearbyStationaryEnemiesGainVinesUnique__1"] = {
		"Inextricable Fate",
	},
	["DivergentNoExtraBleedDamageWhileMovingUnique__1"] = {
		"The Infinite Pursuit",
	},
	["DivergentNonInstantManaRecoveryAlsoAffectsLifeUnique__1"] = {
		"Indigon",
	},
	["DivergentOnslaughtBuffOnKillUniqueHelmet1"] = {
		"Thrillsteel",
	},
	["DivergentOnslaughtEffectUnique__1"] = {
		"Daresso's Defiance",
	},
	["DivergentOnslaughtOnVaalSkillUseUniqueGlovesStrDex4"] = {
		"Vaal Caress",
	},
	["DivergentOnslaughtWhileNotOnLowManaUnique__1_"] = {
		"Dance of the Offered",
	},
	["DivergentPainAttunement"] = {
		"Crown of Thorns",
	},
	["DivergentPercentDexterityIfStrengthHigherThanIntelligenceUnique__1"] = {
		"Fractal Thoughts",
	},
	["DivergentPercentageDexterityUniqueHelmetStrDex6"] = {
		"Black Sun Crest",
	},
	["DivergentPercentageIntelligenceUniqueHelmetStrDex6"] = {
		"Black Sun Crest",
	},
	["DivergentPercentageStrengthUniqueHelmetStrDex6"] = {
		"Black Sun Crest",
	},
	["DivergentPerfectAgonyIfCritRecentlyUnique__1"] = {
		"Replica Atziri's Acuity",
	},
	["DivergentPetrificationStatueUnique__1"] = {
		"Gorgon's Gaze",
	},
	["DivergentPhasingIfBlockedRecentlyReplicaUnique__1"] = {
		"Replica Mistwall",
	},
	["DivergentPhasingIfBlockedRecentlyUnique__1"] = {
		"Mistwall",
	},
	["DivergentPhysAddedAsChaosWithMaxPowerChargesUnique__1"] = {
		"Ahn's Contempt",
	},
	["DivergentPhysicalAddedAsColdUnique__2"] = {
		"Kaltenhalt",
	},
	["DivergentPhysicalDamageConvertToChaosBodyStrInt4"] = {
		"Lightbane Raiment",
	},
	["DivergentPhysicalDamageOnSkillUseUniqueHelmetInt8"] = {
		"Scold's Bridle",
	},
	["DivergentPhysicalDamageReductionWhileNotMovingUnique__1"] = {
		"The Red Trail",
	},
	["DivergentPhysicalDamageTakenAsLightningPercentUniqueBodyStrDex2"] = {
		"Lightning Coil",
	},
	["DivergentPhysicalDamageTakenPercentToReflectUniqueBodyStr2"] = {
		"Bramblejack",
	},
	["DivergentPhysicalHitAndDoTDamageTakenAsFireUnique__2"] = {
		"Cloak of Flame",
	},
	["DivergentPlaceAdditionalMineWith600DexterityUnique__1"] = {
		"Curtain Call",
	},
	["DivergentPlaceAdditionalMineWith600IntelligenceUnique__1"] = {
		"Curtain Call",
	},
	["DivergentPoisonDotMultiplierPerFrenzyChargeUniqueGlovesDexInt5"] = {
		"Snakebite",
	},
	["DivergentPowerChargeOnCriticalStrikeChanceUnique__1"] = {
		"Skyforth",
	},
	["DivergentPowerChargeOnHitWebbedEnemyUnique__1"] = {
		"Fenumus' Toxins",
	},
	["DivergentPowerChargeOnTrapThrowChanceUniqueShieldDexInt1"] = {
		"Jaws of Agony",
	},
	["DivergentPowerFrenzyOrEnduranceChargeOnKillUnique__1"] = {
		"Lochtonial Caress",
	},
	["DivergentProfaneGroundInsteadOfConsecratedGround__1_"] = {
		"Broken Faith",
	},
	["DivergentProjectileAvoidUnique"] = {
		"Azadi Crest",
	},
	["DivergentProjectileSpeedUnique__8"] = {
		"The Fledgling",
	},
	["DivergentProjectileSpeedUnique___1"] = {
		"Winds of Change",
	},
	["DivergentProjectilesChainWhilePhasingUnique__1"] = {
		"Replica Voidwalker",
	},
	["DivergentPunishmentOnMeleeBlockUniqueShieldInt4"] = {
		"Sentari's Answer",
	},
	["DivergentPurityOfFireUnique__6"] = {
		"Doryani's Delusion",
	},
	["DivergentPurityOfIceUnique__6"] = {
		"Doryani's Delusion",
	},
	["DivergentPurityOfLightningUnique__6"] = {
		"Doryani's Delusion",
	},
	["DivergentQuicksilverFlaskAppliesToAlliesUnique__1"] = {
		"Victario's Flight",
	},
	["DivergentRageCasterStats50PercentValueUnique__1"] = {
		"Ravenous Passion",
	},
	["DivergentRagingSpiritFireSplashDamageUnique__1"] = {
		"Mark of the Red Covenant",
	},
	["DivergentRandomCurseWhenHitChanceUnique__1"] = {
		"Ylfeban's Trickery",
	},
	["DivergentRandomMovementVelocityWhenHitUnique__1"] = {
		"Gamblesprint",
	},
	["DivergentRangedAttackDamageReducedUniqueShieldStr1"] = {
		"Lioneye's Remorse",
	},
	["DivergentRangedWeaponPhysicalDamagePlusPercentUnique__1"] = {
		"Ashrend",
	},
	["DivergentRecoverLifeOnSuppressUnique__1"] = {
		"Elevore",
	},
	["DivergentReducedReservationForSocketedCurseGemsUnique__1"] = {
		"Heretic's Veil",
	},
	["DivergentReflectDamageToAttackersOnBlockUniqueShieldDex5"] = {
		"Thousand Teeth Temu",
	},
	["DivergentRegenerateLifeNotUnhingedUnique__1"] = {
		"Doppelganger Guise",
	},
	["DivergentRepeatingShockwaveUnique__1"] = {
		"Abberath's Hooves",
	},
	["DivergentResistancesOfWebbedEnemiesUnique__1"] = {
		"Fenumus' Shroud",
	},
	["DivergentRetaliateSkillUseWindowDuration_1"] = {
		"Bitter Instinct",
	},
	["DivergentReviveEnemiesOnKillUnique__1"] = {
		"Breathstealer",
	},
	["DivergentSacrificeLifeToGainESUnique__1"] = {
		"Demon Stitcher",
	},
	["DivergentSacrificialZealOnSkillUseUnique__1_"] = {
		"Hand of the Fervent",
	},
	["DivergentSavageBarnacleMod_1"] = {
		"Seablister",
	},
	["DivergentScorchOnEnemiesOnBlockUnique__1"] = {
		"Dawnbreaker",
	},
	["DivergentSelfOfferingEffectUnique__2"] = {
		"The Queen's Hunger",
	},
	["DivergentSetElementalResistancesUniqueHelmetStrInt4"] = {
		"Veil of the Night",
	},
	["DivergentShareEnduranceChargesWithParty"] = {
		"Ambu's Charge",
	},
	["DivergentSharedSufferingUnique__1"] = {
		"Leper's Alms",
	},
	["DivergentShockEffectUnique__2"] = {
		"Stormcharger",
	},
	["DivergentShockProliferationUnique__1"] = {
		"Storm's Gift",
	},
	["DivergentShockProliferationUnique__2"] = {
		"Esh's Mirror",
	},
	["DivergentShockedEnemiesExplodeUnique__1_"] = {
		"Inpulsa's Broken Heart",
	},
	["DivergentShockedGroundWhileMovingUnique__1"] = {
		"Wake of Destruction",
	},
	["DivergentShrineBuffEffectUniqueHelmetDexInt3"] = {
		"The Gull",
	},
	["DivergentSimulatedRampageDexInt6"] = {
		"Shadows and Dust",
	},
	["DivergentSimulatedRampageStrDex5"] = {
		"Null and Void",
	},
	["DivergentSimulatedRampageStrInt2"] = {
		"Flesh and Spirit",
	},
	["DivergentSkeletonWarriorsPermanentMinionUnique__1"] = {
		"Alberon's Warpath",
	},
	["DivergentSkillsExertAttacksDoNotCountChanceUnique__1"] = {
		"Deidbell",
	},
	["DivergentSocketedCursesAreReflectedUniqueGlovesStrInt1"] = {
		"Shackles of the Wretched",
	},
	["DivergentSocketedGemQualityUnique__1"] = {
		"Crest of Desire",
	},
	["DivergentSocketedGemsGetElementalProliferationUniqueBodyInt5"] = {
		"Thousand Ribbons",
	},
	["DivergentSocketedGemsHaveAddedChaosDamageUnique__3"] = {
		"The Covenant",
	},
	["DivergentSocketedGemsHaveReducedManaCostUniqueHelmetDexInt5"] = {
		"The Vertex",
	},
	["DivergentSocketedGemsInBlueSocketEffectUnique__1"] = {
		"Dialla's Malefaction",
	},
	["DivergentSocketedGemsInGreenSocketEffectUnique__1"] = {
		"Dialla's Malefaction",
	},
	["DivergentSocketedGemsInRedSocketEffectUnique__1"] = {
		"Dialla's Malefaction",
	},
	["DivergentSocketedGemsSupportedByBlasphemyUnique__3"] = {
		"Heretic's Veil",
	},
	["DivergentSocketedGemsSupportedByCastOnDeathUniqueHelmetStrInt5"] = {
		"The Broken Crown",
	},
	["DivergentSocketedGemsSupportedByPierceUniqueBodyStr6"] = {
		"Lioneye's Vision",
	},
	["DivergentSocketedItemsHaveReducedReservationUniqueBodyDexInt4"] = {
		"Victario's Influence",
	},
	["DivergentSocketedItemsHaveReducedReservationUniqueShieldStrInt2"] = {
		"Prism Guardian",
	},
	["DivergentSocketedWarcryCooldownCountUnique__1"] = {
		"Echoes of Creation",
	},
	["DivergentSpellBlockPercentageOnLowLifeUniqueShieldStrDex1_"] = {
		"Daresso's Courage",
	},
	["DivergentSpellBlockPercentageUniqueBootsInt5"] = {
		"Rainbowstride",
	},
	["DivergentSpellCriticalStrikeChancePerLifeUnique__1"] = {
		"Rathpith Globe",
	},
	["DivergentSpellCriticalStrikeChancePerSpectreUnique__1_"] = {
		"Bitterbind Point",
	},
	["DivergentSpellCriticalStrikeChanceUniqueBootsStrDex5"] = {
		"Mutewind Whispersteps",
	},
	["DivergentSpellDamageFromMainHandWeaponDamageUnique__1"] = {
		"Sandstorm Visage",
	},
	["DivergentSpellDamageModifiersApplyToAttackDamageUniqueHelmetInt7"] = {
		"Crown of Eyes",
	},
	["DivergentSpellDamageUniqueGlovesInt2"] = {
		"Doedre's Tenure",
	},
	["DivergentSpellDodgeUniqueBootsDex7New"] = {
		"Atziri's Step",
	},
	["DivergentSpellImpaleOnCritChanceUnique__1"] = {
		"Entropic Devastation",
	},
	["DivergentSpellsCriticalChanceFinalRepeatUnique__1"] = {
		"Plume of Pursuit",
	},
	["DivergentSpellsDoubleDamageChanceUnique__1"] = {
		"Malachai's Simula",
	},
	["DivergentSpiritMinionRefreshOnUniqueHitUnique__1"] = {
		"Replica Bones of Ullr",
	},
	["DivergentStealChargesOnHitPercentUniqueGlovesStrDex6"] = {
		"Surgebinders",
	},
	["DivergentStrUniqueShieldTriggerShieldShatterOnBlock"] = {
		"Shattershard",
	},
	["DivergentStunAvoidancePerHeraldUnique__1"] = {
		"The Coming Calamity",
	},
	["DivergentSupportedByFasterCastUnique__1"] = {
		"Kalisa's Grace",
	},
	["DivergentSupportedByLesserPoisonUnique__1"] = {
		"Dendrobate",
	},
	["DivergentSupportedByRageUnique__1__"] = {
		"Hateforge",
	},
	["DivergentSupportedByVileToxinsUnique__1"] = {
		"The Embalmer",
	},
	["DivergentTakeNoExtraDamageFromCriticalStrikesUnique__1"] = {
		"The Brass Dome",
	},
	["DivergentTemporalChainsOnProjectileBlockUniqueShieldInt4"] = {
		"Sentari's Answer",
	},
	["DivergentTotemLeechLifeToYouUnique__1"] = {
		"Trolltimber Spire",
	},
	["DivergentTotemReflectFireDamageUnique__1_"] = {
		"Torchoak Step",
	},
	["DivergentTouchedByTormentedSpiritsUnique__1"] = {
		"Fairgraves' Tricorne",
	},
	["DivergentTransfigurationOfBodyUnique__1"] = {
		"Crown of the Inward Eye",
	},
	["DivergentTransfigurationOfMindUnique__1"] = {
		"Crown of the Inward Eye",
	},
	["DivergentTransfigurationOfSoulUnique__1_"] = {
		"Crown of the Inward Eye",
	},
	["DivergentTrapThrowSpeedUniqueBootsDex6"] = {
		"Deerstalker",
	},
	["DivergentTreatResistancesAsMaxChanceUnique__1"] = {
		"Kiloava's Bluster",
	},
	["DivergentTriggerFeastOfFleshSkillUnique__1_"] = {
		"The Devouring Diadem",
	},
	["DivergentTriggerRainOfArrowsOnBowAttackUnique__1"] = {
		"Lioneye's Paws",
	},
	["DivergentTriggerShadeFormWhenHitUnique__1"] = {
		"Replica Eternity Shroud",
	},
	["DivergentTriggerSocketedCurseSkillsOnCurseUnique__1_"] = {
		"Vixen's Entrapment",
	},
	["DivergentTriggerSocketedElementalSpellOnBlockUnique__1"] = {
		"Svalinn",
	},
	["DivergentTriggerSocketedSpellOnBowAttackUnique__2"] = {
		"Asenath's Mark",
	},
	["DivergentTriggerToxicRainOnBowAttackUnique__1"] = {
		"Replica Lioneye's Paws",
	},
	["DivergentTriggeredColdAegisSkillUnique__1"] = {
		"Vix Lunaris",
	},
	["DivergentTriggeredElementalAegisSkillUnique__1_"] = {
		"Magna Eclipsis",
	},
	["DivergentTriggeredFireAegisSkillUnique__1_"] = {
		"Invictus Solaris",
	},
	["DivergentTriggeredLightningAegisSkillUnique__1"] = {
		"Perepiteia",
	},
	["DivergentTriggeredPhysicalAegisSkillUnique__1"] = {
		"The Ghastly Theatre",
	},
	["DivergentUnaffectedByChillLeechingManaUnique__1"] = {
		"Stormseeker",
	},
	["DivergentUnaffectedByCursesUnique__1"] = {
		"Atziri's Reflection",
	},
	["DivergentUnaffectedByDamagingAilmentsUnique__1"] = {
		"Kahuturoa's Certainty",
	},
	["DivergentUnaffectedByPoisonUnique__1_"] = {
		"Maw of Conquest",
	},
	["DivergentUnaffectedByShockLeechingESUnique__1"] = {
		"Stormseeker",
	},
	["DivergentUnwaveringStanceUnique_2"] = {
		"Cowards' Wail",
	},
	["DivergentVaalPactIfCritRecentlyUnique__1"] = {
		"Atziri's Acuity",
	},
	["DivergentVulnerabilityOnBlockUniqueShieldStrDex3"] = {
		"The Deep One's Hide",
	},
	["DivergentWarcryAreaOfEffectUnique__2"] = {
		"Howlcrack",
	},
	["DivergentWarcryCooldownSpeedUnique__1"] = {
		"The Eternal Apple",
	},
	["DivergentWarcryCooldownSpeedUnique__2"] = {
		"Redblade Banner",
	},
	["DivergentWarcryCorpseExplosionUnique__1"] = {
		"Kaom's Command",
	},
	["DivergentWarcryGrantsArcaneSurgeUnique__1"] = {
		"Brinerot Flag",
	},
	["DivergentWarcrySpeedUnique__1"] = {
		"Akoya's Gaze",
	},
	["DivergentWintertideBrandChillEffectUnique__1_"] = {
		"Replica Allelopathy",
	},
	["DivergentWitherOnHitChanceUnique__1"] = {
		"Abhorrent Interrogation",
	},
	["DivergentZealotsOathUnique__1"] = {
		"Geofri's Sanctuary",
	},
	["DivergentZombiesNeedNoCorpsesUnique__1"] = {
		"Aukuna's Will",
	},
}
