---
name: Run Tests
on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run_build_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v4
      - name: Fetch Dev branch
        id: get-dev-ref
        run: |
            git fetch --depth=1 origin dev
            echo "devref=$(git rev-parse origin/dev)" >> "$GITHUB_OUTPUT"
      - name: Download Dev branch cache
        id: download-dev-ref-cache
        uses: dawidd6/action-download-artifact@3ecf4024886f219d9290351234889bfb45d1b9da
        with:
          name: corpus-cache-devref-${{ steps.get-dev-ref.outputs.devref }}
          path: /tmp/cache/
          if_no_artifact_found: warn
          search_artifacts: true
      - name: Calculate build xmls and differences between them
        shell: bash
        run: |
            mkdir /tmp/cache || true # Make sure /tmp/cache exists. Ignore exit code
            chmod -R 777 /tmp/cache && docker compose run -v '/tmp/cache/:/cache' -e 'CACHEDIR=/cache' busted-diff | tee /tmp/dockerlog
      - name: Generate artefact
        run: |
          sed -n '/Runtime comparison for/,/Savefile Diff for/{/Savefile Diff for/!p;}' /tmp/dockerlog > /tmp/artefact
          sed -n '/Savefile Diff for/, $p' /tmp/dockerlog >> /tmp/artefact
          [ -s /tmp/artefact ] || rm /tmp/artefact
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: build-diff-output
          path: /tmp/artefact
      - name: Upload dev ref cache
        if: ${{ steps.download-dev-ref-cache.outputs.found_artifact == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: corpus-cache-devref-${{ steps.get-dev-ref.outputs.devref }}
          path: /tmp/cache/
