name: Create new installer
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                repository: 'https://github.com/PathOfBuildingCommunity/PathOfBuilding-Installer'
                ref: 'master'
            - name: Create installer
              run: 'python3 make_release.py'
            - name: Upload artifact
              run: 'gh release upload ${{ github.event.release.tag_name }} Dist/* --clobber'

